from pathlib import Path
import datetime,hashlib,json,shutil
B=Path('/home/charl/defiformal/review/semantic-kernel/program-execution-20260908');O=B/'p28-depeg-source-preparation';h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def put(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
anchors=[]
def add(id,path,needle,claim):
 p=O/'source'/path;lines=p.read_text().splitlines();matches=[i+1 for i,line in enumerate(lines) if needle in line];assert matches,(id,needle);anchors.append({'id':id,'path':'source/'+path,'sha256':h(p),'needle':needle,'matching_lines':matches,'static_observation':claim,'proof_or_execution':False})
p='contracts/DepegProduct.sol';u='contracts/UsdcPriceDataProvider.sol';a='contracts/AggregatorDataProvider.sol'
add('protected-wallet-authority',p,'msg.sender == getProtectedWallet(processId)','Claim creation uses onlyProtectedWallet and onlyMatchingPolicy; source caller identity is protected wallet, not necessarily policy holder.')
add('attestation-entry',p,'function addDepegBalances(','This function is onlyOwner. It accepts owner-supplied historical wallet balance and a block number matching the configured depeg block. It does not verify a historical account proof or real-world truth.')
add('invalid-attestation-batch-item',p,'emit LogDepegDepegBalanceError(','A malformed individual wallet/block entry is skipped and emits an error event, while valid entries can be stored. This is not a whole-batch executor refusal.')
add('attestation-overwrite',p,'_depegBalance[depegBalance.wallet] = depegBalance;','Owner can overwrite a stored balance at this point; a frozen/final attestation assumption is not automatically enforced by this assignment.')
add('claim-admission',p,'require(this.policyIsAllowedToClaim(processId)','Claim creation requires depegged product state, policy unexpired at depeg, within grace, and no prior claim, via policyIsAllowedToClaim; failure reverts DP-030.')
add('claim-not-terminal',p,'_policiesWithOpenClaims.add(processId);','Creation records a claim and expires the policy, then queues processing. Claim creation/expiry is not payment or disappearance of the obligation.')
add('public-process',p,'function processPolicy(bytes32 processId)','Processing is public and state-gated, not onlyOwner; authority enters through claim creation, owner balance entry and underlying GIF services.')
add('process-set-refusal',p,'ERROR:DP-042:NOT_IN_PROCESS_SET','An unqueued/already-removed processId is rejected before processing. Formal at-most-once success requires transaction/call-path assumptions and source state semantics.')
add('missing-attestation-refusal',p,'ERROR:DP-043:DEPEG_BALANCE_MISSING','A queued claim with no stored depeg block for its protected wallet reverts. This is a concrete missing-attestation refusal candidate.')
add('zero-attestation-refusal',p,'ERROR:DP-044:DEPEG_BALANCE_ZERO','A zero attested balance is a separate explicit refusal; it is not successful zero payout.')
add('aggregate-coverage-budget',p,'uint256 amountLeftToProcess = depegBalance - _processedBalance[protectedWallet];','Across-policy processed balance is subtracted from attested wallet balance, then caps protected amount. If owner later lowers balance below processed balance, Solidity checked subtraction can revert before the explicit exhausted-balance guard.')
add('processed-budget-update',p,'_processedBalance[protectedWallet] += protectedAmount;','Processing consumes protected token amount across policies, distinct from payout-currency amount. Operation order matters when coverage is oversubscribed.')
add('lifecycle-payout',p,'_processPayout(processId, payoutId);','The path confirms claim, creates payout, calls GIF payout processing, and closes policy; actual GIF service/controller/treasury semantics and custody are required to establish discharge, not merely these call names.')
add('integer-payoff',p,'claimAmount = (tokenAmount * (targetPrice - depegPrice)) / targetPrice;','Claim formula uses integer truncation and a source-defined protected minimum depeg price. Preserve token units, price scale, coverage cap, arithmetic bounds and remaining residue.')
add('manual-block-authority',u,'function setDepeggedBlockNumber(','Owner sets a historical block number after recorded depeg. The require only establishes depeg state; supplied block correctness is an external data assumption.')
add('test-feed-authority',a,'function setRoundData (','Test data setter is onlyOwner and onlyTestnet. Mainnet/goerli branch forwards configured aggregator data; local injected observations are not live feed execution.')
put(O/'source-navigation.json',{'utc':now(),'anchors':anchors,'anchor_count':len(anchors),'scope':'Static source navigation. No compiler, contract execution, Lean proof, deployed identity or source-entry acceptance.','P28_accepted':False})
m=json.loads((O/'source-manifest.json').read_text())
(O/'README.md').write_text(f'''# P28 depeg-insurance source candidate

Root captured {m['file_count']} official Etherisc depeg-contracts files at commit `{m['commit']}`: {m['traversed_source_files']} selected Solidity sources, three unexecuted reference tests and five configuration/documentation files. Each matches the pinned Git tree blob. There are {len(m['local_import_edges'])} local lexical import edges and {len(m['unresolved_external_imports'])} external import occurrences in this initial packet. Dependencies and full workflow closure require separate evidence.

This candidate has actual claim/payout lifecycle logic. The earlier eSusFarm candidate is retained as rejected mock evidence. A repository/product name or compiling stub cannot satisfy P28.

The protected wallet creates a claim under product/policy/depeg/time gates. An owner separately supplies historical wallet balances and a depeg block number. These transactions establish on-chain authorization and data presence, not historical-account truth, oracle truth or legal validity. Individual malformed balance batch items emit errors and are skipped; this differs from a reverted batch. The owner can overwrite balances, so a frozen/final attestation assumption requires justification.

`processPolicy` is public. It requires a queued claim, a nonzero stored depeg block, a positive balance, and remaining unprocessed coverage. Missing attestation uses DP-043; zero balance DP-044 is a distinct refusal. It caps the protected amount across policies, confirms the claim, creates and processes a payout through GIF, then closes the policy. Claim creation/expiry alone is not discharge. The source comments identify policy holder as payout recipient, distinct from protected wallet; underlying GIF treasury behavior must be checked before accepting that observation. Solidity transaction rollback is needed to relate mutations before later reverts to externally observable unchanged state; no runtime rollback proof is claimed here.

Pricing derives from the configured aggregator/provider plus owner-supplied depeg block and balances. Owner test-feed setters are restricted to the source's testnet classifications. Local injected prices cannot establish live feed behavior. Price scaling, protected depeg cap, integer division residue, checked arithmetic, custody/token behavior, external oracle/data truth and legal interpretation remain explicit assumptions.

Brownie declares solc0.8.2, optimizer200, null/default EVM target, OpenZeppelin4.7.3, Chainlink1.10.0 and GIF git refs3b0002a/b58fd27. package.json instead declares @chainlink/contracts0.4.1 and @etherisc/gif-interface2.0.0-a8c9822. These are different declared dependency routes; do not silently mix npm dependencies into the Brownie source route or claim either configuration was executed. No installed compiler identity, compile success, reference test execution, deployment identity or P28 proof is established by this packet.

Tasks29.1–29.3 remain open: freeze source-faithful discharge observations/assumptions with independent review; AGY implements ConditionalClaims and authorized lifecycle proofs; execute successful discharge and real missing-attestation refusal, unauthorized-discharge mutant and source-independent disappearance negative. If Claims exports are reused, P07 dependency remains required.
''');shutil.copy2(__file__,O/'scope.py');put(O/'root-seal.json',{'utc':now(),'files':{str(p.relative_to(O)):h(p) for p in O.rglob('*') if p.is_file()},'P28_accepted':False});print(json.dumps({'source_files':m['file_count'],'anchors':len(anchors),'sealed_files':len(json.loads((O/'root-seal.json').read_text())['files']),'acceptance':False}))
