from pathlib import Path
import json,hashlib,tarfile,difflib,re,datetime,shutil
R=Path('/home/charl/defiformal');B=R/'review/semantic-kernel/program-execution-20260908';O=B/'p19-r21-root-scope';O.mkdir(exist_ok=False);h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();read=lambda p:json.loads(p.read_text());put=lambda p,d:p.write_text(json.dumps(d,indent=2)+'\n');m=read(B/'p19-roundtrip-proof-agy-r21-terminal-manifest.json');prev=read(B/'p19-roundtrip-proof-agy-r20-terminal-manifest.json');W=Path(m['worktree']);assert not Path('/proc/2141829').exists();before={x['path']:x['sha256'] for x in prev['files']};changed=[x['path'] for x in m['files'] if before.get(x['path'])!=x['sha256']];assert changed==['lean/DefiKernel/Certificates/CanonicalJson.lean']
path=changed[0]
with tarfile.open(B/prev['archive']) as tar:old=tar.extractfile(path).read().decode()
new=(W/path).read_text();diff=''.join(difflib.unified_diff(old.splitlines(True),new.splitlines(True),fromfile='R20/'+path,tofile='R21/'+path));(O/'CanonicalJson.diff').write_text(diff);pattern=r'^\s*(?:@\[[^\n]*\]\s*)?(?:theorem|lemma)\s+(\S+)';prior_names=set(re.findall(pattern,old,re.M));new_names=[n for n in re.findall(pattern,new,re.M) if n not in prior_names];assert len(new_names)==30
assert old.split('end DefiKernel.Certificates')[0].rstrip()==new.split('/-- Predicate for character suffixes')[0].rstrip()
assert not (W/'review/semantic-kernel/certificates/p19/implementation/agy-r21-proof').exists();process=read(B/'p19-roundtrip-proof-agy-r21-process.json');log=Path(read(B/'p19-roundtrip-proof-agy-r21-dispatch.json')['log']);assert h(log)==process['log_sha256'];observed=[]
for line in log.read_text().splitlines():
 try:d=json.loads(line).get('step_update',{})
 except:continue
 if d.get('tool_name')=='run_command':observed.append({'step_index':d.get('step_index'),'state':d.get('state'),'duration_seconds':d.get('duration_seconds'),'tool_info':d['tool_info']})
put(O/'native-command-observations.json',{'native_sha256':h(log),'observed_run_command_events':len(observed),'events':observed,'claim':'Native observations may repeat steps and truncate command text. They do not expose reliable per-command stdout/stderr/exit receipts; no successful build or test count inferred.','acceptance':False})
inv=read(B/'p19-r21-root-inventory/command.json');assert inv['theorem_lemma_total']==448 and inv['standard_axiom_records']==415 and inv['zero_axiom_records']==33
record={'schema':'defiformal-p19-r21-root-scope/v1','utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'candidate_archive_sha256':m['sha256'],'frozen_files':m['file_count'],'changed_production_files':changed,'historical_CanonicalJson_prefix_unchanged':True,'new_theorem_names':new_names,'new_theorems':30,'new_definition':'NonDigitHead','theorem_lemma_total':448,'standard_axiom_records':415,'zero_axiom_records':33,'root_inventory':'p19-r21-root-inventory/root-seal.json','strongest_results':['tokenizeFuel_tree derives exact suffix/fuel concatenation for arbitrary TreeJson with NonDigitHead suffix.','tokens_length_le_encode_length supplies noncircular fuel bound.','tokenize_tree proves tokenizer(TreeJson.encode t)=ok(TreeJson.tokens t) for every t.','parseCanonicalJson_tree proves full serialized TreeJson text parses to toJson under TreeJson.Valid and TreeJson.depth<=64.'],'unchanged':'Correspondence, Decode, Encode, Schema and other candidate files match R20.','remaining':['Production whole-module TreeJson representation and depth/validity connection to unchanged StructurallyAdmissibleIR.','Production scanner admission and main EncodeDecodeRoundtripStatement, followed by remaining P19 acceptance obligations.'],'author_evidence_gap':'Requested agy-r21-proof directory absent. Native result SUCCESS/exit0 returned repeated waiting messages, not a proof completion report. Native command observations lack reliable raw per-command results and some text is truncated; no R21 build/test success count credited from them.','root_evidence':'Root exact448 #print inventory succeeds against terminal author build. Fresh isolated R21 reviewer rebuild still pending.','native_conversation_id':process['sessions'][0],'native_reported_models':process['reported_models'],'native_exit':process['process_exit'],'P19_accepted':False,'whole_program_complete':False}
put(O/'scope.json',record);shutil.copy2(__file__,O/'verify.py');files={p.name:h(p) for p in O.iterdir() if p.is_file()};put(O/'root-seal.json',{'utc':record['utc'],'files':files,'file_count':len(files),'acceptance':False});put(B/'p19-roundtrip-proof-agy-r21-root-precheck.json',record);print(json.dumps({'new_theorems':30,'total':448,'generic_serialized_TreeJson_inverse':True,'author_report_absent':True,'whole_module_inverse':False}))
