from pathlib import Path
import json,hashlib,datetime,urllib.request,subprocess,time,shutil,gzip
r=Path('/home/charl/defiformal');b=r/'review/semantic-kernel/program-execution-20260908';base=b/'p23-v1-source-closure';o=b/'p23-v1-compile-readiness';cache=Path('/home/charl/.cache/defiformal-program/program-execution-20260908/p23-v1-compiler');old=cache.parent/'p17-source-readiness';o.mkdir(exist_ok=False);cache.mkdir(exist_ok=False);sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat();write=lambda p,v:p.write_text(json.dumps(v,indent=2)+'\n')
oldrec=json.loads((old/'compiler-acquisition.json').read_text());assert sha(old/'solc-bin-list.json')==oldrec['index_sha256'];idx=json.loads((old/'solc-bin-list.json').read_text());entry=next(e for e in idx['builds'] if e['version']=='0.6.11');assert idx['releases']['0.6.11']==entry['path'];binary=cache/entry['path'];url='https://raw.githubusercontent.com/ethereum/solc-bin/gh-pages/linux-amd64/'+entry['path'];data=urllib.request.urlopen(url,timeout=45).read();binary.write_bytes(data);assert sha(binary)==entry['sha256'].removeprefix('0x');binary.chmod(0o755);version=subprocess.run([str(binary),'--version'],capture_output=True);(o/'version.stdout').write_bytes(version.stdout);(o/'version.stderr').write_bytes(version.stderr);assert version.returncode==0 and b'0.6.11+commit.5ef660b1' in version.stdout;shutil.copy2(old/'solc-bin-list.json',o/'solc-bin-list.json');write(o/'compiler-acquisition.json',{'utc':now(),'index_url':oldrec['index_url'],'index_sha256':oldrec['index_sha256'],'index_capture_utc':oldrec['utc'],'binary_url':url,'upstream_entry':entry,'binary_path':str(binary),'binary_sha256':sha(binary),'version_exit':version.returncode,'version_stdout_sha256':sha(o/'version.stdout'),'requested_compiler':'0.6.11','reported_compiler':version.stdout.decode().strip()})
closure=json.loads((base/'readiness.json').read_text());sources={}
for n,v in closure['source_files'].items():
 p=base/'upstream'/n;assert sha(p)==v['sha256'],n;sources[n]={'content':p.read_text()}
settings={'optimizer':{'enabled':True,'runs':100},'evmVersion':'istanbul','outputSelection':{'*':{'*':['abi','evm.bytecode.object','evm.deployedBytecode.object']}}};inp={'language':'Solidity','sources':sources,'settings':settings};ip=o/'standard-input.json';write(ip,inp);argv=[str(binary),'--standard-json'];start=time.time();proc=subprocess.run(argv,input=ip.read_bytes(),capture_output=True,cwd=cache,timeout=180);(o/'compiler.stdout.json').write_bytes(proc.stdout);(o/'compiler.stderr').write_bytes(proc.stderr);output=json.loads(proc.stdout);errors=[e for e in output.get('errors',[]) if e.get('severity')=='error'];warnings=[e for e in output.get('errors',[]) if e.get('severity')=='warning'];inventory={}
for file,cs in output.get('contracts',{}).items():
 for n,c in cs.items():
  bc=c.get('evm',{}).get('bytecode',{}).get('object','');runtime=c.get('evm',{}).get('deployedBytecode',{}).get('object','');inventory[file+':'+n]={'creation_bytecode_hex_chars':len(bc),'runtime_bytecode_hex_chars':len(runtime),'creation_bytecode_sha256':hashlib.sha256(bc.encode()).hexdigest(),'runtime_bytecode_sha256':hashlib.sha256(runtime.encode()).hexdigest(),'abi_entries':len(c.get('abi',[]))}
key='packages/contracts/contracts/TroveManager.sol:TroveManager';passed=proc.returncode==0 and not errors and inventory.get(key,{}).get('creation_bytecode_hex_chars',0)>0;rec={'schema':'defiformal-p23-source-compile-readiness/v1','utc':now(),'source_commit':closure['commit'],'source_closure_manifest_sha256':sha(base/'manifest.json'),'source_files':len(sources),'command':argv,'cwd':str(cache),'compiler_binary_sha256':sha(binary),'input_sha256':sha(ip),'stdout_sha256':sha(o/'compiler.stdout.json'),'stderr_sha256':sha(o/'compiler.stderr'),'process_exit':proc.returncode,'elapsed_seconds':time.time()-start,'settings':settings,'errors':errors,'warning_count':len(warnings),'warnings':warnings,'contract_inventory':inventory,'compile_readiness_passed':passed,'source_execution':False,'empty_set_refusal_observed':False,'task24_1_accepted':False,'P23_accepted':False,'limits':['Only source compilation. No deployment, transaction, source-mutation campaign or Lean proof.','Runtime ABI and bytecode inventory are compilation outputs, not deployed-bytecode equivalence.','External oracle implementations and concrete admitted pre-state remain to be defined for experiments.','Required empty-set refusal must be observed at the selected guard with preceding conditions stated.'],'next':'AGY can reuse this exact compiler/input/source inventory for P23 experiment preparation after the current author scope; independent review and full P23 entry obligations remain open.'};write(o/'compile-receipt.json',rec);shutil.copy2('/tmp/defiformal-p23-compile-readiness.py',o/'capture-and-compile.py');(o/'README.md').write_text('''# P23 V1 compiler readiness

The captured 43-file Solidity source set was compiled with the official hash-verified Solidity 0.6.11 compiler, optimizer enabled with 100 runs, and Istanbul EVM target. The exact result and contract inventory are in compile-receipt.json. Standard JSON input/output and compiler acquisition identities are preserved.

This is a compiler readiness check. No deployment or redemption transaction was executed; the required empty-set refusal, admitted pre-state, Lean proofs and independent candidate review remain open. Task24.1 and P23 are not accepted by this record.
''');write(o/'manifest.json',{'schema':'defiformal-compile-readiness-manifest/v1','utc':now(),'self_excluding':True,'files':{str(p.relative_to(o)):sha(p) for p in o.iterdir() if p.is_file()},'acceptance':False});print(json.dumps({'compile_passed':passed,'process_exit':proc.returncode,'errors':len(errors),'warnings':len(warnings),'contracts':len(inventory),'source_files':len(sources),'elapsed_seconds':rec['elapsed_seconds'],'acceptance':False}),flush=True)
