from pathlib import Path
import json,hashlib,subprocess,datetime,re
r=Path('/home/charl/defiformal');b=r/'review/semantic-kernel/program-execution-20260908';w=Path('/home/charl/defiformal-wt-p19-certificates-grok-opus-20260909');o=b/'p19-r19-root-precheck';o.mkdir(exist_ok=False);h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();write=lambda p,d:p.write_text(json.dumps(d,indent=2)+'\n');m=json.loads((b/'p19-roundtrip-proof-agy-r19-terminal-manifest.json').read_text());old=json.loads((b/'p19-roundtrip-proof-agy-r18-terminal-manifest.json').read_text());prev={f['path']:f['sha256'] for f in old['files']}
assert not Path('/proc/2059389').exists()
for f in m['files']:assert h(w/f['path'])==f['sha256'],f['path']
changes=[f['path'] for f in m['files'] if prev.get(f['path'])!=f['sha256']];names=[];counts={}
for n in ['CanonicalJson','Correspondence']:
 ns=re.findall(r'^\s*(?:@\[[^\n]*\]\s*)?(?:theorem|lemma)\s+(\S+)',(w/f'lean/DefiKernel/Certificates/{n}.lean').read_text(),re.M);counts[n]=len(ns);names+=ns
assert len(names)==343 and len(set(names))==343
probe=o/'Axioms343.lean';assert not probe.exists();probe.write_text('import DefiKernel.Certificates.Correspondence\n'+''.join('#print axioms DefiKernel.Certificates.'+n+'\n' for n in names));tool=Path('/home/charl/.elan/toolchains/leanprover--lean4---v4.33.0-rc2/bin');cmd=[str(tool/'lake'),'env',str(tool/'lean'),str(probe)];start=datetime.datetime.now(datetime.timezone.utc).isoformat();p=subprocess.run(cmd,cwd=w/'lean',capture_output=True,timeout=120);end=datetime.datetime.now(datetime.timezone.utc).isoformat();(o/'axioms343.stdout').write_bytes(p.stdout);(o/'axioms343.stderr').write_bytes(p.stderr);out=p.stdout.decode();records=re.findall(r"'([^']+)' depends on axioms: \[([^\]]*)\]",out,re.S);zero=re.findall(r"'([^']+)' does not depend on any axioms",out);got=[n for n,_ in records]+zero;want=['DefiKernel.Certificates.'+n for n in names];bad=[{'name':n,'axioms':a} for n,a in records if set(x.strip() for x in a.split(',') if x.strip())-{'propext','Classical.choice','Quot.sound'}]
receipt={'argv':cmd,'cwd':str(w/'lean'),'started_utc':start,'finished_utc':end,'exit':p.returncode,'probe_sha256':h(probe),'stdout_sha256':h(o/'axioms343.stdout'),'stderr_sha256':h(o/'axioms343.stderr'),'lean_sha256':h(tool/'lean'),'lake_sha256':h(tool/'lake'),'source_counts':counts,'axiom_records':len(records),'zero_axiom_records':len(zero),'exact_names_match':set(got)==set(want),'forbidden':bad,'scope':'Exact343 declarations imported from frozen R19 author build; fresh independent reviewer rebuild remains pending.','acceptance':False};write(o/'axioms343-command.json',receipt);assert p.returncode==0 and len(got)==343 and set(got)==set(want) and not bad
for f in m['files']:assert h(w/f['path'])==f['sha256'],f['path']
record={'schema':'defiformal-p19-root-precheck/v1','utc':end,'candidate_archive_sha256':m['sha256'],'changed_or_new_files':changes,'counts':counts,'axiom_check':'p19-r19-root-precheck/axioms343-command.json','findings':['Universal EncodeDecodeRoundtripStatement remains a Prop; lexical/parser success still needs derivation from the admitted domain.','R19 checks foundWhitespace at unterminated-string EOF; root execution controls and independent review required.','TreeJson has only scalar and empty-container parser proofs. The new Expr theorems specialize constructors to fixed children or fixed identifiers; arbitrary recursive inversion remains open.','Verify is reported by all three prefixes; bind raw command evidence and source/probe identities.'],'acceptance':False,'assessment':'PARTIAL_PROOF_WORK_CHANGES_REQUIRED'};write(b/'p19-roundtrip-proof-agy-r19-root-precheck.json',record);print(json.dumps({'counts':counts,'axiom_records':len(records),'zero_axioms':len(zero),'changes':changes,'acceptance':False}))
