from pathlib import Path
import json,subprocess,hashlib,datetime,re,shutil
r=Path('/home/charl/defiformal');b=r/'review/semantic-kernel/program-execution-20260908';o=b/'p24-two-supplier-rounding-diagnostic';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat();write=lambda p,d:p.write_text(json.dumps(d,indent=2)+'\n');repo='/home/charl/.cache/defiformal-program/program-execution-20260908/p24-morpho-blue-source-repository';pin='8e26ca6a8dbc5089edcd67fb576248810fd2870a'
base=b/'p24-source-closure/standard-input.json';assert sha(base)=='6cc2ca50f8ba57480c6b61e945b45111000a8d1b0d8924f417b916b49c3f71b8';d=json.loads(base.read_text());extra=[]
for n in ['src/mocks/ERC20Mock.sol','src/mocks/interfaces/IERC20.sol','src/mocks/OracleMock.sol','src/libraries/periphery/MorphoBalancesLib.sol','src/libraries/periphery/MorphoLib.sol','src/libraries/periphery/MorphoStorageLib.sol']:
 data=subprocess.run(['git','--git-dir='+repo,'show',pin+':'+n],capture_output=True,check=True).stdout;blob=subprocess.run(['git','--git-dir='+repo,'rev-parse',pin+':'+n],capture_output=True,text=True,check=True).stdout.strip();q=o/'upstream'/n;q.parent.mkdir(parents=True,exist_ok=True);q.write_bytes(data);d['sources'][n]={'content':data.decode()};extra.append({'path':n,'git_blob':blob,'sha256':sha(q)})
d['sources']['TwoSupplierProbe.sol']={'content':(o/'TwoSupplierProbe.sol').read_text()};d['settings']['outputSelection']['*']['*'].append('evm.methodIdentifiers');write(o/'standard-input.json',d)
solc=Path('/home/charl/.cache/defiformal-program/program-execution-20260908/p24-compiler/solc-linux-amd64-v0.8.19+commit.7dd6d404');evm=Path('/home/charl/.cache/defiformal-program/program-execution-20260908/p16-tools/evm');assert sha(solc)=='7a5c1d3dc9a8eba62bb2ec37192c9178ae5fe8a54a56e5573fd3c9c17cd9eb48';assert sha(evm)=='d298ce2c811de089d650ed4f9535c0c58efc72e7adee9b61a40b6c10cc26fb5c';commands=[]
def run(label,argv,stdin=None):
 st=now();res=subprocess.run(argv,cwd=o,input=stdin,capture_output=True,timeout=180);(o/(label+'.stdout')).write_bytes(res.stdout);(o/(label+'.stderr')).write_bytes(res.stderr);commands.append({'label':label,'argv':argv,'cwd':str(o),'started_utc':st,'finished_utc':now(),'exit':res.returncode,'stdout_sha256':sha(o/(label+'.stdout')),'stderr_sha256':sha(o/(label+'.stderr'))});write(o/'commands.json',commands);return res
res=run('compile',[str(solc),'--standard-json'],(o/'standard-input.json').read_bytes());assert res.returncode==0;out=json.loads(res.stdout);errors=[x for x in out.get('errors',[]) if x['severity']=='error'];assert not errors,errors
prod=out['contracts']['src/Morpho.sol']['Morpho']['evm'];old=json.loads((b/'p24-compile-readiness/standard-output.json').read_text())['contracts']['src/Morpho.sol']['Morpho']['evm'];assert all(prod[x]['object']==old[x]['object'] for x in ['bytecode','deployedBytecode'])
harness=out['contracts']['TwoSupplierProbe.sol']['TwoSupplierProbe']['evm'];(o/'probe-runtime.hex').write_text(harness['deployedBytecode']['object']);gen=b/'p24-public-call-diagnostic/paris-genesis.json';m=json.loads((b/'p24-public-call-diagnostic/manifest.json').read_text());assert sha(gen)==m['files']['paris-genesis.json'];shutil.copy2(gen,o/'paris-genesis.json');selector=harness['methodIdentifiers']['probe()'];res=run('execute',[str(evm),'run','--prestate',str(o/'paris-genesis.json'),'--codefile',str(o/'probe-runtime.hex'),'--input',selector,'--sender','0x0000000000000000000000000000000000000100','--receiver','0x0000000000000000000000000000000000000200']);assert res.returncode==0,(res.returncode,res.stdout,res.stderr);output=res.stdout.decode().strip();assert re.fullmatch(r'0x[0-9a-fA-F]{896}',output),output;v=[int(output[2+64*i:2+64*(i+1)],16) for i in range(14)];print(v,flush=True)
assert v==[2,1,1,1,0,0,1000000,1000000,1000000,1000000,10,1,0,0]
labels=['market_supply_assets_before','market_supply_assets_after','first_expected_assets_before','second_expected_assets_before','first_expected_assets_after','second_expected_assets_after','first_supply_shares_before','second_supply_shares_before','first_supply_shares_after','second_supply_shares_after','returned_seized_assets','returned_repaid_assets','market_borrow_assets_after','borrower_collateral_after'];rec={'schema':'defiformal-p24-two-supplier-source-diagnostic/v1','utc':now(),'pin':pin,'additional_source_bindings':extra,'observations':dict(zip(labels,v)),'market_loss':v[0]-v[1],'sum_rounded_balance_decreases':v[2]+v[3]-v[4]-v[5],'equal':False,'source_EVM_executions':1,'source_production_bytecodes_match_prior_compile':True,'solc_sha256':sha(solc),'evm_sha256':sha(evm),'compiler_input_sha256':sha(o/'standard-input.json'),'runtime_sha256':sha(o/'probe-runtime.hex'),'genesis_sha256':sha(o/'paris-genesis.json'),'oracle_price_before':10**36,'oracle_price_after':10**10,'irm':'zero address','timestamp':1,'block_number':0,'supplier_addresses':['0x1001','0x1002'],'observed_getter':'Pinned MorphoBalancesLib.expectedSupplyAssets, uses real extSloads and pinned virtual-share rounding','P24_accepted':False,'independent_review_pending':True,'limitation':'Distinct supplier positions funded by one authorized public-call harness; root remains borrower/liquidator. Upstream mocks, same timestamp, zero interest/fees, no supplier withdrawals or sequential redemption result, no allocation policy prescribed.'};write(o/'results.json',rec);print('Source counterexample: market loss1, two rounded getter decreases sum2; no full P24 acceptance',flush=True)
