from pathlib import Path
import json,hashlib,subprocess,datetime,re
r=Path('/home/charl/defiformal');b=r/'review/semantic-kernel/program-execution-20260908';w=Path('/home/charl/defiformal-wt-p19-certificates-grok-opus-20260909');o=b/'p19-r13-root-precheck';o.mkdir(exist_ok=False);h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();write=lambda p,d:p.write_text(json.dumps(d,indent=2)+'\n');m=json.loads((b/'p19-roundtrip-proof-agy-r13-terminal-manifest.json').read_text());old=json.loads((b/'p19-roundtrip-proof-agy-r12-terminal-manifest.json').read_text());prev={f['path']:f['sha256'] for f in old['files']}
assert not Path('/proc/1709772').exists()
for f in m['files']:assert h(w/f['path'])==f['sha256'],f['path']
changes=[f['path'] for f in m['files'] if prev.get(f['path'])!=f['sha256']];names=[];counts={}
for n in ['CanonicalJson','Correspondence']:
 ns=re.findall(r'^theorem\s+(\S+)',(w/f'lean/DefiKernel/Certificates/{n}.lean').read_text(),re.M);counts[n]=len(ns);names+=ns
assert len(names)==200 and len(set(names))==200
probe=o/'Axioms200.lean';probe.write_text('import DefiKernel.Certificates.Correspondence\n'+''.join('#print axioms DefiKernel.Certificates.'+n+'\n' for n in names));tool=Path('/home/charl/.elan/toolchains/leanprover--lean4---v4.33.0-rc2/bin');cmd=[str(tool/'lake'),'env',str(tool/'lean'),str(probe)];start=datetime.datetime.now(datetime.timezone.utc).isoformat();p=subprocess.run(cmd,cwd=w/'lean',capture_output=True,timeout=120);end=datetime.datetime.now(datetime.timezone.utc).isoformat();(o/'axioms200.stdout').write_bytes(p.stdout);(o/'axioms200.stderr').write_bytes(p.stderr);out=p.stdout.decode();records=re.findall(r"'([^']+)' depends on axioms: \[([^\]]*)\]",out,re.S);zero=re.findall(r"'([^']+)' does not depend on any axioms",out);got=[n for n,_ in records]+zero;want=['DefiKernel.Certificates.'+n for n in names];bad=[{'name':n,'axioms':a} for n,a in records if set(x.strip() for x in a.split(',') if x.strip())-{'propext','Classical.choice','Quot.sound'}]
receipt={'argv':cmd,'cwd':str(w/'lean'),'started_utc':start,'finished_utc':end,'exit':p.returncode,'probe_sha256':h(probe),'stdout_sha256':h(o/'axioms200.stdout'),'stderr_sha256':h(o/'axioms200.stderr'),'lean_sha256':h(tool/'lean'),'lake_sha256':h(tool/'lake'),'source_counts':counts,'axiom_records':len(records),'zero_axiom_records':len(zero),'exact_names_match':set(got)==set(want),'forbidden':bad,'scope':'Exact200 declarations imported from frozen R13 author build; fresh independent reviewer rebuild remains pending.','acceptance':False};write(o/'axioms200-command.json',receipt);assert p.returncode==0 and len(got)==200 and set(got)==set(want) and not bad
for f in m['files']:assert h(w/f['path'])==f['sha256'],f['path']
record={'schema':'defiformal-p19-root-precheck/v1','utc':end,'candidate_archive_sha256':m['sha256'],'changed_or_new_files':changes,'counts':counts,'axiom_check':'p19-r13-root-precheck/axioms200-command.json','findings':['Universal EncodeDecodeRoundtripStatement remains a Prop declaration.','decodeEnvelope and execution inverses now use actual decodeDecodedIR but require h_sm: decodeSourceMap(encoded_map)=ok map. Only nil and singleton map inverses are proved, so arbitrary sorted source maps are still open. Derive the inverse from SourceMapSorted without decoder-success premises.','jsonDepthFuel_adequate_of_le64 and jsonMaxArrayLengthFuel_adequate both prove only jsonDepth j <100 from <=64 via omega. Neither states fuel stability, maximum-array correctness or parser agreement. parser_max_depth_bound/parser_max_array_bound merely return their hypotheses.','Actual tokenize_escapeJsonString and parseCanonicalJson_escapeJsonString are general string inverses, distinct from the still missing recursive array/object/whole-byte parser inverse.','libraryRef none now uses object theorem field; actual decodeDecodedIR equivalence and canonical claimed-next-state inverse are progress.','Runner checks the lexical final component before resolution. Reported prevention of all parent symlink traversal is not established by checking is_symlink on the resolved path. Fresh child under a parent symlink may be legitimate; no new blanket parent prohibition is required for evidence preservation.','Relative-symlink regression constructs a relative target including temporary parent name again, producing a dangling link instead of testing a live relative link. Add a live relative-link refusal test.','Full54/99/16 campaign deferred; reported7 runner checks and21 Tests require actual scoped evidence, not aggregate proof credit.'],'acceptance':False,'assessment':'PARTIAL_PROOF_WORK_CHANGES_REQUIRED'};write(b/'p19-roundtrip-proof-agy-r13-root-precheck.json',record);print(json.dumps({'counts':counts,'axiom_records':len(records),'zero_axioms':len(zero),'changes':changes,'acceptance':False}))
