#!/usr/bin/env python3
"""Bind original thirteen executions to unchanged relevant inputs of the revised candidate."""
import hashlib,json,subprocess,datetime,sys
from pathlib import Path
R=Path(__file__).resolve().parents[4]; B=R/'review/semantic-kernel/sprint9'; O=Path(__file__).parent
OLD='c880acf62944746ff9a376afc0c0050702f037f7'; NEW=sys.argv[1]
def sha(b):return hashlib.sha256(b).hexdigest()
def read(p):return json.loads(p.read_text())
def data(rev,p):return subprocess.check_output(['git','show',f'{rev}:{p}'],cwd=R)
def blob(rev,p):return subprocess.check_output(['git','rev-parse',f'{rev}:{p}'],cwd=R,text=True).strip()
base=read(B/'regressions/source-binding.json'); runs=read(B/'regressions/regression-runs.json'); assert len(base)==163 and runs['source_revision']==OLD
bindings={}
for p,b in base.items():
 old=data(OLD,p);new=data(NEW,p)
 assert sha(old)==b['sha256'] and blob(OLD,p)==b['git_blob']
 assert (R/p).read_bytes()==new,p
 bindings[p]={'original':{'candidate':OLD,'sha256':sha(old),'git_blob':blob(OLD,p),'bytes':len(old)},'revised':{'candidate':NEW,'sha256':sha(new),'git_blob':blob(NEW,p),'bytes':len(new)},'equal':old==new}
common={'lean/lean-toolchain','lean/lakefile.toml','lean/lake-manifest.json'}
suites=[]
for run in runs['runs']:
 label=run['label'];command=run['command']; paths={command[1]};evidence=[]
 if label.endswith('-mutations'):
  manifest=B/'regressions'/label/'source-manifest.json';m=read(manifest);assert m['git_head']==OLD and m['input_sources_unchanged']
  paths.update(m['sources']);paths.add(command[command.index('--spec')+1]);paths.update(common)
  for p,h in m['sources'].items():assert base[p]['sha256']==h
  assert sha(data(OLD,command[1]))==m['script_sha256']
  rationale='Actual runner source-manifest transitive Lean closure, runner, specification and pinned Lake configuration.'
  evidence.append(str(manifest.relative_to(R)))
 elif label.endswith('-runner-controls'):
  manifest=B/'regressions'/label/'summary.json';m=read(manifest);assert m['git_head']==OLD
  for k in ['runner','harness']:
   p=str(Path(m[k+'_source']).relative_to(R));paths.add(p);assert sha(data(OLD,p))==m[k+'_sha256']
  paths.update(common);rationale='Runner and fixture-generating harness, plus the three copied Lake configuration files; Lean fixture sources are generated by that unchanged harness in isolated repositories.'
  evidence.append(str(manifest.relative_to(R)))
 elif label=='typing-controls':
  manifest=B/'regressions/typing-controls/results.json';m=read(manifest);paths.update(m['sources']);paths.update(common)
  for p,h in m['sources'].items():assert base[p]['sha256']==h
  rationale='Recorded Types/Expr source inputs, typing driver and pinned Lake configuration. No root or Atomic Audit import.';evidence.append(str(manifest.relative_to(R)))
 elif label=='axiom-controls':
  paths.update(common);paths.add('lean/DefiKernel/AxiomAudit.lean')
  rationale='Driver copies only AxiomAudit into a synthetic fixture project; generated probes and imported dependency fixtures are defined by this unchanged driver. Lake configuration included conservatively.'
 else:
  paths.add('scripts/corpus_normalize.py')
  paths.update(p for p in base if p.startswith('corpus50/lanes/') or p.startswith('corpus/normalized/inputs/'))
  paths.update({'corpus/normalized/corpus.schema.json','docs/research/2026-09-06-defi-source-plan.md'})
  rationale='CLI/test driver plus all copied lane and normalized-input files, schema and research source plan; synthetic annotations are generated by the unchanged test driver.'
 assert all(p in bindings and bindings[p]['equal'] for p in paths),label
 suites.append({'label':label,'actual_execution_candidate':OLD,'revised_candidate':NEW,'original_command':command,'original_run':run,'closure_basis':rationale,'evidence_inputs':{p:sha((R/p).read_bytes()) for p in evidence},'source_closure':{p:bindings[p] for p in sorted(paths)},'relevant_input_count':len(paths),'relevant_inputs_equal':True,'rerun_required':False})
assert len(suites)==13
changed=[p for p,b in bindings.items() if not b['equal']]
assert changed and set(changed) <= {'lean/DefiKernel/Metatheory/Examples.lean','lean/DefiKernel/Metatheory/Tests.lean','lean/DefiKernel/Metatheory/SequentialGroups.lean'}
assert all(not(set(changed)&set(s['source_closure'])) for s in suites)
tools={}
for key in ['python','lean','lake','git']:
 p=Path(runs['tools'][key+'_executable']);h=sha(p.read_bytes());assert h==runs['tools'][key+'_executable_sha256'];tools[key]={'path':str(p),'sha256':h,'matches_original_execution':True}
report={'schema_version':1,'kind':'legacy-suite-relevant-dependency-equivalence','status':'PASS','captured_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'actual_execution_candidate':OLD,'revised_candidate':NEW,'original_suite_count':13,'baseline_input_count':len(base),'equal_baseline_inputs':len(base)-len(changed),'changed_baseline_inputs':changed,'all_relevant_inputs_equal':True,'no_rerun_required':True,'scope':'Author dependency-equivalence analysis, not an independent review of the regression harness. Thirteen actual executions retain their original HEAD; no claim that all baseline inputs are unchanged.','baseline_bindings':bindings,'suites':suites,'tools':tools,'input_artifacts':{str(p.relative_to(R)):sha(p.read_bytes()) for p in [B/'regressions/regression-runs.json',B/'regressions/source-binding.json',B/'regressions/source-binding-after.json',B/'regressions/verified-outcomes.json']},'checker_sha256':sha(Path(__file__).read_bytes())}
(O/'legacy-dependency-equivalence.json').write_text(json.dumps(report,indent=2)+'\n')
(O/'legacy-dependency-equivalence.md').write_text(f"""# Legacy regression dependency equivalence

PASS: thirteen suites retain actual execution candidate `{OLD}`. Their relevant
source closures and tool binaries are byte-identical at revised candidate `{NEW}`.
This is a source-equivalence analysis, not thirteen new executions.

Of {len(base)} baseline inputs, {len(base)-len(changed)} are unchanged. The changed
files are {', '.join(changed)}. None belongs to any retained suite's execution
closure. The changed Metatheory runtime fixtures retain their accepted Sprint 9 production
mutation evidence and receive fresh integration execution, recorded separately.

The JSON binds both Git objects and SHA-256 values for every baseline input and
per-suite closure. Mutation closures come from actual manifests; synthetic
runner, axiom, typing and corpus closures come from the recorded inputs and
inspected driver file reads. This author analysis is subject to native review.
""")
print('PASS',[(s['label'],s['relevant_input_count']) for s in suites]);print('report_sha256',sha((O/'legacy-dependency-equivalence.json').read_bytes()))
