#!/usr/bin/env python3
import json
from pathlib import Path
b=Path(__file__).resolve().parent
fixtures=[
('F01','Empty participant universe','B empty, empty roster/tree/schedule; world contains a USD sentinel11 and nonempty capability store with explicit nextId/revocation data.','Admission succeeds; full world/store unchanged, no locals/attempts. Nonempty B with empty tree is structurally rejected after successful base checks.','actual execution/structural'),
('F02','Stable identities and empty nodes','B ordered[b0,b1,b2], all branches empty; compare fork(fork(b0,b1),b2), fork(b0,fork(b1,b2)), and empty-node wrappers with empty schedule.','Each identity occurs once; same full empty-local observation and full entry world. Reordered leaves also preserve identities for a fixed named schedule in F05.','actual execution'),
('F03','Duplicate and missing identities','Tree leaves[b0,b0,b2], then leaves[b0,b2], valid configuration and complete base schedule.','First mismatch in roster order is b0 expected1 observed2, then b1 expected1 observed0. Neither creates a machine or attempt; entry world/store retained.','structural refusal'),
('F04','Deterministic base precedence','Combine malformed tree with invalid catalog; then valid catalog plus malformed full branch suffix; then structurally valid branches with count mismatch.','Actual base configuration, then roster-first structural LocalFailure, then roster-first schedule mismatch wins before tree error. A financially unreachable malformed suffix remains checked.','admission diagnostic'),
('F05','Disjoint three streams all90 schedules','Common finite universe: home/away, USD/EUR, source principals v0/v1/v2, recipients r0/r1/r2 and sentinel. Initial home/USD(v0,v1,v2)=(7,5,4), recipients0; away/EUR sentinel11, other cells0. Full nonempty store has literal valid grants. Branch i uses distinct component ci, producer operation100+100*i and consumer101+100*i. The zero-effect producer at index0 exports its own vi balance under qualified(ci,budget); index1 transfers that own-history amount vi→ri and exports no outputs. Boundaries authenticate vi at each own position; literal grant IDs1–6 authorize the corresponding source/target/domain/asset operations.','All90 schedules with multiplicities(2,2,2) succeed. Final sources(0,0,0), recipients(7,5,4), sentinel11, store exact. Every local consumed2/nextIndex2 with literal producer/consumer receipts and histories containing exactly the producer snapshot7/5/4 respectively (consumer exports none). For each schedule construct full raw event/attempt worlds chronologically from the independent action table; compare multiple groupings and isolated reference.','actual financial/generic theorem instance'),
('F06','Compatible financial refusal all90 schedules','F05 except b1 consumer requests literal6 from v1=5; no custom financial guard masks the actual typed insufficient-funds check.','All90 schedules retain v1=5,r1=0; b0/b2 transfer7/4. b1 consumed2,nextIndex1, exact located .kernel .insufficientFunds at index1, producer history retained. Final canonical observations agree although raw worlds/attempt order differ.','actual financial refusal'),
('F07','Peer continuation and failed suffix','F06 raw prefix schedule[b1,b1,b1,b0,b0,b2,b2,b1], deliberately over-complete.','b1 consumed4,nextIndex1 and first index1 refusal retained; two skipped tokens append no attempts. Peers complete, six actual attempts total, final balances as F06. No ancestor cancellation.','actual prefix/overscheduling'),
('F08','Absolute boundary and branch selection','Funded two-step branch with index0 producer and index1 consumer; boundary principal authorized only at its own correct index, with distinct now/environment witnesses. Include an unselected peer with a different principal.','Correct second leaf uses own nextIndex1 and own history; constant boundary0 changes authority or receipt. Branch selection is by consumed; arbitrary-entry companion distinguishes consumed from nextIndex without asserting reachability.','actual boundary plus labeled arbitrary-entry'),
('F09','Tree path re-encoding and errors','Encode stable schedule[b0,b1,b0,b2,b1,b2] for both three-leaf groupings; add paths ending at a fork/empty, beyond a leaf, and an invalid suffix after two valid paths.','Decoded names match exactly after re-encoding, not after copying paths. First invalid path reports its full path and token index2 in appended suffix case, before financial/admission work.','actual route decoding'),
('F10','Raw malformed fallback','Use a raw duplicate local tree with distinct populated b0 locals and a missing b1; bypass admitted runner explicitly.','b0 selects only the first depth-first match; absent b1 leaves full machine unchanged. Admitted runner still rejects this shape. This does not instantiate well-formed-tree simulation.','synthetic/raw totality'),
('F11','Populated entry continuation','Construct related populated trees/flat machine with p0 producer history/index1/consumed1, p1 already failed and consumed1, nonempty exact attempts/store, and p2 untouched. Continue same suffix and compare two chunks/three tree shapes.','No history, world, failure, index or store reset. Exact full representation equality holds on arbitrary related entries; separate reachable construction is supplied where claimed.','arbitrary-entry algebra/actual companion'),
('F12','Shared qualified key own-history separation','Shared cell q7: b0 first reads/exports q7; b1 first transfers2 q→sink and exports q5 under the same qualified key; then b0 transfers its stored7 from v0=7, b1 its stored5 from v1=5. Schedule[b0,b1,b0,b1], b2 empty.','Final q5,sink2,v0=v1=0,r0=7,r1=5. Separate stream snapshots remain7/5. Both tree shapes agree fully for this fixed schedule; disjoint admission rejects shared read/write footprints. No cross-stream history support is added.','actual overlap/history'),
('F13','All compatibility directions','Use separate valid fixtures for write/write conflict, i-write/j-read-only conflict and j-write/i-read-only conflict, plus allowed shared read-only overlap; include output-only read dependency.','Canonical roster pair, existing ConflictKind and first offending exact cell are reported. Read-only sharing succeeds. Output-snapshot dependencies participate in analyzed compatibility.','static compatibility/actual companion'),
('F14','Overlapping fixed-schedule equality','Two authorized withdrawals7/6 from shared home/USD vault10 into distinct recipients; b2 empty. Fix[b0,b1], through both the stable-name runner and its correctly encoded path wrapper.','Every valid grouping yields vault3,recipient0=7,recipient1=0 and b1 exact insufficientFunds refusal; compatibility fails but ordinary shared admission/execution succeeds.','actual financial'),
('F15','Schedule-independence counterexample','F14 compare[b0,b1] with[b1,b0].','Vault3 versus4; distinct recipient and refusal identity. Both schedules complete and valid; pairwise compatibility premise is false. This refutes unrestricted schedule independence only.','actual negative theorem instance'),
('F16','Global edge omission is material','Global binding edges A=B and B=C with initialized balances5/5/5. Only C transfers1 to sink0 in a valid authorized branch; compare tree cuts retaining only A=B versus the actual full set.','Actual result A5/B5/C4/sink1: full binding query false, truncated A=B query true. Compatibility/admission does not supply binding preservation; the needed local obligation fails.','actual financial/global binding negative'),
('F17','Initialized M2 contract transport','Three streams each perform an authorized paired debit1 from A and B to sink, start5/5/0, same global A=B edge and total region A+B+sink=10. Use actual accepted M2 semantics after dependency refresh.','Each prefix gives(4,4,2),(3,3,4),(2,2,6) in token-count order; all groupings preserve initialized equality and total through M3 local/cross obligations. Overlap precludes disjoint-theorem use. Initial4/5/0 companion remains unequal.','actual financial/conditional invariant'),
('F18','Causal monitor transport and order limit','Use accepted M3 funded producer6/consumer6 plus peer deposits1/2, initial vault10/donors2,3/recipient0. Fixed update and initial monitor are identical across trees. Add a monitor recording selected identities and a skipped-token companion.','For each of12 complete schedules, fixed-schedule trees match full base/monitor states and actual appended-attempt inputs; reserve≥4 and final vault7. Order-list monitors differ across distinct schedules, even for disjoint identity actions.','actual causal/generic transport instance'),
('F19','Full versus canonical synthetic observations','Arbitrary labeled machine pairs differ in exactly one field: world cell, store/nextId/revocation, consumed, nextIndex, failure/index, output, event receipt/request, raw event world, global attempt/outcome.','Full comparison rejects every listed difference. Canonical comparison rejects all retained-field differences but accepts differences only in raw intermediate worlds/global attempt order. No pair is labeled reachable or a financial execution merely because constructible.','synthetic comparator'),
('F20','Merge retains base and unique owner','Run disjoint empty/identity/transfer leaves from same base with nonzero unowned sentinel11 and distinct owner balances. Include empty subtree at each side and a refused owner retaining a successful prefix.','Merge chooses each owner final balance exactly once and initial sentinel11; never doubles to22. Full capabilities unchanged; empty subtree units and outside-write frame hold.','actual reference merge')]
mutations=[
('M01','Execution.route','Always route into the right child instead of testing left membership','F05','left-participant expected transfers/consumed','right-only path control'),
('M02','Execution.accept','Publish pre.world instead of actual successful post.world','F05','literal recipient balances','zero-effect producer control'),
('M03','Execution.startTree','Replace initial capability store with empty store','F01','complete retained store/nextId/revocation','empty-store start control'),
('M04','Execution.route return','Reset an unselected sibling local subtree while rebuilding the selected path','F05','peer histories/events/consumed','single-leaf control'),
('M05','Execution.leaf boundary','Use boundaries b 0 instead of boundaries b nextIndex','F08','index1 authority/receipt','index0 control'),
('M06','Execution.leaf history','Use roster-concatenated output histories instead of selected own history','F12','b1 own snapshot5 and successful transfer5','single-stream control'),
('M07','Execution.skip failed','Clear existing failure while incrementing consumed','F07','exact first retained failure','active success control'),
('M08','Execution.refuse','Leave consumed unchanged instead of incrementing','F07','b1 consumed4 after retained failure/skips','success consumed control'),
('M09','Execution.route fork','Skip target if any sibling local has a failure','F07','peer funded transfers after b1 refusal','no-refusal fixture'),
('M10','Shape.checkTree','Return ok without checking leaf multiplicities','F03','duplicate/missing refusal constructors','valid shape control'),
('M11','Paths.resolve','Exchange left/right path constructors','F09','decoded stable identity sequence','single-leaf empty-path control'),
('M12','Paths.decode','Reverse decoded token list on successful resolution','F14','7-before6 expected balances/refusal via path wrapper','palindromic schedule control'),
('M13','DisjointRuntime.merge','Add child complete balances instead of selecting owner/base','F20','unowned sentinel11 rather than22','all-zero disjoint control'),
('M14','DisjointRuntime.merge','Choose left result on every cell regardless of footprint ownership','F05','right-owner final recipient balance','left-owned-cell control'),
('M15','DisjointRuntime.checkPairwise','Pass footprints with reads=[] to existing checkCompatibility','F13','both asymmetric read/write and output dependency refusals','write/write rejection and shared-read success controls'),
('M16','Observation.canonical','Replace evaluated-receipt equality conjunct with true','F19','receipt-only canonical pair must be false','identical pair control'),
('M17','Observation.full','Replace global-attempt equality conjunct with true','F19','attempt-only full pair must be false','identical pair control'),
('M18','MonitorRuntime.advance','Pass none instead of actual newly appended attempt to callback','F18','producer establishes actual Ready6 fact','true-skip supplies none control')]
common={'status':'provisional_author_contract_not_implemented','accepted':False,'oracle_policy':'All literal expected states/receipts/requests/outputs/stores/failures are independently constructed from typed definitions and action tables; no candidate runner constructs its expected output. Exact API field names and concrete grant/template constructors must be refreshed against accepted M2/M3 before official freeze.','fixture_universe':'Finite two domains/two assets and distinct source/recipient/administrator principals; full nonempty capability store contains explicit allocated IDs, nextId and active/inactive cases. Where a fixture overrides this universe, the override is explicit.','fixtures':[dict(zip(['id','name','inputs','expected','classification'],r)) for r in fixtures]}
(b/'fixtures.json').write_text(json.dumps(common,indent=2)+'\n')
(b/'planned-mutations.json').write_text(json.dumps({'status':'planned_only_no_mutations_run','mutations':[dict(zip(['id','new_source_site','replacement','fixture','intended_false_oracle','protected_positive'],r)) for r in mutations],'gate':'Each mutation must compile actual new runtime closure and trigger its intended false oracle; compiler/type errors/timeouts/empty output/cancellation are blocked, never detection. Exact matched source replacement and literal checkID binding required before execution. Historical sources remain byte-identical.'},indent=2)+'\n')
print(len(fixtures),'fixtures',len(mutations),'planned mutations')
