#!/usr/bin/env python3
from pathlib import Path
import json
b=Path(__file__).resolve().parent;r=b.parents[4];change=r/'openspec/changes/operational-tree-regrouping'
data=[
('operational-tree-routing','Preserves stable participant identities while routing actual shared-state execution through a finite tree.',[
('R01 Stable roster and shape','The system SHALL use the same fixed complete/nodup M3 roster and SHALL require exactly one leaf per participant, allowing explicit empty nodes without changing identity or creating a private world.', ['2.1'], [('Empty universe','the participant universe and schedule are empty','the empty tree preserves the entire entry world/store and creates no attempts',['F01']),('Regrouped identities','a complete three-leaf tree is reassociated or wrapped with empty nodes','every original identity remains present exactly once',['F02'])]),
('R02 Ordered admission and refusal identity','The admitted runner SHALL first return the exact actual M3 admission error when present, then the roster-first tree multiplicity error; every admission refusal SHALL retain full entry world/store and create no machine or attempts.', ['2.2'], [('Duplicate and missing leaf','base admission succeeds for duplicate/missing trees','the exact participant/expected1/observed count follows roster order',['F03']),('Base precedence','a malformed tree coexists with configuration, full-suffix structural or count error','the actual base error wins with its complete payload',['F04']),('Unreachable malformed suffix','a financially failing branch has a structurally invalid later invocation','full base analysis still refuses before tree checking',['F04'])]),
('R03 Actual recursive routing','The dispatcher SHALL independently descend the tree and execute the selected invocation at most once using actual executeStep, consumed for selection and own nextIndex/history for preparation; it SHALL preserve all unselected locals and apply exact success/refusal/skip updates.', ['2.3','2.4'], [('Disjoint funded leaves','all six invocations are selected in any of the90 complete schedules','literal expected full machines and unchanged peer locals are obtained',['F05']),('Refusal does not cancel peers','a branch has refused and further tokens select it and peers','only its consumed counter advances on skips while peers execute and first refusal remains',['F07']),('Own absolute boundary','the selected successful position is1 with distinct boundary identity/time','index1 boundary and own history are used exactly',['F08'])]),
('R04 Path schedules preserve stable names','The system SHALL decode paths in order with exact first invalid token/path, validate all submitted paths before runTreePaths admission, and prove re-encoding across well-formed trees preserves the decoded name schedule and append offsets.', ['2.5'], [('Re-encode after regrouping','the same stable schedule is encoded for two valid shapes','each decodes to the identical token list, while copying old paths is not presumed equivalent',['F09']),('Invalid full suffix','an invalid path follows two valid paths, even after an eventual financial failure','the wrapper returns invalidPath at token2 before financial execution',['F09'])])]),
('tree-flat-regrouping-correspondence','Relates the independently executed participant tree to the flat machine without erasing fixed-schedule execution data.',[
('R05 Exact full observation','The full observation and executable comparator SHALL retain full ledger/store, all local consumed/nextIndex/history/event/receipt/failure fields and every raw global attempt/outcome; comparator truth SHALL be equivalent to the complete representation relation.', ['3.1','3.2'], [('Every stored field matters','a synthetic pair differs in one retained full field','full comparison is false without claiming the pair is reachable',['F19']),('Literal execution observation','the funded execution is compared with its independent expected full machine','all raw event/attempt worlds and capability records match',['F05'])]),
('R06 Noncircular simulation','The development SHALL prove initialization, shape preservation, one-token simulation in both directions and arbitrary-entry continuation from actual execution equations; flattening SHALL be a representation conversion rather than the production dispatch implementation.', ['3.2','3.3'], [('Populated entry','tree and flat entries are fully related with histories/failures already present','continuations remain fully related with no resets',['F11']),('Actual refusal and skip','a related selected local refuses or is already failed/exhausted','the same actual error/none append behavior and counters are preserved',['F06','F07']),('Malformed raw fallback excluded','a raw tree has duplicate or missing identity','documented total fallback is tested but no well-formed simulation theorem is claimed',['F10'])]),
('R07 Fixed schedule behavioral regrouping','For identical static parameters, valid trees, related starts and the same decoded schedule, the system SHALL prove equality of full observations, including association and empty-node units, without requiring disjoint writes or changing token order.', ['3.4'], [('Overlapping execution','withdrawals7/6 compete for10 with fixed order b0,b1 across tree shapes','both give vault3 and the same peer refusal/history/attempt data',['F14']),('Group association and units','the funded valid tree is reassociated or gains empty internal nodes','full fixed-schedule results are unchanged',['F02','F05'])]),
('R08 Result and initialization correspondence','The development SHALL map exact admitted/refused result constructors and original stable schedules to M3 and SHALL state arbitrary-entry representation premises separately from genesis reachability; accepted S9 sequential administration SHALL retain its separate scope.', ['3.5'], [('Refused result projection','base admission fails before execution','projection retains the exact M3 reason, submitted schedule and entry world',['F04']),('No implicit restart','a populated entry is continued across chunks and tree boundaries','complete existing cursor data and first failures survive',['F11'])])]),
('compatible-tree-disjoint-recovery','Establishes schedule independence only for analyzed compatible branches under an explicitly reduced observation.',[
('R09 Actual pairwise compatibility','The disjoint reference SHALL require actual full-branch analyzed footprints and check roster-ordered pairs with exact existing conflict kind/cell. The development SHALL prove compatible disjoint-subtree footprint unions, including output dependencies and both write/read directions.', ['4.1'], [('All conflicts material','valid branches have write/write or either write/read conflict including an output-only dependency','the exact canonical pair/kind/cell is refused',['F13']),('Shared reads allowed','two branches read the same cell but neither writes it','compatibility succeeds and no false separation requirement is introduced',['F13'])]),
('R10 Independent isolated tree reference','The reference executor SHALL run each actual branch from the same initial world with its own history, recursively merge unique write owners and retain initial unowned cells/capabilities. It SHALL be independent of the shared/flat dispatcher and prove grouping correspondence.', ['4.2','4.3'], [('Unique owner merge','disjoint branches affect separate cells while an unowned sentinel starts11','owner results appear once and sentinel remains11, never22',['F20']),('Refused owner prefix','one isolated branch succeeds then refuses','its successful prefix and exact local failure survive merge',['F06','F20']),('Empty subtree unit','an empty subtree is merged on either side','the reference state/local observation is unchanged',['F20'])]),
('R11 Generic compatible recovery','For actual admission, valid trees, identical genesis world/store, pairwise analyzed compatibility and any complete schedule, the development SHALL prove canonical equality with independently executed isolated branches using actual prefix dependency/refusal simulation; it SHALL cover financial refusals and not assume the desired run equality.', ['4.4','4.5'], [('All successful orders','the three disjoint two-step branches run in any of90 complete schedules','the generic theorem and independently expected canonical balances/receipts agree',['F05']),('All refusal orders','the middle branch requests6 from5 in any complete schedule','the exact retained refusal and peers match the independent isolated reference',['F06'])]),
('R12 Canonical equality and excluded observations','Canonical equality SHALL retain final full world/store, every local consumed and BranchObservation field; it SHALL omit only tree/path shape, complete schedule, raw intermediate worlds and global attempts. Different-schedule equality SHALL require compatibility and SHALL not imply full-trace or monitor equality.', ['4.5','4.6'], [('Projection distinguishes its own fields','synthetic pairs differ in receipt, failure, consumed or output versus only raw worlds/attempts','canonical comparison rejects the former and accepts the latter exactly',['F19']),('Unrestricted law is false','the two competing withdrawals run in opposite complete orders','vault3 versus4 and different refusals refute independence; the compatibility premise is false',['F15'])])]),
('tree-initialized-contract-transport','Transports established initialized invariants and causal prefix facts through actual tree representation correspondence.',[
('R13 Initialized invariant transport','The development SHALL transport actual M3 reachable-prefix/local-order and finite interference conclusions through representation, retaining explicit entry initialization and actual local/peer obligations rather than deriving them from tree admission.', ['5.1'], [('Initialized equality','three paired-debit streams start A=B=5 with sink0 and the local obligations hold','each actual prefix retains equality and total10 across groupings',['F17']),('Uninitialized companion','the same operations start A4/B5','the desired equality is not inferred merely from admission',['F17'])]),
('R14 Fixed global interface bindings','The M2 binding/region instantiation SHALL retain the complete unchanged globally named edge set and actual accepted accounting/support premises across tree cuts; disjointness alone SHALL NOT imply arbitrary binding preservation.', ['5.2'], [('Cross-cut edge retained','global edges A=B and B=C are initialized at5/5/5 before C pays1','full binding is false despite a truncated A=B check being true',['F16']),('Local obligations discharged','paired debits update A and B together under accepted M2 effects','the full global equality and total are proven from actual local effects',['F17']),('Pending API is explicit','M2/M3 are not yet accepted and delivered','no invented declaration or premise is reported as an existing proof',['F17'])]),
('R15 Actual causal monitor transport','The monitor wrapper SHALL use one actual tree step and the exact newly appended attempt/none, preserve base erasure, and prove fixed-prefix monitor equality for identical update/initial monitor/static parameters and related entry machines.', ['5.3'], [('Funded producer provenance','the actual producer6 succeeds in the accepted M3 funded fixture','both trees receive the same actual attempt and establish the same monitor fact',['F18']),('Skip has no fresh attempt','a selected failed/exhausted token appends nothing','the callback receives none rather than the prior attempt',['F18'])]),
('R16 Causal and schedule limits','The development SHALL distinguish fixed-parameter common-prefix causality from hidden callback constants and SHALL not claim equal monitor state across distinct schedules without a separate observer-invariance premise.', ['5.4'], [('Order-sensitive monitor','a callback records selected identities for disjoint identity actions in different orders','final base canonical observation agrees but monitor lists differ',['F18']),('Changed callback or initial monitor','a different callback or externally prescient initial value is supplied','the fixed-parameter transport/common-prefix theorem is not applied',['F18'])])]),
('tree-regression-evidence','Requires independently expected observations and reproducible source-bound proof, execution and review evidence.',[
('R17 Independent finite fixture coverage','The implementation SHALL cover all twenty explicit fixture contracts, enumerate90 nonduplicate complete(2,2,2) schedules and12 funded causal schedules, and construct expected observations independently of candidate runners, labeling synthetic/arbitrary-entry versus actual financial cases.', ['6.1','6.2'], [('Nondegenerate oracles','the funded/disjoint and shared-history cases are exercised','literal balances, histories, receipts, stores and exact failures detect wrong execution, not only agreement between implementations',['F05','F06','F12']),('Synthetic scope','a comparator-only pair is unreachable or arbitrary','it is labeled synthetic and earns no financial execution or initialization credit',['F19'])]),
('R18 Real mutation and defensive runner evidence','Each of eighteen planned mutations SHALL compile the actual runtime closure and falsify its intended semantic oracle while protected positives pass. All final accepted predecessor CLI controls SHALL be literally mapped and run; runner/harness timeouts SHALL be600s/1500s with measured duration and preserved failures.', ['6.3','6.4','6.5'], [('Runtime mutant discrimination','a merge mutation doubles the unowned sentinel or routing corrupts a peer','the intended independent false comparison is recorded on compiled runtime source',['F05','F20']),('Blocked execution gets no credit','compilation, parsing, timeout or an empty check list prevents semantic execution','the run is classified blocked and retained without detection credit',['F19']),('Inherited controls refreshed','accepted M3 driver/control bytes become available','every old namespace/root/proof regex/error/fixture/command receives an exact successor mapping before official freeze',['F19'])]),
('R19 Proof and integration inventory','The result SHALL bind actual imported full theorem statements/axioms, explicit/generated/private classifications, source/tool hashes and nonempty runtime counts; required Lean/regression checks SHALL be fresh or retained only with exact dependency equivalence and original run identity.', ['7.1','7.2','7.3'], [('Generic versus bounded evidence','all90 financial schedules pass','the report still identifies the separate arbitrary-schedule theorem, its premises and actual axioms',['F05','F06']),('Source binding','a baseline is retained across metadata-only change','actual executed revision and byte-equivalent dependencies remain explicit',['F01'])]),
('R20 Accepted dependency and independent gates','Official freeze SHALL require accepted/delivered S10 and M3 source/API/baseline/control refresh, strict validation and same-candidate nonauthor GPT-6/native Fable5.1 medium verdicts. Implementation evidence SHALL receive native Grok/Fable review; unavailable or non-substantive responses SHALL remain open.', ['1.1','1.2','1.3','1.4','7.4','7.5'], [('Provisional author draft','this draft precedes accepted M2/M3 delivery','all tasks remain unchecked and no implementation or independent acceptance is claimed',['F01']),('Missing substantive verdict','a provider returns no verdict, timeout or tool-only text','the gate remains open and original response/model identity is retained',['F01'])])])]
scenarios=[];requirements=[];seq=0
for cap,purpose,reqs in data:
 p=change/'specs'/cap/'spec.md';p.parent.mkdir(parents=True,exist_ok=True);lines=['## Purpose','',purpose,'','## ADDED Requirements','']
 for title,contract,tasks,scs in reqs:
  lines+=['### Requirement: '+title,contract,''];requirements.append({'id':title.split()[0],'title':title,'capability':cap,'tasks':tasks})
  for name,when,then,fs in scs:
   seq+=1;sid=f'S{seq:02}';lines+=['#### Scenario: '+sid+' '+name,'- **WHEN** '+when,'- **THEN** '+then,''];scenarios.append({'id':sid,'title':name,'requirement':title.split()[0],'capability':cap,'fixtures':fs,'tasks':tasks,'status':'planned_unexecuted'})
 p.write_text('\n'.join(lines))
(b/'scenario-map.json').write_text(json.dumps({'status':'author_consistency_only','accepted':False,'requirements':requirements,'scenarios':scenarios},indent=2)+'\n')
print(len(data),'capabilities',len(requirements),'requirements',len(scenarios),'scenarios')
