import DefiKernel.Arithmetic.Operations
#print axioms DefiKernel.Arithmetic.Word.ext
#print axioms DefiKernel.Arithmetic.Word.checked_ok_iff
#print axioms DefiKernel.Arithmetic.Word.checked_error_iff
#print axioms DefiKernel.Arithmetic.Word.checked_exists_iff
#print axioms DefiKernel.Arithmetic.ofNat_ok_iff
#print axioms DefiKernel.Arithmetic.ofNat_error_iff
#print axioms DefiKernel.Arithmetic.ofNat_value
#print axioms DefiKernel.Arithmetic.Word.width_zero
#print axioms DefiKernel.Arithmetic.Operations.add_ok_iff
#print axioms DefiKernel.Arithmetic.Operations.add_error_iff
#print axioms DefiKernel.Arithmetic.Operations.mul_ok_iff
#print axioms DefiKernel.Arithmetic.Operations.mul_error_iff
#print axioms DefiKernel.Arithmetic.Operations.sub_difference_bound
#print axioms DefiKernel.Arithmetic.Operations.sub_checked_ne_error
#print axioms DefiKernel.Arithmetic.Operations.sub_ok_iff
#print axioms DefiKernel.Arithmetic.Operations.sub_error_iff
#print axioms DefiKernel.Arithmetic.Operations.add_mono
#print axioms DefiKernel.Arithmetic.Operations.mul_mono
#print axioms DefiKernel.Arithmetic.Operations.sub_mono
#print axioms DefiKernel.Arithmetic.Operations.sub_antitone
#print axioms DefiKernel.Arithmetic.Operations.add_comm
#print axioms DefiKernel.Arithmetic.Operations.mul_comm
#print axioms DefiKernel.Arithmetic.Operations.add_zero
#print axioms DefiKernel.Arithmetic.Operations.sub_zero
#print axioms DefiKernel.Arithmetic.Operations.sub_self
#print axioms DefiKernel.Arithmetic.Operations.mul_zero
#print axioms DefiKernel.Arithmetic.Operations.mul_one
#print axioms DefiKernel.Arithmetic.Operations.add_mono_right
#print axioms DefiKernel.Arithmetic.Operations.mul_mono_right
