from pathlib import Path
import datetime,hashlib,json,posixpath,re,urllib.request,shutil
B=Path('/home/charl/defiformal/review/semantic-kernel/program-execution-20260908');D=B/'p28-depeg-dependency-preparation';O=B/'p28-depeg-license-source';O.mkdir(exist_ok=False);now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat();sha=lambda b:hashlib.sha256(b).hexdigest()
def put(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
m=json.loads((D/'identity.json').read_text());pin=next(p for p in m['pins'] if p['alias']=='@etherisc/gif-contracts');path='contracts/modules/LicenseController.sol';name=pin['alias']+'/'+path;t=json.loads((D/'discovery'/pin['directory']/'tree.json').read_text());blob=next(r['sha'] for r in t['tree'] if r['path']==path);url='https://raw.githubusercontent.com/'+pin['repository']+'/'+pin['commit']+'/'+path;start=now()
with urllib.request.urlopen(urllib.request.Request(url,headers={'User-Agent':'DeFiFormal-source-evidence'}),timeout=60) as r:body=r.read();status=r.status;headers=dict(r.headers);final=r.url
assert status==200 and len(body)<1000000 and hashlib.sha1(b'blob '+str(len(body)).encode()+b'\0'+body).hexdigest()==blob
(O/'LicenseController.sol').write_bytes(body);put(O/'http.json',{'url':url,'final_url':final,'started_utc':start,'finished_utc':now(),'status':status,'headers':headers,'bytes':len(body),'sha256':sha(body),'git_blob_sha1':blob})
edges=[]
for mt in re.finditer(r'\bimport\s+(?:[^;]*?\bfrom\s+)?["\']([^"\']+)["\']\s*;',body.decode()):
 spec=mt.group(1);target=posixpath.normpath(posixpath.join(posixpath.dirname(name),spec)) if spec.startswith('.') else spec;assert target in m['source_locations'],target;edges.append({'from':name,'import':spec,'resolved':target})
put(O/'identity.json',{'utc':now(),'repository':pin['repository'],'commit':pin['commit'],'tree':pin['tree'],'compiler_path':name,'upstream_path':path,'sha256':sha(body),'git_blob_sha1':blob,'prior_compiler_sources':70,'source_locations':{**m['source_locations'],name:str((O/'LicenseController.sol').relative_to(B))},'source_hashes':{**m['source_hashes'],name:sha(body)},'compiler_source_count':71,'additional_lexical_import_edges':edges,'scope':'Additional registry license authorization implementation used by ProductService fallback. Runtime registry/deployment state remains an assumption.','P28_accepted':False});shutil.copy2(__file__,O/'capture.py');put(O/'root-seal.json',{'files':{p.name:sha(p.read_bytes()) for p in O.iterdir() if p.is_file()},'P28_accepted':False});print(json.dumps({'additional_source_files':1,'additional_lexical_import_edges':len(edges),'compiler_sources':71,'acceptance':False}))
