from pathlib import Path
import datetime,hashlib,json,shutil
O=Path('/home/charl/defiformal/review/semantic-kernel/program-execution-20260908/p27-gmx-source-preparation-attempt2');h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def put(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
anchors=[]
def add(ident,path,needle,claim):
 p=O/'source'/path;lines=p.read_text().splitlines();found=[i+1 for i,line in enumerate(lines) if needle in line];assert found,(ident,needle)
 anchors.append({'id':ident,'path':'source/'+path,'sha256':h(p),'needle':needle,'matching_lines':found,'static_observation':claim,'proof_or_execution':False})
u='contracts/position/PositionUtils.sol';d='contracts/position/DecreasePositionCollateralUtils.sol';f='contracts/pricing/PositionPricingUtils.sol';m='contracts/market/MarketUtils.sol'
add('liquidation-equity',u,'info.remainingCollateralUsd =','Liquidation valuation adds signed position PnL and price impact to collateral USD and subtracts token-denominated costs converted at collateral price.min. This is a health valuation, not an available token balance.')
add('nonpositive-liquidation',u,'if (info.remainingCollateralUsd <= 0) {','Nonpositive remaining equity is a liquidation condition, alongside minimum collateral and leverage thresholds.')
add('collateral-no-positive-pnl',u,'if (values.realizedPnlUsd < 0) {','Collateral-sufficiency calculation deducts negative realized PnL but does not credit positive PnL; keep this check distinct from liquidation equity.')
add('liquidatable-position-guard',u,'revert Errors.LiquidatablePosition(','validatePosition can reject a liquidatable position. This guard is not the same as executing a permitted liquidation order.')
add('insolvent-close-admission',d,'collateralCache.isInsolventCloseAllowed =','Insolvent early close requires a full size reduction and either liquidation order or secondary ADL classification. Later caller checks and transaction success are separate.')
add('cost-refusal',d,'revert Errors.InsufficientFundsToPayForCosts(','handleEarlyReturn rejects unpaid costs when the insolvent-close condition is false. This is a concrete source refusal candidate.')
add('insolvent-residual-event',d,'PositionEventUtils.emitInsolventClose(','Allowed insolvent early return emits the remainingCostUsd and payment step, then returns empty fee values; this event is not a self-executing insurance payout or a proven debt ledger.')
add('funding-shortfall-event',d,'PositionEventUtils.emitInsufficientFundingFeePayment(','Insufficient collateral-token funding payment emits expected/paid primary and paid secondary amounts. Comments proposing pool top-up/insurance are not an executed automatic top-up.')
add('holding-address-refusal',d,'revert Errors.EmptyHoldingAddress();','Funding paid in secondary output tokens requires a nonzero configured holding address before recording claimable collateral for that address.')
add('primary-payment-rounding',d,'Calc.roundUpDivision(costUsd, collateralTokenPrice.min)','payForCost first rounds cost upward in collateral-token units, then consumes output collateral tokens and remaining position collateral.')
add('secondary-payment-rounding',d,'remainingCostInOutputToken * collateralTokenPrice.min / secondaryOutputTokenPrice.min','Secondary token conversion uses integer division. Explicit accounting must distinguish source-rounded remainingCostUsd from an exact rational residual and preserve dust/valuation assumptions.')
add('withdrawal-token-cap',d,'if (params.order.initialCollateralDeltaAmount() > values.remainingCollateralAmount) {','Requested collateral withdrawal is capped by remainingCollateralAmount at this stage; unrealized equity must not be silently substituted for these token units.')
add('funding-fee-versus-claimables',f,'fundingFees.fundingFeeAmount = MarketUtils.getFundingAmount(','Funding has separate unsigned fee and long/short claimable token amounts; fee calculation rounds up, claimable calculations round down. Signed net reconciliation must retain asset/unit identity.')
add('funding-cumulative-difference',m,'uint256 fundingDiffFactor = (latestFundingAmountPerSize - positionFundingAmountPerSize);','Funding is derived from a checked unsigned cumulative-factor difference and size via scaled mulDiv; this is not an unconstrained signed cash increment.')
add('claimable-account-key',m,'Keys.claimableFundingAmountKey(market, token, account)','Claimable funding is keyed by market/token/account; accrual and claim logic operate on these records separately from position collateral.')
add('claim-transfer',m,'MarketToken(payable(market)).transferOut(','claimFundingFees clears claimable records and transfers the selected token before balance validation. Other functions share transferOut calls; the claim path is bounded by its function body.')
put(O/'source-navigation.json',{'utc':now(),'anchors':anchors,'anchor_count':len(anchors),'scope':'Static source navigation only; no compiler, contract execution, Lean proof, deployment identity or accepted observation contract.','P27_accepted':False})
s=json.loads((O/'source-manifest.json').read_text())
(O/'README.md').write_text(f'''# P27 GMX source candidate

Root captured {s['file_count']} official GMX Synthetics files at commit `{s['commit']}`, matching the captured commit tree's Git blob identities. Seven position/pricing/market/liquidation seeds reach {s['traversed_source_files']} local Solidity sources through {len(s['local_import_edges'])} lexical import edges. There are {len(s['unresolved_external_imports'])} unresolved external import occurrences. Three reference TypeScript tests and eight configuration/documentation files are also retained. This is a candidate for AGY source-entry design and later independent review, not an accepted P27 contract or a deployed address identity.

The first archive transfer exceeded the100MiB capture limit and stopped. Its partial cache bytes and failed script are recorded in `../p27-gmx-source-preparation/`; it supplied no extracted source and is not a complete archive. This attempt fetched individual raw files at the exact commit, with one HTTP receipt per file and Git blob verification. No source archive completion or whole repository acquisition is claimed.

The liquidation health equation combines collateral USD, signed position PnL, price impact and costs. The collateral-sufficiency check instead deducts negative realized PnL and does not credit positive PnL. PnL may therefore affect liquidation health without becoming spendable collateral tokens. The later PnL-as-cash mutant must target the correct observation; removing PnL from the liquidation equation would not represent source fidelity.

Funding is represented by a fee amount and separate claimable long/short token amounts, with opposing rounding directions. Claimables are stored by market/token/account and transferred by a separate claim path. A signed net equation must preserve token identities, conversion prices, rounding, fee liabilities and claimable assets. It must not relabel all of them as one cash field.

`handleEarlyReturn` provides an actual `InsufficientFundsToPayForCosts` refusal when insolvent close is disallowed. A full liquidation or secondary ADL close can take the insolvent early-return path and emit remaining cost and payment stage. Other caller checks still apply. Funding shortfalls and insolvent residual events do not automatically execute the insurance/top-up mechanism mentioned in comments. No general solvency, unconditional liquidation success or automatic bankruptcy compensation is established.

`payForCost` rounds collateral-token cost upward, then consumes primary output, remaining position collateral and secondary output. Its secondary conversion uses integer division. An exact financial reconciliation must expose rounding residue and distinguish the source's rounded `remainingCostUsd` from an arbitrary rational shortfall. Positive oracle-price, decimals/scales, Solidity integer safety, pool/custody/holding-address state, caller authority and transaction/runtime assumptions remain explicit.

Source configuration names Solidity0.8.29 with optimizer runs10 and constant optimizer enabled; Hardhat's local network allows unlimited contract size. package.json selects OpenZeppelin4.9.3. These are source configuration declarations, not installed tool or deployed bytecode identities. Dependencies, test imports and compiler closure remain unresolved. No npm install, Solidity compilation, EVM execution, reference test, Lean proof or mutation ran in this capture. The old graph returned legacy margin audit nodes and did not establish current P27 readiness.

P27 tasks28.1–28.3 remain open: freeze actual funding/equity/refusal observations and assumptions, implement `Margin`, prove signed reconciliation with residual, run funding success and allowed liquidation/insolvency controls plus actual refusal, and detect PnL-as-cash and source-independent equation failures under independent review. Full roadmap completion is unchanged.
''')
shutil.copy2(__file__,O/'scope.py');files={str(p.relative_to(O)):h(p) for p in O.rglob('*') if p.is_file()};assert 'root-seal.json' not in files;put(O/'root-seal.json',{'utc':now(),'files':files,'file_count':len(files),'P27_accepted':False});print(json.dumps({'sealed_files':len(files),'source_files':s['file_count'],'anchors':len(anchors),'acceptance':False}))
