from pathlib import Path
import json,hashlib,datetime,subprocess
R=Path('/home/charl/defiformal');B=R/'review/semantic-kernel/program-execution-20260908';C=B.parent/'strategy-audit-20260908/CURRENT.json';h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();read=lambda p:json.loads(p.read_text());now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def put(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
a=read(B/'p19-roundtrip-proof-agy-r25-dispatch.json');g=read(B/'p19-module-validity-grok-r1/closeout/dispatch.json');assert Path('/proc',str(a['pid'])).exists() and Path('/proc',str(g['pid'])).exists();assert not subprocess.check_output(['git','diff','--cached','--name-only'],cwd=R,text=True).strip()
corr={'utc':now(),'actual_R24_source_manifest_bindings':13,'all_13_bindings_verified_in':'p19-r24-root-scope-attempt3/scope.json','incorrect_historical_statements':['r24-freeze-r25-dispatch.json:R24_source_manifest_bindings=15','p19-module-validity-grok-r1/brief.txt:15sourcemanifestbindings'],'corrected_interpretation':'R24 source-manifest.json has13 Certificate source entries, all verified. Root scope/precheck already recorded13 correctly. Wrapper dispatch receipt and review brief copied15 from earlier scope. Raw historical bytes preserved; closeout informed of exact count.','proof_inventory_unchanged':578,'author_MANIFEST_valid_bindings':9,'author_MANIFEST_stale_commands_binding':1,'acceptance':False};corrpath=B/'p19-r24-source-manifest-count-correction.json';put(corrpath,corr)
s=read(B/'STATE.json');c=read(C);s['updated_utc']=now();s['phase']='AGY_R25_running_R24_Grok_same_session_missing_axiom_probe_and_reporting_closeout';s['p19']['module_validity_review']['status']='original_max30turns_six_commands_built_reports_in_progress_probe_missing';s['p19']['module_validity_review']['original_process']='p19-module-validity-grok-r1/process.json';s['p19']['module_validity_review']['original_seal']='p19-module-validity-grok-r1/original-terminal/root-seal.json';s['p19']['module_validity_review']['closeout']={**g,'root_supervisor_handle':22337};s['p19']['agy_r24']['source_manifest_count_correction']=corrpath.name;s['independent_reviewer']={**g,'root_supervisor_handle':22337};s['p27']['prepared_source_review']={'launcher':'p27-source-grok-r1-launcher.py','status':'prepared_not_launched','guard':'requires completed/root-sealed R24 review and R25 not terminal; prioritize terminal author proof audit','acceptance':False};s['continuation_loop']['native_reviewer_status']='R24_same_independent_session_missing578probe_then_reporting_closeout_running';s['continuation_loop']['observed_utc']=now();s['next_actions']=['Poll AGY R25 supervisor27928/pid2362900. Freeze only terminal and no child processes using prepared R25 helper; inspect exact full proof progress.','Poll same-session R24 Grok closeout22337/pid2393712,12turn cap. Only missing578probe then finalize reports. Original30turnattempt builtRoundtrip/Verify and ranpreflight/context/sorrycheck but reports stilldraft; no finalacceptance.','After closeout terminal verify frozen sources/privatebuild/names/axioms and finalreportbindings. Root correctR24source-manifestcount is13, not15 inbrief/dispatch summary.','Prepared P27 source/dependency/compiler audit launcher may run only after R24reviewsealed and ifauthorR25notterminal; otherwise prioritize newfrozenauthorproofaudit.','P28 bounded ABI diagnostic publishedc3aa827a: sourceflowreturns(false,7,93), Product reads(0,7), ignoringreturncontinues withmockeffects; nofullinsurance lifecycle orcustodyproof. Fullcoregoalactive,Atlasparked.'];put(B/'STATE.json',s);c['updated_utc']=now();c['current_task']=s['phase'];c['process_liveness']={'observed_utc':now(),'author_pid':a['pid'],'author_live':True,'author_supervisor':27928,'reviewer_pid':g['pid'],'reviewer_live':True,'reviewer_supervisor':22337,'reviewer_scope':'R24 same-session missing axiom probe and reporting closeout','note':'Recheck on resume. OriginalR24reviewterminalexit1 at30turns; sixsuccessfulcommands, reportsdraft.'};put(C,c)
paths={B/'STATE.json',C,corrpath,B/'p27-source-grok-r1-launcher.py',B/'p19-module-validity-grok-r1/closeout-launcher.py',B/'p19-module-validity-grok-r1/closeout/brief.txt',B/'p19-module-validity-grok-r1/closeout/dispatch.json'};o=B/'p19-module-validity-grok-r1/original-terminal';paths.add(o/'root-seal.json')
for p,d in read(o/'root-seal.json')['files'].items():assert h(o/p)==d,p;paths.add(o/p)
subprocess.run(['git','add','-f','--',*[str(p.relative_to(R)) for p in sorted(paths)]],cwd=R,check=True);subprocess.run(['git','-c','core.whitespace=-blank-at-eol,-blank-at-eof','diff','--cached','--check'],cwd=R,check=True);print(json.dumps({'paths':len(paths),'original_R24_review_sealed_files':len(read(o/'root-seal.json')['files']),'closeout_supervisor':22337}));subprocess.run(['git','diff','--cached','--stat'],cwd=R,check=True)
