/* B: STRUCTURE. Cn is generated by rules with a single-element consequent and a
 * disjunctive-but-effectively-unary subject list: a law fires if ANY subject is
 * present, and then adds each definite consequent. So the rule set is exactly a
 * set of arcs s -> e, and Cn(S) = the reachable set from S in that digraph.
 * This file (1) builds the digraph, (2) PROVES the reachability identity by
 * brute-force agreement with the original cl() on many seeds, (3) computes SCCs.
 */
import { PARSED_NEW, MECH } from "./tables.mjs";

const E = MECH.slice();
const IDX = new Map(E.map((s, i) => [s, i]));

// original closure, verbatim from antiexchange.mjs
function cl(S) {
  const X = new Set(S);
  let grew = true;
  while (grew) {
    grew = false;
    for (const law of PARSED_NEW) {
      if (!law.subjects.some(s => X.has(s))) continue;
      for (const t of law.terms) {
        if (t.external || t.alts.length !== 1) continue;
        if (!X.has(t.alts[0])) { X.add(t.alts[0]); grew = true; }
      }
    }
  }
  return X;
}

// ---- the digraph
const ARCS = [];          // [s, e, lawId]
for (const law of PARSED_NEW) {
  for (const t of law.terms) {
    if (t.external || t.alts.length !== 1) continue;
    for (const s of law.subjects) ARCS.push([s, t.alts[0], law.id]);
  }
}
const succ = new Map(E.map(e => [e, new Set()]));
for (const [s, e] of ARCS) if (succ.has(s) && succ.has(e)) succ.get(s).add(e);

function reach(S) {
  const X = new Set(S), stack = [...S];
  while (stack.length) {
    const v = stack.pop();
    for (const w of (succ.get(v) || [])) if (!X.has(w)) { X.add(w); stack.push(w); }
  }
  return X;
}
const eq = (a, b) => a.size === b.size && [...a].every(x => b.has(x));

console.log(`elements: ${E.length}`);
console.log(`arcs (with multiplicity over laws): ${ARCS.length}`);
const uniqArcs = new Set(ARCS.map(a => a[0] + "->" + a[1]));
console.log(`distinct arcs: ${uniqArcs.size}`);
const selfLoops = [...uniqArcs].filter(a => { const [x, y] = a.split("->"); return x === y; });
console.log(`self-loops: ${selfLoops.length} ${JSON.stringify(selfLoops)}`);
console.log(`arcs whose endpoint is outside MECH (dropped): ${ARCS.filter(([s,e])=>!IDX.has(s)||!IDX.has(e)).length}`);

// ---- (2) agreement cl == reach, on every singleton, every pair, and 200k random seeds
let bad = 0, tested = 0;
const chk = S => { tested++; if (!eq(cl(S), reach(S))) { bad++; if (bad < 4) console.log("MISMATCH", S); } };
chk([]);
for (const a of E) chk([a]);
for (const a of E) for (const b of E) if (a < b) chk([a, b]);
let seed = 12345;
const rnd = () => {seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296;};
for (let i = 0; i < 20000; i++) {
  const k = 1 + Math.floor(rnd() * 12);
  const S = [];
  for (let j = 0; j < k; j++) S.push(E[Math.floor(rnd() * E.length)]);
  chk([...new Set(S)]);
}
console.log(`\ncl == reach agreement: ${tested - bad}/${tested}  (mismatches: ${bad})`);

// ---- (3) SCCs (Tarjan)
let idc = 0; const idxm = new Map(), low = new Map(), onstk = new Set(), stk = [], comps = [];
function strong(v) {
  idxm.set(v, idc); low.set(v, idc); idc++; stk.push(v); onstk.add(v);
  for (const w of (succ.get(v) || [])) {
    if (!idxm.has(w)) { strong(w); low.set(v, Math.min(low.get(v), low.get(w))); }
    else if (onstk.has(w)) low.set(v, Math.min(low.get(v), idxm.get(w)));
  }
  if (low.get(v) === idxm.get(v)) {
    const c = []; let w;
    do { w = stk.pop(); onstk.delete(w); c.push(w); } while (w !== v);
    comps.push(c);
  }
}
for (const v of E) if (!idxm.has(v)) strong(v);
const nontrivial = comps.filter(c => c.length > 1);
console.log(`SCCs: ${comps.length}  (nontrivial, size>1: ${nontrivial.length})`);
for (const c of nontrivial) console.log(`   NONTRIVIAL SCC: {${c.sort().join(",")}}`);

// ---- mutual reachability pairs = exactly the anti-exchange violators (see proof)
const R = new Map(E.map(e => [e, reach([e])]));
const mutual = [];
for (const x of E) for (const y of E) if (x < y && R.get(x).has(y) && R.get(y).has(x)) mutual.push([x, y]);
console.log(`mutually-reachable distinct pairs: ${mutual.length} ${JSON.stringify(mutual.slice(0,10))}`);
console.log(mutual.length === 0
  ? "\n=> digraph is ACYCLIC up to self-loops. By Theorem (see FINDINGS), Cn is anti-exchange ON ALL 2^58 SUBSETS."
  : "\n=> digraph HAS a nontrivial cycle. Anti-exchange FAILS globally; witness A={} with the pair above.");

// arc list for the record
console.log(`\narcs:`);
const byLaw = new Map();
for (const [s, e, id] of ARCS) byLaw.set(id, [...(byLaw.get(id) || []), `${s}->${e}`]);
for (const [id, l] of byLaw) console.log(`  ${id}: ${[...new Set(l)].join(" ")}`);
