/-
Copyright (c) 2026. Released under Apache 2.0 license.
Authors: DefiElements
-/
import Mathlib.Order.Closure
import Mathlib.Data.Finset.Card
import Mathlib.Data.Finset.Max
import Mathlib.Data.Fintype.Powerset
import Mathlib.Logic.Relation

/-!
# Anti-exchange closures, unique minimum generators, and reachability

Machine-checked counterparts of Theorems `R` and `U`.

## Main results

* `ex_subset_of_generates` — the "extreme points" `ex c A` sit inside *every* generator of `A`.
  Needs no anti-exchange hypothesis.
* `maximal_closed_gap` — under anti-exchange, a closed set of maximum cardinality strictly
  below a closed `A` (relative to a floor `D`) misses exactly one point of `A`.
* `closure_ex` — under anti-exchange, `ex c A` really generates `A`.
* `unique_minimum_generator` — every closed set has a unique *minimum* generator, `ex c A`.
* `reachCl` — the closure operator generated by unary rules, i.e. reachability in a digraph.
* `reachCl_antiExchange_iff` — the reachability closure is anti-exchange **iff** the
  reachability preorder is antisymmetric (all strongly connected components are trivial).
-/

-- The ambient carrier is a *finite* ground set with decidable equality throughout; several
-- individual statements do not need one or the other, but the uniform signature is deliberate.
set_option linter.unusedFintypeInType false
set_option linter.unusedDecidableInType false
set_option linter.unusedSectionVars false

namespace Defialgebra

namespace ConvexGeometry

variable {E : Type*} [Fintype E] [DecidableEq E]

/-! ## The abstract part: anti-exchange and minimum generators -/

/-- The **anti-exchange** axiom for a closure operator on `Finset E`: from a closed set `A`
and two distinct outside points `x`, `y`, at most one of them can be dragged in by adjoining
the other. -/
def AntiExchange (c : ClosureOperator (Finset E)) : Prop :=
  ∀ A : Finset E, c A = A → ∀ x y : E, x ∉ A → y ∉ A → x ≠ y →
    x ∈ c (insert y A) → y ∉ c (insert x A)

/-- The **extreme points** of `A`: those `a ∈ A` not recoverable from the rest of `A`. -/
def ex (c : ClosureOperator (Finset E)) (A : Finset E) : Finset E :=
  A.filter (fun a => a ∉ c (A.erase a))

variable {c : ClosureOperator (Finset E)}

@[simp] lemma mem_ex {A : Finset E} {a : E} :
    a ∈ ex c A ↔ a ∈ A ∧ a ∉ c (A.erase a) := by
  simp only [ex, Finset.mem_filter]

lemma ex_subset (c : ClosureOperator (Finset E)) (A : Finset E) : ex c A ⊆ A :=
  Finset.filter_subset _ _

/-- Monotonicity of a closure operator, spelled with `⊆` rather than `≤`. -/
lemma cl_mono (c : ClosureOperator (Finset E)) {S T : Finset E} (h : S ⊆ T) : c S ⊆ c T :=
  c.monotone h

lemma subset_cl (c : ClosureOperator (Finset E)) (S : Finset E) : S ⊆ c S :=
  c.le_closure S

/-- **Theorem 1.** The extreme points of `A` are contained in *every* generating set of `A`.
No anti-exchange hypothesis is needed. -/
theorem ex_subset_of_generates (c : ClosureOperator (Finset E)) {A G : Finset E}
    (h : c G = A) : ex c A ⊆ G := by
  intro a ha
  rw [mem_ex] at ha
  by_contra haG
  have hGA : G ⊆ A := by rw [← h]; exact subset_cl c G
  have hGe : G ⊆ A.erase a := Finset.subset_erase.mpr ⟨hGA, haG⟩
  have h2 : A ⊆ c (A.erase a) := by
    have := cl_mono c hGe
    rwa [h] at this
  exact ha.2 (h2 ha.1)

/-- **Theorem 2** (relativised to a floor `D`). This is the only place anti-exchange is used.
If `C` is a closed set of maximum cardinality among the closed sets `C'` with `D ⊆ C' ⊆ A`
and `C' ≠ A`, then `A \ C` is a singleton. -/
theorem maximal_closed_gap (c : ClosureOperator (Finset E)) (hae : AntiExchange c)
    {D A C : Finset E} (hA : c A = A) (hC : c C = C)
    (hDC : D ⊆ C) (hCA : C ⊆ A) (hCne : C ≠ A)
    (hmax : ∀ C' : Finset E, c C' = C' → D ⊆ C' → C' ⊆ A → C' ≠ A → C'.card ≤ C.card) :
    ∃ x : E, A \ C = {x} := by
  -- Adjoining any point of `A \ C` to `C` and closing already reaches all of `A`.
  have key : ∀ z ∈ A \ C, c (insert z C) = A := by
    intro z hz
    obtain ⟨hzA, hzC⟩ := Finset.mem_sdiff.mp hz
    have hsubA : insert z C ⊆ A := Finset.insert_subset hzA hCA
    have h1 : c (insert z C) ⊆ A := by
      have := cl_mono c hsubA
      rwa [hA] at this
    have h2 : C ⊆ c (insert z C) :=
      (Finset.subset_insert z C).trans (subset_cl c _)
    have hzmem : z ∈ c (insert z C) := subset_cl c _ (Finset.mem_insert_self z C)
    by_contra hne
    have hle : (c (insert z C)).card ≤ C.card :=
      hmax _ (c.idempotent _) (hDC.trans h2) h1 hne
    have hss : C ⊂ c (insert z C) :=
      (Finset.ssubset_iff_of_subset h2).mpr ⟨z, hzmem, hzC⟩
    exact absurd (Finset.card_lt_card hss) (not_lt.mpr hle)
  have hne : (A \ C).Nonempty := by
    rw [Finset.sdiff_nonempty]
    intro hAC
    exact hCne (Finset.Subset.antisymm hCA hAC)
  have hcard : (A \ C).card ≤ 1 := by
    by_contra hgt
    rw [not_le] at hgt
    obtain ⟨x, hx, y, hy, hxy⟩ := Finset.one_lt_card.mp hgt
    have hxC : x ∉ C := (Finset.mem_sdiff.mp hx).2
    have hyC : y ∉ C := (Finset.mem_sdiff.mp hy).2
    have hyin : y ∈ c (insert x C) := by
      rw [key x hx]; exact (Finset.mem_sdiff.mp hy).1
    have hxin : x ∈ c (insert y C) := by
      rw [key y hy]; exact (Finset.mem_sdiff.mp hx).1
    exact hae C hC x y hxC hyC hxy hxin hyin
  exact Finset.card_eq_one.mp (Nat.le_antisymm hcard (Finset.card_pos.mpr hne))

/-- Unrelativised form of `maximal_closed_gap` (take `D = ∅`). -/
theorem maximal_closed_gap' (c : ClosureOperator (Finset E)) (hae : AntiExchange c)
    {A C : Finset E} (hA : c A = A) (hC : c C = C) (hCA : C ⊆ A) (hCne : C ≠ A)
    (hmax : ∀ C' : Finset E, c C' = C' → C' ⊆ A → C' ≠ A → C'.card ≤ C.card) :
    ∃ x : E, A \ C = {x} :=
  maximal_closed_gap c hae hA hC (Finset.empty_subset _) hCA hCne
    (fun C' h1 _ h3 h4 => hmax C' h1 h3 h4)

/-- **Theorem 3.** Under anti-exchange, the extreme points of a closed set generate it. -/
theorem closure_ex (c : ClosureOperator (Finset E)) (hae : AntiExchange c)
    {A : Finset E} (hA : c A = A) : c (ex c A) = A := by
  have hDA : c (ex c A) ⊆ A := by
    have := cl_mono c (ex_subset c A)
    rwa [hA] at this
  by_contra hDne
  have hDF : c (ex c A) ∈
      (Finset.univ : Finset (Finset E)).filter
        (fun C => c C = C ∧ c (ex c A) ⊆ C ∧ C ⊆ A ∧ C ≠ A) := by
    simp only [Finset.mem_filter, Finset.mem_univ, true_and]
    exact ⟨c.idempotent _, Finset.Subset.refl _, hDA, hDne⟩
  obtain ⟨C, hCF, hCmax⟩ :=
    Finset.exists_max_image
      ((Finset.univ : Finset (Finset E)).filter
        (fun C => c C = C ∧ c (ex c A) ⊆ C ∧ C ⊆ A ∧ C ≠ A))
      Finset.card ⟨_, hDF⟩
  simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hCF
  obtain ⟨hCcl, hDC, hCA, hCne⟩ := hCF
  have hmax : ∀ C' : Finset E, c C' = C' → c (ex c A) ⊆ C' → C' ⊆ A → C' ≠ A →
      C'.card ≤ C.card := by
    intro C' h1 h2 h3 h4
    refine hCmax C' ?_
    simp only [Finset.mem_filter, Finset.mem_univ, true_and]
    exact ⟨h1, h2, h3, h4⟩
  obtain ⟨x, hx⟩ := maximal_closed_gap c hae hA hCcl hDC hCA hCne hmax
  have hxmem : x ∈ A \ C := by rw [hx]; exact Finset.mem_singleton_self x
  have hxA : x ∈ A := (Finset.mem_sdiff.mp hxmem).1
  have hxC : x ∉ C := (Finset.mem_sdiff.mp hxmem).2
  have heq : A.erase x = C := by
    apply Finset.Subset.antisymm
    · intro a ha
      rw [Finset.mem_erase] at ha
      by_contra haC
      have hmem : a ∈ A \ C := Finset.mem_sdiff.mpr ⟨ha.2, haC⟩
      rw [hx, Finset.mem_singleton] at hmem
      exact ha.1 hmem
    · intro a ha
      rw [Finset.mem_erase]
      exact ⟨fun h => hxC (h ▸ ha), hCA ha⟩
  have hxex : x ∈ ex c A := by
    rw [mem_ex, heq, hCcl]
    exact ⟨hxA, hxC⟩
  exact hxC (hDC (subset_cl c _ hxex))

/-- **Theorem 4 / Theorem U.** Every closed set `A` has a unique *minimum* generator, and it is
`ex c A`: it generates `A`, and it is contained in every other generator. -/
theorem unique_minimum_generator (c : ClosureOperator (Finset E)) (hae : AntiExchange c)
    {A : Finset E} (hA : c A = A) :
    ∃! G : Finset E, c G = A ∧ ∀ G' : Finset E, c G' = A → G ⊆ G' := by
  refine ⟨ex c A, ⟨closure_ex c hae hA, fun G' hG' => ex_subset_of_generates c hG'⟩, ?_⟩
  rintro G ⟨hG1, hG2⟩
  exact Finset.Subset.antisymm (hG2 _ (closure_ex c hae hA))
    (ex_subset_of_generates c hG1)

/-- The two halves of `unique_minimum_generator`, stated separately. -/
theorem ex_isMinimumGenerator (c : ClosureOperator (Finset E)) (hae : AntiExchange c)
    {A : Finset E} (hA : c A = A) :
    c (ex c A) = A ∧ ∀ G : Finset E, c G = A → ex c A ⊆ G :=
  ⟨closure_ex c hae hA, fun _ hG => ex_subset_of_generates c hG⟩

/-! ## The reachability part: Theorem R -/

section Reach

variable (r : E → E → Prop) [DecidableRel (Relation.ReflTransGen r)]

/-- The set of vertices reachable from `S` along `r`. -/
def reachSet (S : Finset E) : Finset E :=
  Finset.univ.filter (fun x => ∃ s ∈ S, Relation.ReflTransGen r s x)

@[simp] lemma mem_reachSet {S : Finset E} {x : E} :
    x ∈ reachSet r S ↔ ∃ s ∈ S, Relation.ReflTransGen r s x := by
  simp only [reachSet, Finset.mem_filter, Finset.mem_univ, true_and]

lemma reachSet_mono {S T : Finset E} (h : S ⊆ T) : reachSet r S ⊆ reachSet r T := by
  intro x hx
  rw [mem_reachSet] at hx ⊢
  obtain ⟨s, hs, hsx⟩ := hx
  exact ⟨s, h hs, hsx⟩

lemma subset_reachSet (S : Finset E) : S ⊆ reachSet r S := by
  intro x hx
  rw [mem_reachSet]
  exact ⟨x, hx, Relation.ReflTransGen.refl⟩

lemma reachSet_idem (S : Finset E) : reachSet r (reachSet r S) = reachSet r S := by
  apply Finset.Subset.antisymm _ (subset_reachSet r _)
  intro x hx
  rw [mem_reachSet] at hx
  obtain ⟨s, hs, hsx⟩ := hx
  rw [mem_reachSet] at hs
  obtain ⟨t, ht, hts⟩ := hs
  rw [mem_reachSet]
  exact ⟨t, ht, hts.trans hsx⟩

/-- Reachability as a closure operator on `Finset E`. This is exactly the closure generated
by the unary rules `s → e` of the digraph `r`. -/
def reachCl : ClosureOperator (Finset E) where
  toFun := reachSet r
  monotone' := fun _ _ h => reachSet_mono r h
  le_closure' := fun S => subset_reachSet r S
  idempotent' := fun S => reachSet_idem r S

@[simp] lemma reachCl_apply (S : Finset E) : reachCl r S = reachSet r S := rfl

lemma reachSet_empty : reachSet r (∅ : Finset E) = ∅ := by
  ext x
  simp

/-- The key computational lemma: closing an insertion splits. -/
lemma reachSet_insert (x : E) (A : Finset E) :
    reachSet r (insert x A) = reachSet r A ∪ reachSet r {x} := by
  ext z
  simp only [mem_reachSet, Finset.mem_union, Finset.mem_insert, Finset.mem_singleton]
  constructor
  · rintro ⟨s, (rfl | hs), hsz⟩
    · exact Or.inr ⟨s, rfl, hsz⟩
    · exact Or.inl ⟨s, hs, hsz⟩
  · rintro (⟨s, hs, hsz⟩ | ⟨s, rfl, hsz⟩)
    · exact ⟨s, Or.inr hs, hsz⟩
    · exact ⟨s, Or.inl rfl, hsz⟩

/-- For a closed `A`, membership in `reachSet r (insert y A)` is membership in `A` or
reachability from `y`. -/
lemma mem_reachSet_insert_of_closed {A : Finset E} (hA : reachSet r A = A) (y x : E) :
    x ∈ reachSet r (insert y A) ↔ x ∈ A ∨ Relation.ReflTransGen r y x := by
  rw [mem_reachSet]
  constructor
  · rintro ⟨s, hs, hsx⟩
    rcases Finset.mem_insert.mp hs with rfl | hs
    · exact Or.inr hsx
    · refine Or.inl ?_
      rw [← hA, mem_reachSet]
      exact ⟨s, hs, hsx⟩
  · rintro (hx | hyx)
    · exact ⟨x, Finset.mem_insert_of_mem hx, Relation.ReflTransGen.refl⟩
    · exact ⟨y, Finset.mem_insert_self _ _, hyx⟩

/-- **Theorem R, forward direction.** If the reachability preorder is antisymmetric (every
strongly connected component is trivial) then the reachability closure is anti-exchange. -/
theorem reachCl_antiExchange_of_antisymm
    (h : ∀ x y : E, Relation.ReflTransGen r x y → Relation.ReflTransGen r y x → x = y) :
    AntiExchange (reachCl r) := by
  intro A hA x y hxA hyA hxy hx
  have hA' : reachSet r A = A := hA
  rw [reachCl_apply, mem_reachSet_insert_of_closed r hA'] at hx
  have hyx : Relation.ReflTransGen r y x := hx.resolve_left hxA
  intro hy
  rw [reachCl_apply, mem_reachSet_insert_of_closed r hA'] at hy
  have hxy' : Relation.ReflTransGen r x y := hy.resolve_left hyA
  exact hxy (h x y hxy' hyx)

/-- **Theorem R, converse direction.** If the reachability closure is anti-exchange then the
reachability preorder is antisymmetric. -/
theorem antisymm_of_reachCl_antiExchange (h : AntiExchange (reachCl r)) :
    ∀ x y : E, Relation.ReflTransGen r x y → Relation.ReflTransGen r y x → x = y := by
  intro x y hxy hyx
  by_contra hne
  have hcl : reachCl r (∅ : Finset E) = ∅ := reachSet_empty r
  have hx : x ∈ reachCl r (insert y (∅ : Finset E)) := by
    rw [reachCl_apply, mem_reachSet]
    exact ⟨y, Finset.mem_insert_self _ _, hyx⟩
  refine h ∅ hcl x y (Finset.notMem_empty x) (Finset.notMem_empty y) hne hx ?_
  rw [reachCl_apply, mem_reachSet]
  exact ⟨x, Finset.mem_insert_self _ _, hxy⟩

/-- **Theorem R.** The reachability closure satisfies anti-exchange if and only if the
reachability preorder is antisymmetric. -/
theorem reachCl_antiExchange_iff :
    AntiExchange (reachCl r) ↔
      ∀ x y : E, Relation.ReflTransGen r x y → Relation.ReflTransGen r y x → x = y :=
  ⟨antisymm_of_reachCl_antiExchange r, reachCl_antiExchange_of_antisymm r⟩

/-! ### The extreme points of a reachability closure are the minimal elements -/

/-- For the reachability closure, `ex` computes the `≤`-**minimal** elements of `A`, where
`≤` is the reachability preorder. (Antisymmetry is not needed for this identification; under
antisymmetry `≤` is a genuine partial order and these are minimal in the usual sense.) -/
theorem ex_reachCl (A : Finset E) :
    ex (reachCl r) A =
      A.filter (fun a => ∀ b ∈ A, Relation.ReflTransGen r b a → b = a) := by
  ext a
  rw [mem_ex, Finset.mem_filter, reachCl_apply]
  constructor
  · rintro ⟨haA, h⟩
    refine ⟨haA, fun b hbA hba => ?_⟩
    by_contra hne
    exact h ((mem_reachSet r).mpr ⟨b, Finset.mem_erase.mpr ⟨hne, hbA⟩, hba⟩)
  · rintro ⟨haA, h⟩
    refine ⟨haA, fun hmem => ?_⟩
    obtain ⟨b, hb, hba⟩ := (mem_reachSet r).mp hmem
    obtain ⟨hbne, hbA⟩ := Finset.mem_erase.mp hb
    exact hbne (h b hbA hba)

/-- Composition law: the extreme points of a union are the extreme points of the two pieces,
filtered down to those still minimal in the union. -/
theorem ex_reachCl_union (A B : Finset E) :
    ex (reachCl r) (A ∪ B) =
      (ex (reachCl r) A ∪ ex (reachCl r) B).filter
        (fun a => ∀ b ∈ A ∪ B, Relation.ReflTransGen r b a → b = a) := by
  ext a
  simp only [ex_reachCl, Finset.mem_filter, Finset.mem_union]
  constructor
  · rintro ⟨haAB, hmin⟩
    refine ⟨?_, hmin⟩
    rcases haAB with h | h
    · exact Or.inl ⟨h, fun b hb hba => hmin b (Or.inl hb) hba⟩
    · exact Or.inr ⟨h, fun b hb hba => hmin b (Or.inr hb) hba⟩
  · rintro ⟨(⟨h, _⟩ | ⟨h, _⟩), hmin⟩
    · exact ⟨Or.inl h, hmin⟩
    · exact ⟨Or.inr h, hmin⟩

end Reach

/-! ## Axiom audit

Every named result above depends only on Lean's three standard axioms (in fact several depend
on strictly fewer). No `sorry`, no new axioms.
-/

section AxiomAudit

#print axioms Defialgebra.ConvexGeometry.mem_ex
#print axioms Defialgebra.ConvexGeometry.ex_subset
#print axioms Defialgebra.ConvexGeometry.cl_mono
#print axioms Defialgebra.ConvexGeometry.subset_cl
#print axioms Defialgebra.ConvexGeometry.ex_subset_of_generates
#print axioms Defialgebra.ConvexGeometry.maximal_closed_gap
#print axioms Defialgebra.ConvexGeometry.maximal_closed_gap'
#print axioms Defialgebra.ConvexGeometry.closure_ex
#print axioms Defialgebra.ConvexGeometry.unique_minimum_generator
#print axioms Defialgebra.ConvexGeometry.ex_isMinimumGenerator
#print axioms Defialgebra.ConvexGeometry.mem_reachSet
#print axioms Defialgebra.ConvexGeometry.reachSet_mono
#print axioms Defialgebra.ConvexGeometry.subset_reachSet
#print axioms Defialgebra.ConvexGeometry.reachSet_idem
#print axioms Defialgebra.ConvexGeometry.reachCl
#print axioms Defialgebra.ConvexGeometry.reachCl_apply
#print axioms Defialgebra.ConvexGeometry.reachSet_empty
#print axioms Defialgebra.ConvexGeometry.reachSet_insert
#print axioms Defialgebra.ConvexGeometry.mem_reachSet_insert_of_closed
#print axioms Defialgebra.ConvexGeometry.reachCl_antiExchange_of_antisymm
#print axioms Defialgebra.ConvexGeometry.antisymm_of_reachCl_antiExchange
#print axioms Defialgebra.ConvexGeometry.reachCl_antiExchange_iff
#print axioms Defialgebra.ConvexGeometry.ex_reachCl
#print axioms Defialgebra.ConvexGeometry.ex_reachCl_union

end AxiomAudit


/-! ## Union-stability, down-sets, and the composition law for canonical forms

Paper: `lem:cm` (union-stability for singleton premises), `thm:convex`, `cor:ex`, `thm:excomp`.

Orientation warning. The paper's specialization preorder is `a ≽ b ↔ b ∈ Cn {a}`, i.e.
`a ≽ b` exactly when `a` reaches `b` along `r`. Consequently a `≼`-**maximal** element of `A`
is one that no *other* element of `A` reaches — reachability-**minimal**. This is exactly the
predicate used by `ex_reachCl`, so `ex = max_≼` as claimed in `cor:ex`.
-/

section ReachExtra

variable (r : E → E → Prop) [DecidableRel (Relation.ReflTransGen r)]

/-- **Union-stability** (paper `lem:cm`, the content that makes `A ⊕ B = A ∪ B`). Because
every definite rule has a *singleton* premise, the reachability closure distributes over
union. -/
theorem reachSet_union (A B : Finset E) :
    reachSet r (A ∪ B) = reachSet r A ∪ reachSet r B := by
  ext z
  simp only [mem_reachSet, Finset.mem_union]
  constructor
  · rintro ⟨s, (hs | hs), hsz⟩
    · exact Or.inl ⟨s, hs, hsz⟩
    · exact Or.inr ⟨s, hs, hsz⟩
  · rintro (⟨s, hs, hsz⟩ | ⟨s, hs, hsz⟩)
    · exact ⟨s, Or.inl hs, hsz⟩
    · exact ⟨s, Or.inr hs, hsz⟩

/-- Same statement for the closure operator. -/
theorem reachCl_union (A B : Finset E) :
    reachCl r (A ∪ B) = reachCl r A ∪ reachCl r B := reachSet_union r A B

/-- For closed `A` and `B`, the composite `A ⊕ B = Cn (A ∪ B)` is literally `A ∪ B`. -/
theorem reachCl_union_of_closed {A B : Finset E}
    (hA : reachCl r A = A) (hB : reachCl r B = B) : reachCl r (A ∪ B) = A ∪ B := by
  rw [reachCl_union, hA, hB]

/-- **The closed sets are exactly the down-sets of the specialization preorder** (paper
`thm:convex`, second half). Here "down-set" is taken in the `≼`-orientation of the paper:
`A` is closed iff everything `a ∈ A` reaches stays in `A`. -/
theorem reachSet_eq_self_iff (A : Finset E) :
    reachSet r A = A ↔ ∀ a ∈ A, ∀ b : E, Relation.ReflTransGen r a b → b ∈ A := by
  constructor
  · intro h a ha b hab
    rw [← h, mem_reachSet]
    exact ⟨a, ha, hab⟩
  · intro h
    refine Finset.Subset.antisymm ?_ (subset_reachSet r A)
    intro x hx
    obtain ⟨s, hs, hsx⟩ := (mem_reachSet r).mp hx
    exact h s hs x hsx

/-- **Paper `thm:convex`, bundled.** The reachability closure is always union-stable and its
closed sets are always the down-sets of the specialization preorder; it satisfies
anti-exchange exactly when that preorder is antisymmetric, i.e. when the digraph is acyclic,
in which case the preorder is a genuine partial order. -/
theorem thm_convex :
    (∀ A B : Finset E, reachCl r (A ∪ B) = reachCl r A ∪ reachCl r B) ∧
      (∀ A : Finset E, reachCl r A = A ↔ ∀ a ∈ A, ∀ b : E, Relation.ReflTransGen r a b → b ∈ A) ∧
      (AntiExchange (reachCl r) ↔
        ∀ x y : E, Relation.ReflTransGen r x y → Relation.ReflTransGen r y x → x = y) :=
  ⟨reachCl_union r, reachSet_eq_self_iff r, reachCl_antiExchange_iff r⟩

/-! ### Descent to extreme points

The technical heart of `thm:excomp`. Antisymmetry of reachability is genuinely needed: with a
2-cycle `x ⇄ y` and `S = {x, y}` we have `ex S = ∅`, so no extreme point of `S` reaches `x`.
-/

/-- Every element of `S` is reached by an *extreme* element of `S`. Proved by strong
induction on the size of the down-set `{x ∈ S : x ≼ b}`; antisymmetry is what makes that
set shrink strictly at each step. -/
theorem exists_ex_reach_aux
    (hanti : ∀ x y : E, Relation.ReflTransGen r x y → Relation.ReflTransGen r y x → x = y)
    (S : Finset E) : ∀ (n : ℕ) (b : E), b ∈ S →
      (S.filter (fun x => Relation.ReflTransGen r x b)).card ≤ n →
      ∃ b' ∈ ex (reachCl r) S, Relation.ReflTransGen r b' b := by
  intro n
  induction n with
  | zero =>
    intro b hb hcard
    have hpos : 0 < (S.filter (fun x => Relation.ReflTransGen r x b)).card :=
      Finset.card_pos.mpr ⟨b, Finset.mem_filter.mpr ⟨hb, Relation.ReflTransGen.refl⟩⟩
    exact absurd hcard (by omega)
  | succ n ih =>
    intro b hb hcard
    by_cases h : ∀ y ∈ S, Relation.ReflTransGen r y b → y = b
    · refine ⟨b, ?_, Relation.ReflTransGen.refl⟩
      rw [ex_reachCl, Finset.mem_filter]
      exact ⟨hb, h⟩
    · push_neg at h
      obtain ⟨y, hyS, hyb, hne⟩ := h
      -- the down-set of `y` is a *strict* subset of the down-set of `b`
      have hsub : S.filter (fun x => Relation.ReflTransGen r x y) ⊆
          S.filter (fun x => Relation.ReflTransGen r x b) := by
        intro x hx
        obtain ⟨hxS, hxy⟩ := Finset.mem_filter.mp hx
        exact Finset.mem_filter.mpr ⟨hxS, hxy.trans hyb⟩
      have hbnot : b ∉ S.filter (fun x => Relation.ReflTransGen r x y) := by
        intro hbm
        exact hne (hanti y b hyb (Finset.mem_filter.mp hbm).2)
      have hssub : S.filter (fun x => Relation.ReflTransGen r x y) ⊂
          S.filter (fun x => Relation.ReflTransGen r x b) :=
        (Finset.ssubset_iff_of_subset hsub).mpr
          ⟨b, Finset.mem_filter.mpr ⟨hb, Relation.ReflTransGen.refl⟩, hbnot⟩
      have hlt := Finset.card_lt_card hssub
      obtain ⟨b', hb'ex, hb'y⟩ := ih y hyS (by omega)
      exact ⟨b', hb'ex, hb'y.trans hyb⟩

/-- Every element of `S` is reached by an extreme point of `S` (under acyclicity). -/
theorem exists_ex_reach
    (hanti : ∀ x y : E, Relation.ReflTransGen r x y → Relation.ReflTransGen r y x → x = y)
    {S : Finset E} {b : E} (hb : b ∈ S) :
    ∃ b' ∈ ex (reachCl r) S, Relation.ReflTransGen r b' b :=
  exists_ex_reach_aux r hanti S _ b hb le_rfl

/-- **Paper `thm:excomp`.** The extreme points of a union are the `≼`-maximal elements of the
union of the extreme points — the filter now ranges over the *generators only*, which is what
makes the law computable in `|ex A| + |ex B|`. Acyclicity is required. -/
theorem ex_reachCl_union_ex
    (hanti : ∀ x y : E, Relation.ReflTransGen r x y → Relation.ReflTransGen r y x → x = y)
    (A B : Finset E) :
    ex (reachCl r) (A ∪ B)
      = (ex (reachCl r) A ∪ ex (reachCl r) B).filter
          (fun a => ∀ b ∈ ex (reachCl r) A ∪ ex (reachCl r) B,
            Relation.ReflTransGen r b a → b = a) := by
  have hPsub : ex (reachCl r) A ∪ ex (reachCl r) B ⊆ A ∪ B :=
    Finset.union_subset_union (ex_subset _ A) (ex_subset _ B)
  ext a
  rw [ex_reachCl, Finset.mem_filter, Finset.mem_filter]
  constructor
  · -- easy direction: minimal over `A ∪ B` implies extreme in its own side and minimal over
    -- the smaller set of generators
    rintro ⟨haAB, hmin⟩
    refine ⟨?_, fun b hb hba => hmin b (hPsub hb) hba⟩
    rw [Finset.mem_union] at haAB ⊢
    rcases haAB with h | h
    · refine Or.inl ?_
      rw [ex_reachCl, Finset.mem_filter]
      exact ⟨h, fun b hb hba => hmin b (Finset.mem_union_left _ hb) hba⟩
    · refine Or.inr ?_
      rw [ex_reachCl, Finset.mem_filter]
      exact ⟨h, fun b hb hba => hmin b (Finset.mem_union_right _ hb) hba⟩
  · -- hard direction: descend an arbitrary `b ≼ a` to an extreme point of its own side
    rintro ⟨haP, hmin⟩
    refine ⟨hPsub haP, fun b hb hba => ?_⟩
    by_contra hne
    have hdesc : ∃ b' ∈ ex (reachCl r) A ∪ ex (reachCl r) B,
        Relation.ReflTransGen r b' b := by
      rcases Finset.mem_union.mp hb with h | h
      · obtain ⟨b', hb', hb'b⟩ := exists_ex_reach r hanti h
        exact ⟨b', Finset.mem_union_left _ hb', hb'b⟩
      · obtain ⟨b', hb', hb'b⟩ := exists_ex_reach r hanti h
        exact ⟨b', Finset.mem_union_right _ hb', hb'b⟩
    obtain ⟨b', hb'P, hb'b⟩ := hdesc
    -- `b'` is a generator reaching `a`, so minimality of `a` over the generators forces
    -- `b' = a`; then `a` and `b` reach each other and antisymmetry kills the assumption.
    have hb'a : Relation.ReflTransGen r b' a := hb'b.trans hba
    have : b' = a := hmin b' hb'P hb'a
    subst this
    exact hne (hanti b' b hb'b hba).symm

/-- **Paper `thm:excomp`, in `⊕` form.** For *closed* `A` and `B` the composite is
`Cn (A ∪ B)` and its canonical form is computed from the canonical forms of the parts. -/
theorem ex_oplus
    (hanti : ∀ x y : E, Relation.ReflTransGen r x y → Relation.ReflTransGen r y x → x = y)
    {A B : Finset E} (hA : reachCl r A = A) (hB : reachCl r B = B) :
    ex (reachCl r) (reachCl r (A ∪ B))
      = (ex (reachCl r) A ∪ ex (reachCl r) B).filter
          (fun a => ∀ b ∈ ex (reachCl r) A ∪ ex (reachCl r) B,
            Relation.ReflTransGen r b a → b = a) := by
  rw [reachCl_union_of_closed r hA hB]
  exact ex_reachCl_union_ex r hanti A B

end ReachExtra

section AxiomAudit2

#print axioms Defialgebra.ConvexGeometry.reachSet_union
#print axioms Defialgebra.ConvexGeometry.reachCl_union
#print axioms Defialgebra.ConvexGeometry.reachCl_union_of_closed
#print axioms Defialgebra.ConvexGeometry.reachSet_eq_self_iff
#print axioms Defialgebra.ConvexGeometry.thm_convex
#print axioms Defialgebra.ConvexGeometry.exists_ex_reach_aux
#print axioms Defialgebra.ConvexGeometry.exists_ex_reach
#print axioms Defialgebra.ConvexGeometry.ex_reachCl_union_ex
#print axioms Defialgebra.ConvexGeometry.ex_oplus

end AxiomAudit2

end ConvexGeometry

end Defialgebra
