from pathlib import Path
import json,hashlib,re,subprocess,datetime
r=Path(__file__).resolve().parents[3];out=Path(__file__).parent/'planning';change=Path('openspec/changes/operational-continuation-congruence');head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=r,text=True).strip();source='99e2e2c61a1a3c5249026921efdc6cd41ac8f21d';delivery=json.loads((r/'review/semantic-kernel/sprint8/archive-delivery.json').read_text());assert delivery['archive_complete'] and delivery['remote_matches'];assert not(r/'lean/DefiKernel/Metatheory').exists()
mods=set();todo=['DefiKernel.Atomic.Verify']
while todo:
 m=todo.pop()
 if m in mods:continue
 p=Path('lean')/Path(*m.split('.')).with_suffix('.lean');assert(r/p).exists();mods.add(m)
 for dep in re.findall(r'^import\s+(\S+)',(r/p).read_text(),re.M):
  if dep.startswith('DefiKernel.'):todo.append(dep)
paths=[Path('AGENTS.md'),change/'proposal.md',change/'design.md',change/'tasks.md']+[p.relative_to(r) for p in sorted((r/change/'specs').glob('*/spec.md'))]+[Path('wiki-llm/sprint-9-operational-continuation-congruence.md')]+[Path('lean')/Path(*m.split('.')).with_suffix('.lean') for m in sorted(mods)]+[Path('lean')/p for p in ['lean-toolchain','lakefile.toml','lake-manifest.json']]+[Path('scripts/check_atomic_mutations.py'),Path('scripts/test_atomic_mutation_runner.py')]
paths += [Path('review/semantic-kernel/sprint9/planning')/p for p in ['AUTHOR-REVIEW.md','author-validation.json','scenario-planning-map.json','context-refresh.json','dependency-baseline-binding.json','baseline/gate-evidence.json']]
paths += [Path('review/semantic-kernel/sprint8')/p for p in ['final-review/acceptance.json','implementation/log-pointer-fix-binding.json','delivery.json','archive-delivery.json']]
header=f'''Independent Sprint9 OpenSpec PLANNING audit. Frozen plan candidate {head}, accepted Sprint8 source context {source}, verified accepted archive {delivery['archive_metadata_commit']}. This is not implementation review. No Metatheory source exists yet. Return a substantive plain-text final starting VERDICT: ACCEPT, ACCEPT WITH LIMITATIONS or REVISE, then BLOCKERS, REQUIRED CHANGES, NONBLOCKING LIMITATIONS and CLAIM/SCOPE CHECK. Do not emit proposed tool calls or XML. No edits, implementation, external messages or Foreman. Treat author checks as untrusted claims to inspect. No unexecuted check claims. A passing plan must be precise, feasible and noncircular; identify actual semantic/proof/coverage blockers with concrete counterexamples.

The user requires GPT6 stock-harness implementation; independent nonauthor GPT6 and native Opus planning passes on this SAME frozen candidate/bundle before any code. Native Grok+Opus will review substantive implementation and final evidence. Fable remains only historical evidence. Requested Opus alias is opus; actual response model is recorded.

Scope M1: genuinely recursive SeqGroup interpreter using actual Composition.advance at leaves and entire cursor propagation; exact simulation to existing continuation; identity/refusal absorption/fullcursor associativity. Exact continuation observations include fullworld/store, event request/receipt/outputs, frozen histories, nextindex and firstlocatedfailure; omit only past raw event worlds. Restricted fixed before/after single-hole context grammar and universally quantified GroupEquivalent, with a real same-entry counterexample. Explicit ConfigAgreement/support props preserve fullusedlookup pair and registry templates, bothcatalogvalidity and all-domain admins; administrative Grant.operation references are included. Derive actual executeStep equality for success/refusal without assuming it, liftactual sequences/groups and existing Parallel/Interleaving/Atomic operators including staticadmission/errorprecedence. No newcertificatechecker, finite-participant executor, activepeerextension, aliasrewriter oratomicboundaryregrouping. Review exactmodelcode for hidden dependencies, field names, authorityfreshID/store/registryscope, callbackworld/history/time sensitivity, rejected suffixes, projectionadequacy and independent expectedfinance. Examine14planned actualmutants and complete65 inherited defensivecontrols, planned55scenario/35taskmapping, baseline/source/model/evidence discipline and the explicit laterM2-M6 boundary. Determine whether the proposed exacttheorems/runtimecases are sufficient for these claims and possible underactualexistingcode; do not invent broader normative scope.

The fresh baseline has14Lean commands and13Python suites atactual99, allpass with148unchanged relevantinputs. Source/evidence equivalence supports metadata-only currentHEAD. This is baseline for authorized implementation after plan acceptance, not evidence that new Metatheory proofs already exist. Every original input binds current frozen Git bytes below.\n'''
rows=[];parts=[header]
for p in dict.fromkeys(paths):
 data=(r/p).read_bytes();assert data==subprocess.check_output(['git','show',head+':'+str(p)],cwd=r),p
 h=hashlib.sha256(data).hexdigest();row={'path':str(p),'sha256':h,'bytes':len(data),'git_blob':subprocess.check_output(['git','rev-parse',head+':'+str(p)],cwd=r,text=True).strip()}
 if str(p).startswith('lean/') or str(p).startswith('scripts/'):
  assert data==subprocess.check_output(['git','show',source+':'+str(p)],cwd=r);row['accepted_source_context']=source
 rows.append(row);render=json.dumps(json.loads(data),separators=(',',':'),ensure_ascii=False) if p.suffix=='.json' else data.decode();row['rendered_sha256']=hashlib.sha256(render.encode()).hexdigest();parts.append(f'\n\n===== INPUT {p} ORIGINAL_SHA256 {h} RENDERED_SHA256 {row["rendered_sha256"]} =====\n'+render)
b=''.join(parts).encode();(out/'r1-bundle.md').write_bytes(b);m={'candidate':head,'accepted_source_context':source,'accepted_dependency_archive':delivery['archive_metadata_commit'],'captured_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'input_count':len(rows),'inputs':rows,'bundle_bytes':len(b),'bundle_sha256':hashlib.sha256(b).hexdigest(),'review_kind':'independent same-candidate GPT6/Opus planning gate; no implementation yet','presentation':'Complete source and plan; JSON compact rendering with same parsed fields/values and separate hashes'};(out/'r1-candidate.json').write_text(json.dumps(m,indent=2)+'\n');print(json.dumps({k:v for k,v in m.items() if k!='inputs'},indent=2))
