import json,hashlib,re,math,subprocess
from pathlib import Path
from datetime import datetime,timezone
R=Path('/home/charl/defiformal');O=R/'review/semantic-kernel/historical-instance-audit';h=lambda b:hashlib.sha256(b).hexdigest();js=lambda p:json.loads(p.read_text());checks=[]
def write(p,x):
 with p.open('x') as f:json.dump(x,f,indent=2);f.write('\n')
def bind(p):
 b=p.read_bytes();return {'path':str(p.relative_to(R)),'sha256':h(b),'bytes':len(b)}
def check(n,x):checks.append({'name':n,'pass':bool(x)});assert x,n
before=js(O/'before.json');run=js(O/'execution.json');stdout=(O/'stdout.log').read_text();stderr=(O/'stderr.log').read_text()
check('completed',run['process_status']=='completed' and run['returncode']==0);check('stderr-empty',stderr=='');check('head-held',run['source_head_before']==run['source_head_after']==before['git_head']);check('runtime-input-count',before['runtime_dependency_count']==8)
for f in [run['stdout'],run['stderr']]:check('log-hash:'+f['path'],bind(R/f['path'])==f)
sections=re.findall(r'--- (LSTAR|PARSED_NEW) definite digraph ---\n(.*?)(?=\n---|\Z)',stdout,re.S);check('two-sections',len(sections)==2 and {s[0] for s in sections}=={'LSTAR','PARSED_NEW'});outcomes=[]
patterns={'graph':r'vertices (\d+); arcs (\d+); SCCs (\d+); non-trivial SCCs (\d+); self-loops (\d+)','equality':r'Cn == reachability on all (\d+) seeds of size <= 3: mismatches (\d+)','union':r'Cn\(A u B\) == Cn\(A\) u Cn\(B\) on (\d+) split seeds: failures (\d+)','anti_exchange':r'anti-exchange over (\d+) closed sets x (\d+)\^2 pairs \((\d+) tests\): violations (\d+)','composition':r'thm:excomp  ex\(A u B\) == max\(ex A u ex B\) over (\d+) closed pairs: failures (\d+)','principal':r'elements whose principal closure is themselves \(Cn\(\{e\}\) = \{e\}\): (\d+) / (\d+)'}
for label,body in sections:
 parsed={}
 for k,pat in patterns.items():
  ms=re.findall(pat,body);check(label+'-unique-'+k,len(ms)==1);parsed[k]=list(map(int,ms[0]))
 N,arcs,sccs,nontrivial,loops=parsed['graph'];eq,eqbad=parsed['equality'];un,ubad=parsed['union'];closed,n2,ae,aebad=parsed['anti_exchange'];pairs,pbad=parsed['composition'];own,n3=parsed['principal'];gen=N*(N+1)//2;distinct=closed-1
 check(label+'-nonempty',N>0 and eq>0 and un>0 and closed>0 and ae>0 and pairs>0)
 check(label+'-acyclic',nontrivial==loops==0 and sccs==N and 'ACYCLIC: true' in body)
 check(label+'-zero-violations',eqbad==ubad==aebad==pbad==0)
 check(label+'-loop-ranges',eq==sum(math.comb(N,k) for k in [1,2,3]) and un==math.comb(N,3) and pairs==gen*(gen+1)//2 and N==n2==n3)
 extract=re.search(label+r'.*?: definite \(singleton-term\) arcs = (\d+), distinct = (\d+)\n   ([^\n]+)',stdout);check(label+'-extraction',extract is not None);occ,unique=map(int,extract.group(1,2));edge_strings=extract.group(3).split();check(label+'-edges',len(edge_strings)==len(set(edge_strings))==unique==arcs)
 outcomes.append({'table':label,'actual_counters':parsed,'extraction_occurrences':occ,'distinct_graph_edges':arcs,'edge_strings':edge_strings,'bounded_counter_verdict':'PASS_NONEMPTY_COUNTERS_ZERO','derived_index_semantics':{'formula_source':'m5 lines61–63,68–73,77–80,98–104; arithmetic applied to actual logged58 vertices/closed counts','nonempty_size_1_to_3_seeds':eq,'empty_in_equality_loop':False,'all_size_0_to_3_would_be':eq+1,'union_split':'For each i<j<k, A={E[i]} and B={E[j],E[k]}; one partition only','anti_exchange_distinct_closed_states':closed,'anti_exchange_includes_empty':True,'anti_exchange_points':'Ordered distinct x,y outside A; not all58^2 pairs per state','generator_index_count':gen,'generator_distinct_nonempty_states':distinct,'generator_redundant_index_entries':gen-distinct,'unordered_index_pairs_with_repetition':pairs,'distinct_unordered_state_pairs_with_repetition':distinct*(distinct+1)//2,'empty_in_composition_loop':False},'historical_report_comparison':{'historical_graph_arc_count':13 if label=='LSTAR' else 16,'fresh_graph_arc_count':arcs,'historical_count_scope':'formal/v3/VERIFICATION.md216–259 text; historical execution is not relabelled','equality_union_anti_exchange_composition_and_principal_counts_match_historical_text':True}})
# Directly bind the independently inspected nearby operator definitions without executing them.
extra=[]
for rel in ['formal/v2/f8.mjs','viz/src/laws.ts']:
 p=R/rel;b=p.read_bytes();check('extra-git:'+rel,subprocess.check_output(['git','show',before['git_head']+':'+rel],cwd=R)==b);dest=O/'inputs'/rel;dest.parent.mkdir(parents=True,exist_ok=True)
 with dest.open('xb') as f:f.write(b)
 extra.append({**bind(p),'snapshot':str(dest.relative_to(R)),'role':'read_only_comparison_context_not_runtime_dependency'})
spans=[('formal/v3/m5-convex.mjs',3,23,'imports-and-extraction'),('formal/v3/m5-convex.mjs',25,47,'scc'),('formal/v3/m5-convex.mjs',49,64,'local-algorithms-and-equality-range'),('formal/v3/m5-convex.mjs',66,74,'union-range'),('formal/v3/m5-convex.mjs',76,90,'anti-exchange-range'),('formal/v3/m5-convex.mjs',92,111,'ex-alias-and-indexed-pairs'),('formal/v3/lib.mjs',1,28,'exports-used-versus-unused'),('formal/v2/tables.mjs',3,28,'root-read-and-element-order'),('formal/v2/tables.mjs',37,58,'parser'),('formal/v2/tables.mjs',86,99,'LSTAR-table'),('formal/v2/tables.mjs',173,193,'eager-corpus-reads'),('lean/Defialgebra/ConvexGeometry.lean',43,53,'intrinsic-ex-definition'),('lean/Defialgebra/ConvexGeometry.lean',195,207,'generic-reachSet'),('lean/Defialgebra/ConvexGeometry.lean',301,327,'generic-anti-exchange-and-ex-identification'),('lean/Defialgebra/ConvexGeometry.lean',502,558,'generic-composition-premises'),('paper/atlas.tex',952,960,'concrete-corollary'),('paper/atlas.tex',966,994,'composition-and-cost'),('formal/v3/VERIFICATION.md',216,259,'historical-run-text'),('formal/v2/f8.mjs',1,11,'separate-Cn-not-called'),('viz/src/laws.ts',148,170,'UI-closure-not-called')]
locators=[]
for rel,a,z,lid in spans:
 p=O/'inputs'/rel;b=p.read_bytes();lines=b.splitlines(keepends=True);check('locator-bounds:'+lid,1<=a<=z<=len(lines));span=b''.join(lines[a-1:z]);locators.append({'id':lid,'original_path':rel,'snapshot':bind(p),'start_line':a,'end_line':z,'byte_start':sum(map(len,lines[:a-1])),'byte_end_exclusive':sum(map(len,lines[:z])),'excerpt_sha256':h(span),'excerpt':span.decode()})
for path,digest in before['protected'].items():check('protected:'+path,h((R/path).read_bytes())==digest)
for row in before['sources']+extra:
 check('source-preserved:'+row['path'],h((R/row['path']).read_bytes())==row['sha256'] and h((R/row['snapshot']).read_bytes())==row['sha256'])
claims=[{'id':'HI01','assessment':'confirmed','claim':'Cn and reach are local algorithms sharing the same adjacency. This is a bounded consistency comparison, not a call to a separately shipped closure implementation.','locators':['local-algorithms-and-equality-range','imports-and-extraction','separate-Cn-not-called']},{'id':'HI02','assessment':'confirmed_with_limit','claim':'ex is defined as maxOf. The run does not independently compare intrinsic deletion-based extreme points with maximal elements. The composition identity remains a nontrivial bounded test; it is not merely syntactic equality.','locators':['ex-alias-and-indexed-pairs','intrinsic-ex-definition','generic-anti-exchange-and-ex-identification']},{'id':'HI03','assessment':'confirmed','claim':'Equality seeds cover exactly sizes1,2,3 and omit empty. Union tests one singleton/pair split of each sorted triple only. Anti-exchange does include empty and deduplicates closed states.','locators':['local-algorithms-and-equality-range','union-range','anti-exchange-range']},{'id':'HI04','assessment':'confirmed','claim':'Composition counts unordered generator-index pairs with repetition. Multiple generator indices can produce the same closed state; the logged closed pairs are not distinct state pairs.','locators':['ex-alias-and-indexed-pairs','anti-exchange-range']},{'id':'HI05','assessment':'confirmed','claim':'Mismatch/violation counters only print. No counter controls process.exitCode, throw or nonzero exit. This audit separately parses every expected nonempty block and zero violation counter.','locators':['local-algorithms-and-equality-range','union-range','anti-exchange-range','ex-alias-and-indexed-pairs']},{'id':'HI06','assessment':'additional_scope_guard','claim':'Extraction removes self-loops before SCC analysis, so its self-loops0 report is guaranteed by preprocessing and is not a check that original rules have no self-implications. Removing self-loops preserves reflexive-transitive reachability, so this does not by itself defeat the generic antisymmetry route.','locators':['imports-and-extraction','scc','generic-anti-exchange-and-ex-identification']},{'id':'HI07','assessment':'additional_dependency_guard','claim':'tables eagerly reads blind and lane corpora although m5 numerical computations only need E/LSTAR/PARSED_NEW and helpers. Bind those actual reads; do not infer untouched-holdout validation or whole-admissibility testing.','locators':['eager-corpus-reads','exports-used-versus-unused']},{'id':'HI08','assessment':'additional_operator_guard','claim':'The UI closureOf is depth-limited, follows every alternative and omits the seed from its reached set; it is not interchangeable with unary definite Cn. The separate f8 rule-saturation Cn is a closer candidate but is not called by m5. Both were inspected only, not executed.','locators':['UI-closure-not-called','separate-Cn-not-called']}]
result={'status':'BOUNDED_EXECUTION_PASS_CORRESPONDENCE_UNESTABLISHED','author':'Nonauthor GPT-6 stock Codex source reviewer; provider model telemetry unavailable','source_revision':before['git_head'],'execution':bind(O/'execution.json'),'dependency_inventory':bind(O/'before.json'),'additional_context':extra,'runtime_read_dependencies':8,'comparison_context_files':5,'actual_run':outcomes,'findings':claims,'locators':locators,'missing_correspondence':['Choose the exact concrete58-element vocabulary and law-table extraction; bind symbol/order/filter semantics to a finite Lean instance.','Identify the intended shipped closure function. Prove for every input its encoded result equals reachCl of the selected relation, rather than comparing two local helpers on bounded seeds.','Establish antisymmetry for that exact encoded relation, via a checked finite certificate or proof; source-scoped SCC output alone is not a Lean instance.','Bridge intrinsic ex(c,A) to executable maxOf under the same representation and reversed reachability order, then instantiate ex_reachCl and ex_oplus with their exact premises.','Keep algebraic set equality separate from the paper word-RAM cost model and any compiled implementation.'], 'limits':['No all2^58-subset execution or concrete Lean instance theorem was produced. A structural correspondence proof can discharge the universal bridge without enumeration.','No original outputs/corpus/source files changed; all88 S10 inputs remain bound and unchanged.','No native reviewer, Foreman orchestration, Lean build, new model implementation or historical generator mutation occurred. Node executable path includes a pre-existing .foreman tools directory; only the standalone Node binary was invoked.','Historical counts are compared to frozen report text, not independently reconstructed historical source/runtime identity.'],'checks':checks,'check_count':len(checks),'all_checks_passed':all(x['pass'] for x in checks),'protected_count':len(before['protected']),'s10_input_count':88,'created_utc':datetime.now(timezone.utc).isoformat()}
write(O/'audit.json',result);print(json.dumps({'checks':len(checks),'all_passed':True,'outcomes':outcomes,'audit_sha256':h((O/'audit.json').read_bytes())},indent=2))
