from pathlib import Path
import subprocess,json,hashlib
r=Path('/home/charl/defiformal');o=r/'review/semantic-kernel/sprint7/implementation';p='review/semantic-kernel/sprint7/';sha='bea105ec72e633a2dd66c663b96d0b552e1814a8'
source=['scripts/check_interleaving_mutations.py','scripts/test_interleaving_mutation_runner.py',p+'mutation-spec.json','lean/DefiKernel/AxiomAudit.lean']
source += ['lean/DefiKernel/Interleaving/'+f+'.lean' for f in ['Schedule','Execution','Examples','ScheduleTests','Tests','Audit','Verify','Completion','Trace','LocalOrder']]
source += ['openspec/changes/shared-state-interleaving/specs/interleaving-regression-evidence/spec.md']
evidence=[p+x for x in ['mutations/summary.json','mutations/source-manifest.json','mutations/results.json','mutations/driver-spec-git-bindings.json','mutations/REPORT.md','mutations/artifact-crosscheck.json','mutations/artifact-inventory.json','runner-controls/summary.json','runner-controls/REPORT.md','runner-controls/artifact-crosscheck.json','runner-controls/fixture-bundle-verification.json','regression-runs.json','regressions/source-binding.json','regressions/source-binding-after.json','regressions/REPORT.md','regressions/verified-outcomes.json','integration/lean-runs.json','integration/verification.json','integration-final/lean-runs.json','integration-final/verification.json','integration-final/01.log','integration-final/02.log','implementation/proof-supplement-binding.json','preservation.json','proof-inventory-driver.lean','proof-inventory-execution.json','coverage.md','coverage-validation.json','scenario-map.json','implementation/independent-artifact-check.md','implementation/independent-artifact-check.json']]
evidence += [str(x.relative_to(r)) for x in sorted((r/p/'mutations').glob('*.log'))]
missing=[f for f in source+evidence if not (r/f).is_file()]
if missing:raise SystemExit('Not ready: '+repr(missing))
parts=[f'''# Independent native Sprint 7 execution evidence and mutation runner review

Frozen source candidate: {sha}. Separate earlier native Lean review covers all generic semantics/proofs in lean-review-bundle.md (hash3b9a5e05bddc2f2ea32f37fdd55e70383972ef59ce3d7cef44fa715c90bcc2bf). This second scope includes the three new Completion.lean generic corollaries and its Verify import (the only changes since6de24fe), plus final mutation runner/harness, real execution evidence, classification, input/artifact binding and compliance with complete regression specification below. Author-supplied execution is not reviewer execution. User requires native Grok/Fable, stock GPT6 implementation, no Foreman. No previous reviewers' verdicts supplied.

Return substantive final ACCEPT / ACCEPT WITH LIMITATIONS / REQUEST CHANGES, exact material blockers and smallest fixes, limits and conclusions. Do not expose private chain of thought. Read-only source/evidence review; no independent Lean execution claimed unless actually performed. Do not modify any repository source or evidence. Native Grok previously used its automatic large-prompt offload and read-only source inspection despite --tools empty; exact bundle/source binding is the authority. The unchanged prior Lean source scope need not be re-reviewed; explicitly review and accept/reject the supplemental proofs and their new262theorem inventory along with the evidence scope. All25mutationclosure inputs and3driver/spec/harness files are byte-identical at both revisions; original runtime execution is not relabeled as a new run. Check the production runtime edit paths and independent oracles, all14 compiling mutants with designated false plus9 global protected true, unchanged116true control, complete unique nonempty inventory,52actualCLI runner control cases with correct blocked/violated classification, exact Git/SHA bindings, and current9legacy suites/12Leancommands. Full proof types remain in separate proof-inventory.json and the prior full Lean bundle; fresh summary and mapped statements are supplied here. Finite runtime tests, kernel proofs, compiler controls and advisory reviews are separate categories.

Some scenario statuses intentionally remain pending native review and delivery. Do not treat future acceptance as already happened. Frozen runtime/source files must not differ between runs and supplied Git candidate. Evidence files are fresh parent-generated artifacts and not falsely claimed as Git inputs at that candidate. Development failed attempts are retained separately and not counted as production detections. Native reviewer unavailable or timeout is pending, never a passing verdict. Threat model: mistakes and stale/misleading evidence, not an adversary replacing every code/log. Raw fixture Git metadata is preserved in audited archives/bundles rather than nested .git dirs. Financial fixtures are exact-rational development examples, no deployed refinement or liveness claim.
''']
items=[]
for f in source+evidence:
 data=(r/f).read_bytes();kind='fresh execution/evidence artifact'
 if f in source:
  assert subprocess.check_output(['git','show',sha+':'+f],cwd=r)==data,f
  kind='Git object at source candidate'
 items.append({'path':f,'sha256':hashlib.sha256(data).hexdigest(),'bytes':len(data),'binding':kind})
 parts.append(f'\n--- BEGIN {f} ---\n'+data.decode()+f'\n--- END {f} ---\n')
inv=json.loads((r/p/'proof-inventory.json').read_text());summary={k:v for k,v in inv.items() if not isinstance(v,list) or len(v)<20}
parts.append('\nProof inventory metadata (full inventory separately retained; omitted long declaration arrays):\n'+json.dumps(summary,indent=2)+'\n')
blob=''.join(parts).encode();(o/'evidence-review-bundle.md').write_bytes(blob);meta={'candidate':sha,'source_candidate':sha,'scope':'mutation runner, production execution and classification/bindings; source Lean review separate','bundle_sha256':hashlib.sha256(blob).hexdigest(),'bundle_bytes':len(blob),'files':items};(o/'evidence-review-candidate.json').write_text(json.dumps(meta,indent=2)+'\n');print(len(blob),len(items),meta['bundle_sha256'])
