from pathlib import Path
import json,hashlib,subprocess,datetime
r=Path(__file__).resolve().parents[4];o=Path(__file__).parent;old='a52fb748272fdc08f07d4ad8d2e2a06805b92dd6';new=subprocess.check_output(['git','rev-parse','HEAD'],cwd=r,text=True).strip();p='scripts/test_atomic_mutation_runner.py'
def sha(b):return hashlib.sha256(b).hexdigest()
def data(rev,path):return subprocess.check_output(['git','show',rev+':'+path],cwd=r)
changed=subprocess.check_output(['git','diff','--name-only',old,new],cwd=r,text=True).splitlines();assert changed==[p]
before=data(old,p);after=data(new,p);assert after==(r/p).read_bytes();assert after==before.replace(b'                log_path = result_path / (label + \'.log\')\n                actual_log = log_path.read_text() if log_path.exists() else \'\'',b'                lean_log_path = result_path / (label + \'.log\')\n                actual_log = lean_log_path.read_text() if lean_log_path.exists() else \'\'')
s=json.loads((o/'runner-controls-r4/summary.json').read_text());assert s['total']==s['passed']==65;assert s['git_head']==old and s['harness_sha256']==sha(after)
rows=[]
v=json.loads((o/'runner-controls-r3/summary.json').read_text())
for c in v['cases']:
 if not c['name'].startswith('production-eval-'):continue
 path=o/'runner-controls-r3'/(c['name']+'.log');b=path.read_bytes();assert sha(b)==c['log_sha256'] and b.decode()==c['cli_output'];assert sha((o/'runner-controls-r3/runs'/c['name']/'probe.log').read_bytes())==c['lean_observations']['probe']['log_sha256']
 rows.append({'case':c['name'],'original_incorrect_cli_log_pointer':c['log'],'correct_original_cli_log_pointer':'/tmp/sprint8-atomic-runner-controls-r3/'+c['name']+'.log','preserved_repo_cli_log':str(path.relative_to(r)),'cli_log_sha256':sha(b),'distinct_lean_probe_log_sha256':c['lean_observations']['probe']['log_sha256']})
report={'status':'PASS','checked_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'final_source_candidate':new,'kernel_execution_and_proof_candidate':old,'changed_paths':changed,'change':'Rename nested Lean log variable only, preventing overwriting outer CLI log path. No executor/Lean/spec/test predicate change.','old_harness_sha256':sha(before),'final_harness_sha256':sha(after),'all_other_tracked_git_bytes_equal':True,'equivalence_scope':'All Lean modules, toolchain and dependency pins, Atomic mutation driver/spec and old11 suite relevant inputs are unchanged from a52. Preserve original actual execution HEADs: Lean/proof/18production a52; legacy11 suites88aa via prior explicit equivalence; new65controls a52 with edited harness bytes now committed at final source. Production run captured old harness as provenance but did not execute it. The new harness is covered by fresh65controls. No old run is relabelled.','new_controls':{'path':str((o/'runner-controls-r4/summary.json').relative_to(r)),'sha256':sha((o/'runner-controls-r4/summary.json').read_bytes()),'actual_execution_head':s['git_head'],'total':65,'passed':65,'harness_equals_final_git_bytes':True},'historical_pointer_corrections':rows,'source_patch':subprocess.check_output(['git','diff',old,new,'--',p],cwd=r,text=True),'checker_sha256':sha(Path(__file__).read_bytes())}
(o/'log-pointer-fix-binding.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({k:x for k,x in report.items() if k not in ['source_patch','historical_pointer_corrections']},indent=2))
