from pathlib import Path
import datetime,json,hashlib,shutil,subprocess,os
r=Path('/home/charl/defiformal');b=r/'review/semantic-kernel/program-execution-20260908';o=b/'p32-readiness-preparation';o.mkdir(exist_ok=False);h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();read=lambda p:json.loads(p.read_text());write=lambda p,d:p.write_text(json.dumps(d,indent=2)+'\n');now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
groups={'evm':['forge','cast','anvil','solc','evm'],'solana':['solana','cargo-build-sbf','anchor','agave-validator','solana-test-validator'],'cosmos':['gaiad','osmosisd','wasmd','hermes'],'move-sui':['sui','aptos','move'],'sovereign-cross-chain':['polkadot','substrate','cardano-node','cardano-cli'],'payment-channel':['bitcoind','bitcoin-cli','lnd','lncli','lightningd','lightning-cli']}
lookups={k:{n:shutil.which(n) for n in ns} for k,ns in groups.items()};roots=[Path('/home/charl/.local/bin'),Path('/home/charl/.cargo/bin'),Path('/usr/local/bin'),Path('/home/charl/.cache/defiformal-program/program-execution-20260908/p16-tools')];names={n for ns in groups.values() for n in ns};directory_checks={str(p):[x.name for x in p.iterdir() if x.name in names] if p.is_dir() else None for p in roots};write(o/'tool-discovery.json',{'utc':now(),'method':'shutil.which on current process PATH plus exact-name directory entries in four known local tool roots','path':os.environ.get('PATH'),'which':lookups,'directory_checks':directory_checks,'scope':'Bounded local discovery only. Absence from these lookups does not establish absence throughout the machine or availability on the public network. Generic Rust/Go compilers are not evidence that a chain-specific toolchain is ready.'})
p16=r/'review/semantic-kernel/uniswap-token0/p16/implementation/grok-r6';pin=read(r/'openspec/changes/uniswap-token0-p16/source-pin.json');bindings={}
for f in pin['token0_closure']:
 p=r/pin['capture_root']/f['rel'];assert h(p)==f['sha256'],str(p);bindings[str(p.relative_to(r))]=h(p)
selected=['openspec/changes/uniswap-token0-p16/source-pin.json','review/semantic-kernel/program-execution-20260908/P16-SOURCE-ACCEPTANCE.md','review/semantic-kernel/program-execution-20260908/p16-source-r6-review/REVIEW.md','review/semantic-kernel/program-execution-20260908/p16-source-r6-integration.json','review/semantic-kernel/full-program-openspec-20260908/environment-scope-inputs.json','openspec/changes/reusable-verification-platform-program/tasks.md','openspec/changes/reusable-verification-platform-program/specs/certificates-adapters-evaluation-publication/spec.md']
for n in selected:bindings[n]=h(r/n)
for n in ['result.json','genesis/genesis-binding.json','genesis/istanbul-genesis.json','compiler/baseline/standard-json-input.json','logs/setup/solc-version/receipt.json','logs/setup/evm-version/receipt.json']:
 p=p16/n;bindings[str(p.relative_to(r))]=h(p)
write(o/'source-bindings.json',{'utc':now(),'files':bindings,'p16_original_source_pin_status':'Historical captured_not_executed flags retained; later P16-SOURCE-ACCEPTANCE.md separately records accepted scoped execution.','source_plan_scope':'Existing requirement excerpt only; no new assessment case or held payload selected/read.'})
commands=[]
for name in ['solc','evm']:
 prior=read(p16/f'logs/setup/{name}-version/receipt.json');tool=Path(prior['tool']['resolved']);assert h(tool)==prior['tool']['sha256'];argv=[str(tool),'--version'];start=now();res=subprocess.run(argv,cwd=r,capture_output=True,timeout=30);(o/f'{name}-version.stdout').write_bytes(res.stdout);(o/f'{name}-version.stderr').write_bytes(res.stderr);rec={'argv':argv,'cwd':str(r),'started_utc':start,'finished_utc':now(),'exit':res.returncode,'tool_sha256':h(tool),'stdout_sha256':h(o/f'{name}-version.stdout'),'stderr_sha256':h(o/f'{name}-version.stderr'),'stdout':res.stdout.decode(),'matches_historical_p16_tool_sha256':True,'scope':'Fresh version command only; no new compilation or financial execution'};commands.append(rec);assert res.returncode==0
write(o/'commands.json',commands)
result=read(p16/'result.json');genesis=read(p16/'genesis/genesis-binding.json');settings=read(p16/'compiler/baseline/standard-json-input.json')['settings'];records=[]
for index,(env,toolnames) in enumerate(groups.items(),1):
 rec={'schema':'defiformal-p32-environment-readiness-draft/v1','utc':now(),'environment':env,'task':f'33.{index}','authorship':'Root administrative evidence preparation; no AGY implementation or Grok review claimed','independent_review':'pending','readiness_accepted':False,'p34_execution_accepted':False,'new_execution_cases':0,'tool_discovery':'tool-discovery.json','source_bindings':'source-bindings.json'}
 if env=='evm':
  rec.update(status='scoped_local_harness_available',implementation=pin['helper'],source_pin=pin['pin'],source_closure_hashes_verified=len(pin['token0_closure']),toolchains=commands,compile_settings=settings,execution_environment={'fork':genesis['selected_fork'],'genesis_sha256':genesis['sha256'],'prestate_supplied':genesis['prestate_supplied'],'number':genesis['number'],'time':genesis['time'],'sender':genesis['sender'],'receiver':genesis['receiver'],'gasLimit':genesis['gasLimit']},deployment={'kind':'local deterministic helper harness','runtime_bytecode_sha256':result['compile']['runtime_bytecode_sha256'],'mainnet_address_verified':False,'mainnet_deployment_identity':None},historical_accepted_evidence='P16-SOURCE-ACCEPTANCE.md: twelve selected token0 source comparisons and six compiled mutations; historical evidence, not new P32/P34 runs',remaining=['Independent review of this P32 readiness record','Any selected deployed contract requires its own verified address/code/environment binding','P34 requires new nonempty success/refusal on frozen evaluated APIs after P33; prior token0 evidence scores only its scoped EVM function'])
 else:
  rec.update(status='blocked_unavailable',verified_source_pin=None,verified_deployment=None,verified_toolchain=None,discovery_names=toolnames,block_reason='No verified source/deployment/toolchain binding for this environment is supplied by the current P32 preparation; named tools were not found by the bounded local discovery.',scope_limit='This is a missing-readiness-evidence record, not a claim that the protocol or toolchain does not exist or cannot be installed.',unblock_requirements=['Select and pin an implementation and source commit through the P32 source gate','Acquire or locate and verify the chain-specific compiler/runtime and exact version','Bind relevant local execution/deployment configuration','Independent review under task33.7; preserve later P33 freeze and P34 untouched-case selection'],remaining=['Actual nonempty success and refusal against frozen APIs in P34'])
 write(o/f'{env}.json',rec);records.append({'environment':env,'task':rec['task'],'path':f'{env}.json','status':rec['status'],'acceptance':False})
write(o/'readiness-index.json',{'utc':now(),'records':records,'task33_7_review':'pending','full_p32_accepted':False,'full_p34_accepted':False,'whole_program_complete':False})
(o/'README.md').write_text('''# P32 environment readiness preparation

Six draft records cover the six environments required by tasks33.1–33.6. They await independent task33.7 review. Root prepared administrative source/tool bindings; no new implementation or acceptance is claimed.

The EVM record binds the accepted P16 Uniswap token0 source pin, seven unchanged source files, Solidity0.7.6 optimizer800/Istanbul settings, actual Istanbul genesis/prestate and local helper bytecode. Fresh absolute-path version commands match the pinned Solidity and geth EVM binaries. No mainnet deployment identity or new financial execution is claimed.

The other five records explicitly lack verified source/deployment/toolchain bindings. Named tools were not found on PATH or by exact-name checks in the recorded local roots. This is bounded discovery, not a whole-machine absence proof. These records identify the evidence needed to proceed and do not close P34.

No untouched assessment case was selected or read. P34 still requires nonempty success and refusal execution in every required environment against APIs frozen under P33. Historical token0 results provide no coverage for other environments.
''')
shutil.copy2(__file__,o/'capture.py');write(o/'root-seal.json',{'utc':now(),'files':{str(p.relative_to(o)):h(p) for p in sorted(o.iterdir()) if p.is_file()},'source_binding_count':len(bindings),'six_records':True,'independent_review':'pending','acceptance':False});print(json.dumps({'records':records,'source_bindings':len(bindings),'fresh_version_commands':len(commands),'acceptance':False}))
