from pathlib import Path
import hashlib,json,subprocess,datetime
repo=Path('/home/charl/defiformal');base=repo/'review/semantic-kernel/sprint8';out=base/'final-review';out.mkdir(exist_ok=True)
sha=subprocess.check_output(['git','rev-parse','HEAD'],cwd=repo,text=True).strip();assert sha=='99e2e2c61a1a3c5249026921efdc6cd41ac8f21d'
old=json.loads((base/'implementation/lean-review-candidate.json').read_text())
paths=[Path(x['path']) for x in old['inputs']]
extra=['implementation/build-log-pointer-fix-binding.py','implementation/log-pointer-fix-binding.json','implementation/log-pointer-fix-independent.json','implementation/log-pointer-fix-independent.md','final-review/build-review-inventory.py','final-review/proof-inventory-review.json','proof-inventory-execution.json','integration-final/verification.json','integration-final/lean-runs.json','integration-final/01.stdout.log','mutations/REPORT.md','mutations/results.json','mutations/summary.json','mutations/final-manifest.json','mutations/artifact-crosscheck.json','mutations/artifact-inventory.json','implementation/runner-controls-r4/REPORT.md','implementation/runner-controls-r4/summary.json','implementation/runner-controls-r4/artifact-crosscheck.json','regression-runs.json','regressions/README.md','final-review/regression-outcomes-review.json','regressions/verify-results.py','implementation/ADJUDICATION-r1.md','implementation/lean-fable.md','implementation/lean-grok.md','implementation/review-summary-r1.json','implementation/independent-artifact-check.json','implementation/independent-artifact-check.md']
extra+=['implementation/legacy-dependency-equivalence.json', 'implementation/legacy-dependency-equivalence.py', 'implementation/legacy-dependency-equivalence.md', 'scenario-to-evidence.json', 'scenario-coverage.json', 'evidence-summary.json', 'EVIDENCE.md', 'final-scenario-artifact-inventory.json']
paths += [Path('review/semantic-kernel/sprint8')/x for x in extra]
paths += [Path('AGENTS.md'),Path('review/semantic-kernel/reviewer-transition-2026-09-07/policy.json')]
paths=list(dict.fromkeys(paths))
header=f'''Audit revised Sprint8 Atomic source AND final execution/evidence at frozen Git {sha}. Return a SUBSTANTIVE PLAIN-TEXT FINAL beginning VERDICT: ACCEPT, ACCEPT WITH LIMITATIONS, or REVISE, followed by BLOCKERS, REQUIRED CHANGES, NONBLOCKING LIMITATIONS and CLAIM/SCOPE CHECK. No tool markup/XML. Read the supplied full source and evidence; no edits or external communication, no Foreman. Do not claim independent command execution. This is a new native audit, not an instruction to endorse author reports. The user explicitly changed future Fable reviews to native Opus. Grok and Opus must independently review this same final candidate; older Fable requirements are superseded only in reviewer identity, with historical Fable reports preserved.

Initial88aa source review: native Fable REVISE for real Audit list/count protocol mismatch, independently observed as a blocked first production mutant. Grok ACCEPT WITH LIMITATIONS missed that defect. The actual a52 revision changes production Audit to failures.length, adds6 runtime checks for competing policy and lane-supply failure precedence,2 real production #eval/IO.userError runner controls, and2 comment corrections. Check B1 and R1/R2/R3 closure against actual source/output, preserve dissent. No old blocked result counted as a detection.

Current executed counts:14 fresh Lean commands pass at a52;135 unique Atomic runtime comparisons all true;357 imported theorem and496 supplemental forbidden-axiom checks with0 forbidden;106 explicit declarations (93 generic,9 reference instances,3 counterexamples,1 counterexample corollary),2 private helpers included,251 generated. All18 actual production mutants compiled at a52,19 designated false checks total,135 complete comparisons each,6 protected positives each. Omitting final lane and final participant have identical8-false inventories: detected interventions, not fault identification.65 actual synthetic CLI controls =52 established+11 proof-tail+2 production-form. The earlier r3 run executed at88aa with edited a52 harness bytes. Independent reconciliation found2 incorrect CLI log pointers caused by a local variable being overwritten. Final source99e2e2c changes only that nested log variable, and a fresh r4 run passes all65 at actual HEADa52 with edited harness bytes equal to99e2e2c. Every CLI path now resolves to exact output/hash. All kernel/modules/toolchain/production driver/spec bytes are unchanged a52->99; the original14 Lean/proof/18production results retain actual a52 identity via exact Git tree equivalence. Do not claim a kernel or production rerun at99, or count old and new controls twice.11 fresh legacy suites executed at88aa, with explicit relevant dependency equivalence to a52, not claimed rerun at a52. Proof, finite kernel instances, actual runtime, compiler negatives, mutation evidence, synthetic harness controls and advisory review are distinct.

49 normative scenarios mapped; native acceptance and branch delivery entries intentionally remain pending until actual reviews and push/archive. Task checkboxes are still historical preacceptance state; source/evidence obligations determine substantive completion. Review/delivery cannot be evidence inputs to their own review. Evaluate whether all substantive Sprint8 obligations are met and source correction plus final evidence warrant acceptance for delivery. Check exact source linkage, actual-prefix signed receipt conservation even successful policyabort, allkey settlement, noncircular converse, full rollback, point-of-use capabilities, frame/invariant premises, exact public projection, independent expectations, complete and nonempty inventories, actual mutation projections, drift/hashes/model identities and accurate limitations. The full saved inventory is hash-bound. The supplied review projection preserves all106 explicit elaborated/source theorem statements and lists all generated/supplemental identities, sources, axioms and statement hashes; expanded generated/supplemental types are omitted from this prompt, not absent from the saved evidence. No runtime count is inferred from declaration count. No deployed Balancer fidelity, machine arithmetic, dynamic provenance, general associativity, security-type hiding of diagnostics, fairness or arbitrary command macro safety is claimed. All author prose is an untrusted claim to inspect against supplied source and records. Explicitly state any missing decisive evidence or normative blocker, with precise location and concrete consequence.\n'''
parts=[header];rows=[]
for p in paths:
 data=(repo/p).read_bytes();h=hashlib.sha256(data).hexdigest();row={'path':p.as_posix(),'sha256':h,'bytes':len(data)}
 if p in [Path(x['path']) for x in old['inputs']]:
  assert subprocess.check_output(['git','show',f'{sha}:{p.as_posix()}'],cwd=repo)==data,p
  row['git_blob']=subprocess.check_output(['git','rev-parse',f'{sha}:{p.as_posix()}'],cwd=repo,text=True).strip()
 rows.append(row);parts.append(f'\n\n===== INPUT {p.as_posix()} SHA256 {h} =====\n'+data.decode())
b=''.join(parts).encode();(out/'bundle.md').write_bytes(b)
m={'candidate':sha,'kind':'native revised source and final evidence review; no independent execution claimed','captured_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'inputs':rows,'input_count':len(rows),'bundle_bytes':len(b),'bundle_sha256':hashlib.sha256(b).hexdigest()};(out/'candidate.json').write_text(json.dumps(m,indent=2)+'\n');print(json.dumps({k:v for k,v in m.items() if k!='inputs'},indent=2))
