from pathlib import Path
import json,hashlib
out=Path(__file__).parent;r=out.parents[3];full=r/'review/semantic-kernel/sprint8/proof-inventory.json';v=json.loads(full.read_text())
def sha(b):return hashlib.sha256(b).hexdigest()
explicit=[{k:x[k] for k in ['name','statement','axioms','source','line','category','private'] if k in x} for x in v['theorems'] if x['declaration_origin']=='explicit'];assert len(explicit)==106
sources=sorted({x['source'] for x in v['theorems']+v['supplemental']});axioms=sorted({tuple(x['axioms']) for x in v['theorems']+v['supplemental']})
def row(x):return [x['name'],sources.index(x['source']),axioms.index(tuple(x['axioms'])),sha(x['statement'].encode())]
w={'full_inventory_path':str(full.relative_to(r)),'full_inventory_sha256':sha(full.read_bytes()),'candidate':v['candidate'],'counts':v['counts'],'source_bindings':v['source_bindings'],'explicit_theorems':explicit,'nonexplicit_columns':['name','source_index','axiom_set_index','full_statement_sha256'],'sources':sources,'axiom_sets':axioms,'generated_theorems':[row(x) for x in v['theorems'] if x['declaration_origin']!='explicit'],'supplemental':[row(x) for x in v['supplemental']],'scope':'All106 explicit fully elaborated statements retain all premises; source context is in complete supplied Lean modules. All251 generated and496 supplemental identities/axioms/source/type hashes retained. Repeated source-context text and expanded generated/supplemental types omitted from prompt only; complete original inventory saved unchanged.'}
p=out/'proof-inventory-opus.json';p.write_text(json.dumps(w,separators=(',',':'),ensure_ascii=False)+'\n')
m=json.loads((out/'candidate.json').read_text());header=(out/'bundle.md').read_text().split('\n\n===== INPUT ',1)[0]
header+='\n\nOPUS PRESENTATION: The two earlier Opus attempts exceeded the context limit and are not audits. This prompt retains all complete Lean/source/plan/driver code and execution reports from the original candidate. The proof-inventory review projection is losslessly normalized for all106 explicit elaborated statements (including premises), every generated/supplemental declaration identity, axiom set, source and full-type hash. Repeated source-context text is supplied once in full Lean source rather than again in each theorem row. Generated/supplemental expanded types remain in the same hash-bound full inventory. JSON presentation is compact; actual original input and rendered hashes are recorded separately. Grok reviews the more verbose presentation of the same underlying source/evidence, not an earlier source candidate.\n'
parts=[header];rows=[]
for x in m['inputs']:
 if x['path']=='review/semantic-kernel/sprint8/final-review/proof-inventory-review.json':x={'path':str(p.relative_to(r)),'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size}
 data=(r/x['path']).read_bytes();assert sha(data)==x['sha256'];render=data
 if x['path'].endswith('.json'):render=json.dumps(json.loads(data),separators=(',',':'),ensure_ascii=False).encode();assert json.loads(render)==json.loads(data)
 y={**x,'rendered_sha256':sha(render),'rendered_bytes':len(render)};rows.append(y);parts.append(f'\n\n===== INPUT {x["path"]} ORIGINAL_SHA256 {x["sha256"]} RENDERED_SHA256 {y["rendered_sha256"]} =====\n'+render.decode())
b=''.join(parts).encode();(out/'bundle-opus.md').write_bytes(b);m.update(inputs=rows,bundle_bytes=len(b),bundle_sha256=sha(b),presentation='Compact JSON with normalized proof inventory; complete106 explicit elaborated statements and full source retained',underlying_full_proof_inventory_sha256=sha(full.read_bytes()),grok_bundle_sha256=sha((out/'bundle.md').read_bytes()));(out/'candidate-opus.json').write_text(json.dumps(m,indent=2)+'\n');print('proof projection',p.stat().st_size,'bundle',len(b),sha(b))
