import DefiKernel.Arithmetic.Rounding

#print axioms DefiKernel.Arithmetic.Rounding.floor_characterization
#print axioms DefiKernel.Arithmetic.Rounding.ceil_characterization
#print axioms DefiKernel.Arithmetic.Rounding.divideNat_error_iff
#print axioms DefiKernel.Arithmetic.Rounding.divideNat_down_ok_iff
#print axioms DefiKernel.Arithmetic.Rounding.divideNat_up_ok_iff
#print axioms DefiKernel.Arithmetic.Rounding.divideNat_le
#print axioms DefiKernel.Arithmetic.Rounding.divideNat_exists_iff
#print axioms DefiKernel.Arithmetic.Rounding.divideNat_zero_denominator
#print axioms DefiKernel.Arithmetic.Rounding.divideNat_zero
#print axioms DefiKernel.Arithmetic.Rounding.divideNat_exact
#print axioms DefiKernel.Arithmetic.Rounding.divideNat_up_zero_iff
#print axioms DefiKernel.Arithmetic.Rounding.divideNat_rounding_gap
#print axioms DefiKernel.Arithmetic.Rounding.divideNat_equal_iff_dvd
#print axioms DefiKernel.Arithmetic.Rounding.divideNat_mono
#print axioms DefiKernel.Arithmetic.Rounding.divideNat_down_rational_error
#print axioms DefiKernel.Arithmetic.Rounding.divideNat_up_rational_error
#print axioms DefiKernel.Arithmetic.Rounding.mulDiv_ok_iff
#print axioms DefiKernel.Arithmetic.Rounding.mulDiv_down_ok_iff
#print axioms DefiKernel.Arithmetic.Rounding.mulDiv_up_ok_iff
#print axioms DefiKernel.Arithmetic.Rounding.mulDiv_error_iff
#print axioms DefiKernel.Arithmetic.Rounding.mulDiv_exists_iff
#print axioms DefiKernel.Arithmetic.Rounding.mulDiv_zero_denominator
#print axioms DefiKernel.Arithmetic.Rounding.mulDiv_error_cases
#print axioms DefiKernel.Arithmetic.Rounding.mulDiv_quotientOverflow_iff
#print axioms DefiKernel.Arithmetic.Rounding.mulDiv_mono_left
#print axioms DefiKernel.Arithmetic.Rounding.mulDiv_mono_right
#print axioms DefiKernel.Arithmetic.Rounding.mulDiv_down_error_iff
#print axioms DefiKernel.Arithmetic.Rounding.mulDiv_up_error_iff
#print axioms DefiKernel.Arithmetic.Rounding.mulDiv_divisionByZero_iff
#print axioms DefiKernel.Arithmetic.Rounding.mulDiv_zero_left
#print axioms DefiKernel.Arithmetic.Rounding.mulDiv_zero_right
#print axioms DefiKernel.Arithmetic.Rounding.mulDiv_width_zero
#print axioms DefiKernel.Arithmetic.Rounding.mulDiv_exact_iff
#print axioms DefiKernel.Arithmetic.Rounding.mulDiv_rounding_gap
#print axioms DefiKernel.Arithmetic.Rounding.mulDiv_equal_iff_dvd
#print axioms DefiKernel.Arithmetic.Rounding.mulDiv_down_rational_error
#print axioms DefiKernel.Arithmetic.Rounding.mulDiv_up_rational_error
#print axioms DefiKernel.Arithmetic.Rounding.mulDiv_up_value_zero_iff
