from pathlib import Path
import collections,datetime,hashlib,json,re,shutil,gzip,tarfile
B=Path('/home/charl/defiformal/review/semantic-kernel/program-execution-20260908');W=Path('/home/charl/defiformal-wt-p19-certificates-grok-opus-20260909');E=W/'review/semantic-kernel/certificates/p19/implementation/agy-r24-proof';O=B/'p19-r24-root-scope-attempt2';now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat();h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();read=lambda p:json.loads(p.read_text())
def put(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
assert not Path('/proc',str(read(B/'p19-roundtrip-proof-agy-r24-dispatch.json')['pid'])).exists()
O.mkdir(exist_ok=False);shutil.copy2(__file__,O/'verify.py');m=read(B/'p19-roundtrip-proof-agy-r24-terminal-manifest.json');prev=read(B/'p19-roundtrip-proof-agy-r23-terminal-manifest.json');old={r['path']:r['sha256'] for r in prev['files']}
assert h(B/m['archive'])==m['sha256']
for row in m['files']:assert h(W/row['path'])==row['sha256'],row['path']
rows=read(E/'commands.json');assert len(rows)==62 and len({r['id'] for r in rows})==62;origin=collections.Counter();codes=collections.Counter();finals=[]
final={r['path']:r['sha256'] for r in m['files'] if r['path'].startswith('lean/DefiKernel/Certificates/')}
for row in rows:
 assert read(E/'logs'/row['id']/'command.json')==row,row['id'];assert h(E/row['stdout_path'])==row['stdout_sha256'] and h(E/row['stderr_path'])==row['stderr_sha256'];assert row['finished_utc']>=row['started_utc'];origin[row['origin']]+=1;codes[str((row['origin'],row['exit']))]+=1
 if all(final.get(p)==d for p,d in row['source_sha256_after'].items()) and all(final.get(p)==d for p,d in row['source_sha256_before'].items()):finals.append({'id':row['id'],'exit':row['exit'],'argv':row['argv']})
source=read(E/'source-manifest.json')
for p,row in source['sources'].items():assert h(W/p)==row['sha256'] and (W/p).stat().st_size==row['bytes'],p
manifest=read(E/'MANIFEST.json')
manifest_mismatches=[{'path':row['path'],'claimed_sha256':row['sha256'],'actual_sha256':h(W/row['path'])} for row in manifest['files'] if h(W/row['path'])!=row['sha256']]
inv=read(B/'p19-r24-root-inventory/command.json');assert inv['theorem_lemma_total']==578 and inv['exact_names_match'] and inv['forbidden']==[]
text=(W/'lean/DefiKernel/Certificates/Roundtrip.lean').read_text();signature=text[text.index('theorem decodeBytes_encodeModule_of_depth'):text.index('end DefiKernel.Certificates',text.index('theorem decodeBytes_encodeModule_of_depth'))];(O/'actual-final-theorem.txt').write_text(signature)
changed=[r for r in m['files'] if old.get(r['path'])!=r['sha256'] and r['path'].startswith('lean/')];assert len(changed)==1 and changed[0]['path'].endswith('/Roundtrip.lean')
with tarfile.open(B/prev['archive']) as t: prior=t.extractfile('lean/DefiKernel/Certificates/Roundtrip.lean').read().decode()
def signatures(s):return {a:b.strip() for a,b in re.findall(r'^(?:theorem|lemma)\s+(\S+)(.*?)(?=\s:=)',s,re.M|re.S)}
old_s=signatures(prior);new_s=signatures(text);assert all(new_s.get(n)==s for n,s in old_s.items());assert len(old_s)==102 and len(new_s)==130
native=gzip.open(B/'p19-roundtrip-proof-agy-r24-native.jsonl.gz','rt').read().splitlines();attribution=[]
for n,line in enumerate(native,1):
 if 'root-control-success-24' in line or 'root-control-failure-25' in line: attribution.append({'line':n,'event':json.loads(line)})
assert attribution;put(O/'native-control-attribution.json',attribution)
result={'utc':now(),'candidate_archive_sha256':m['sha256'],'candidate_files':len(m['files']),'new_files':sum(r['path'] not in old for r in m['files']),'changed_production_sources':changed,'all_other_previous_sources_unchanged':True,'previous_102_theorem_signatures_preserved':True,'new_theorems':sorted(set(new_s)-set(old_s)),'command_records_verified':62,'raw_streams_verified':124,'recorded_origin_labels':dict(origin),'exit_counts_by_recorded_origin':dict(codes),'actual_attribution':'All 62 recorded commands occurred during AGY R24. The two root_preflight-labelled controls were invoked by AGY, not root; native-control-attribution.json preserves native events. Labels do not establish actor identity.','commands_bound_to_final_certificate_sources':finals,'author_source_manifest_bindings_verified':len(source['sources']),'author_manifest_bindings_verified':len(manifest['files'])-len(manifest_mismatches),'author_manifest_mismatches':manifest_mismatches,'root_explicit_inventory':inv,'strongest_new_result':'moduleToTreeJson_valid derives TreeJson.Valid from existing StructurallyAdmissibleIR. Direct world/libraryRef decoder inverses also added. Final byte theorem still assumes whole tree depth, semantic decoder success and lexical scanner success.','scope':'Partial production proof progress; fresh independent review pending.','author_report_corrections':['Verify.lean is unchanged from R23; only Roundtrip.lean changed.','TreeJson.Valid requires recursive validity, array bounds and distinct object keys; it does not require every object field list to be sorted. Preserve actual encoder declaration order.','Actual build target is DefiKernel.Certificates.Verify (938 jobs), not full DefiKernel.','MANIFEST lists 10 files, but commands.json digest is stale and raw streams/probes are omitted. Root terminal archive binds actual frozen files. Failed initial root verifier preserved separately.','Two root_preflight labels are author-generated controls, not root runs. Root recorder content unchanged; author changed executable mode only.','99 scenario status mappings are not proof of 99 acceptance obligations. Existing overlay/hash/schema/expectedIR/host and 16-mutant requirements remain open.','Author auditor field names requested future Grok only; R24 independent verdict is pending.'],'next_author':['Finish actual declaration-order TreeJson semantic decoding through envelope/typed/step/run/module.','Derive whole TreeJson depth and actual lexical scan success from faithful existing domain.','Prove EncodeDecodeRoundtripStatement without desired-success/image premises or arbitrary string/rational caps.','Continue all remaining P19 campaigns and full roadmap; preserve historical evidence and exact signatures.'],'P19_accepted':False,'whole_program_complete':False}
put(O/'scope.json',result);put(B/'p19-roundtrip-proof-agy-r24-root-precheck.json',result);put(O/'root-seal.json',{'utc':now(),'files':{p.name:h(p) for p in O.iterdir() if p.is_file()},'acceptance':False});print(json.dumps({'files':len(m['files']),'new_files':result['new_files'],'new_theorems':len(result['new_theorems']),'commands':len(rows),'manifest_bindings':len(manifest['files']),'P19_accepted':False}))
