from pathlib import Path
import json,hashlib,datetime,gzip,shutil
r=Path('/home/charl/defiformal');b=r/'review/semantic-kernel/program-execution-20260908';o=b/'p31-runtime-preparation-grok-r1';c=o/'closeout';h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();read=lambda p:json.loads(p.read_text());write=lambda p,d:p.write_text(json.dumps(d,indent=2)+'\n');now=datetime.datetime.now(datetime.timezone.utc).isoformat();p=read(o/'process.json');cp=read(c/'process.json');assert p['process_exit']==1 and cp['process_exit']==0;assert p['sessions']==cp['sessions'];assert not Path('/proc/1789331').exists();assert h(o/'native.jsonl')==p['log_sha256'] and h(c/'native.jsonl')==cp['log_sha256'];inputs=read(o/'inputs.json');s=Path(inputs['sandbox'])
for n,v in inputs['files'].items():assert h(s/n)==v,n
m=read(c/'MANIFEST.json');paths=set()
for n,v in m['files'].items():
 q=(c/n).resolve();assert q.is_relative_to(o);assert h(q)==v,n;paths.add(q)
for n in ['REVIEW.md','verdict.json','findings.json','commands.json']:assert (c/n).read_bytes()==(o/n).read_bytes()
commands=read(c/'commands.json')
for n,v in commands['output_hashes'].items():assert h(o/n)==v,n
for key,path in {'node':'/home/charl/.foreman/tools/fnm/node-versions/v24.18.1/installation/bin/node','compactc.bin':'/home/charl/.compact/versions/0.31.1/x86_64-unknown-linux-musl/compactc.bin','compact_launcher':'/home/charl/.local/bin/compact','typescript.js_5.9.3':'/home/charl/.cache/defiformal-program/program-execution-20260908/p31-import-scanner-tool/node_modules/typescript/lib/typescript.js'}.items():assert h(Path(path))==commands['tool_hashes'][key]
comparisons={}
for label,expected,actual in [('simulation_stdout',s/'p31-source-closure/simulation.stdout.json',o/'replay/source-closure/simulation.stdout.json'),('simulation_stderr',s/'p31-source-closure/simulation.stderr.log',o/'replay/source-closure/simulation.stderr.log'),('compact_stdout',s/'p31-compact-add-diagnostic/runtime.stdout.json',o/'replay/compact-add/runtime.stdout.json'),('compact_stderr',s/'p31-compact-add-diagnostic/runtime.stderr.log',o/'replay/compact-add/runtime.stderr.log')]:comparisons[label]={'exact_bytes_match':expected.read_bytes()==actual.read_bytes(),'captured_sha256':h(expected),'reviewer_sha256':h(actual)}
assert comparisons['simulation_stdout']['exact_bytes_match'] and comparisons['compact_stdout']['exact_bytes_match'] and comparisons['compact_stderr']['exact_bytes_match'];assert 'NO_COLOR' in (o/'replay/source-closure/simulation.stderr.log').read_text();assert read(o/'replay/verification.json')['simulation']['semantic_match']
tool=read(s/'p31-compact-add-diagnostic/tool-inputs.json');nm=Path('/home/charl/.cache/defiformal-program/program-execution-20260908/p31-compact-runtime-tool/node_modules')
for n,v in tool['runtime_files'].items():assert h(nm/n)==v,n
with (c/'native.jsonl.gz').open('xb') as out:
 with gzip.GzipFile(filename='',mode='wb',fileobj=out,mtime=0) as z:z.write((c/'native.jsonl').read_bytes())
shutil.copy2('/tmp/defiformal-p31-runtime-preparation-grok-closeout.py',o/'closeout-launcher.py');shutil.copy2(__file__,o/'root-verify.py')
write(o/'root-adjudication.json',{'schema':'defiformal-p31-root-adjudication/v1','utc':now,'decision':'usable_scoped_runtime_source_preparation','requested_model':'grok-4.6','reported_models':cp['reported_models'],'session':cp['sessions'][0],'initial_exit':1,'initial_stop':'max14turns','same_session_closeout_exit':0,'frozen_inputs_verified':len(inputs['files']),'review_manifest_paths_verified':len(m['files']),'command_output_hashes_verified':len(commands['output_hashes']),'tool_hashes_verified':4,'runtime_package_files_unchanged':len(tool['runtime_files']),'raw_output_comparisons':comparisons,'metadata_note':'verification.json simulation.stdout_bytes_match combines stdout AND stderr equality. Root records channels separately: stdout exact, stderr differs only by recorded Node FORCE_COLOR/NO_COLOR warning. commands.json brief-sha256 stdout_sha256 is the brief content digest, not a hash of the sha256sum output line; no stdout-hash credit for that field.','scope':'20-file static source closure plus3 exact upstream example inputs;4 simulation actions with adverse and missing-backend controls;5 generated Compact checkedAdd calls. Original root compile and reviewer runtime replay are separate evidence.','resolves_for_bounded_scope':['Missing frontend/registered bounds capture for the two examples','Observed addition overflow rejection under Compact0.31.1/runtime0.16.0'],'remaining':['Choose exact adapter profile','General semantic/Lean correspondence and actual adapters','ZKIR artifact contract and constraints','Accepted P20 before certificate consumption'],'readiness_tasks_accepted':False,'full_P31_accepted':False,'acceptance':False})
for n in ['dispatch.json','inputs.json','brief.txt','process.json','REVIEW.md','verdict.json','findings.json','commands.json','attempt1-terminal-seal.json','attempt1-native.jsonl.gz','closeout-launcher.py','root-verify.py','root-adjudication.json']:paths.add(o/n)
for n in ['brief.txt','dispatch.json','process.json','MANIFEST.json','CLOSEOUT.md','native.jsonl.gz','native.stderr']:paths.add(c/n)
write(o/'root-seal.json',{'schema':'defiformal-root-review-seal/v1','utc':now,'files':{str(p.relative_to(o)):h(p) for p in sorted(paths)},'file_count':len(paths),'disposition':'usable_scoped_runtime_source_preparation','acceptance':False});print(json.dumps({'sealed_files':len(paths),'inputs_verified':len(inputs['files']),'runtime_files_unchanged':len(tool['runtime_files']),'stdout_replays_exact':True}))
