import json
from pathlib import Path
p=Path(__file__).parent
configs=[
{'folder':'spark-savings-cross-domain','unit':'unit:lane2:c1:p1','name':'Spark Savings (sUSDS / Sky Savings Rate)','ids':['dispute-15'],'dispositions':{'async_cross_domain':'not_evidenced'},
'spans':[('user-actions','ethereum-savings','- `USDS <-> sUSDS`: sUSDS ERC-4626 interface','line'),('user-actions','non-ethereum','## Non-Ethereum chains','mdsection'),('psm','swap-service','The PSM contract allows users','line'),('psm','rate-provider','The conversion between a stablecoin','line'),('psm','l2-token','- **`susds`**:','line')],
'claims':[
('async_cross_domain','source_statement','Pinned Spark repository documentation distinguishes Ethereum savings-token entry from non-Ethereum PSM swaps.',['user-actions:ethereum-savings','user-actions:non-ethereum']),
('async_cross_domain','source_statement','The PSM source documentation describes local swaps and a conversion-rate provider, and distinguishes its sUSDS ERC20 from the mainnet ERC4626 interface.',['psm:swap-service','psm:rate-provider','psm:l2-token']),
('async_cross_domain','bounded_evidence_gap','These paths do not establish an initiating transition, delivery/finality condition and consequent destination transition for one scoped savings workflow. The multi-chain execution label remains not_evidenced.',['user-actions:non-ethereum','psm:rate-provider'])],
'limits':['The official savings URL returned404 twice; no page body or search text is substituted.','Both retained READMEs are pinned to actual Git revisions resolved in this packet. Their statements are documentation, not executed contract behavior.','Local PSM liquidity, sUSDS balances and a rate provider do not establish a bridge or relay. The wider Spark Liquidity Layer and Sky collateral system are distinct dependencies.','No eight-chain count, cross-chain sameness, specific source/destination pair, token bridge, oracle delivery implementation, deployment or historical correspondence was established.'],
'next':'Retrieve a particular savings bridge or rate-update relay and its source/destination acceptance conditions, binding that workflow to the selected savings unit. Preserve local PSM access as separate evidence.'},
{'folder':'huma-v2-roles','unit':'unit:lane2:c1:p4','name':'Huma Finance V2 — product binding unresolved','ids':['dispute-16','dispute-17','dispute-18'],'dispositions':{'asset_management':'not_evidenced','allocation':'not_evidenced','attester':'not_evidenced'},
'spans':[('product-scope','faq-pointer','Please see the','p'),('admin-roles','pool-manager','Pool Owners are addresses','p'),('admin-roles','lender-capital','Lenders, also known','p'),('admin-roles','borrower-drawdown','Borrowers initiate credit requests','p'),('admin-roles','evaluation-role','Each pool is managed by a single EA','p'),('evaluation-agent','credit-terms','As the Evaluation Agent of a pool','p'),('evaluation-agent','receivable-review','This evaluation determines','p'),('evaluation-agent','default-trigger','authority to declare a default','p')],
'claims':[
('asset_management','scoped_predicate_supported','Within the documented Huma Institutional product, lenders supply pooled capital and pool owners manage that pool, select the EA and set parameters. That directly describes management of user capital under the proposed rule.',['admin-roles:lender-capital','admin-roles:pool-manager']),
('allocation','scoped_predicate_supported','Within that Institutional pool, a designated EA selects eligible borrowers and credit terms; approval permits those borrowers to draw pool capital. This identifies the controlling actor, capital source and borrower destinations.',['admin-roles:borrower-drawdown','admin-roles:evaluation-role','evaluation-agent:credit-terms']),
('asset_management','unit_applicability_gap','The corpus names Solana Huma V2, while these operational sources identify Huma Institutional. The retained Huma 2.0 FAQ is only a pointer to the dApp. No retained source establishes the version relationship required to transfer the scoped management finding to this exact unit.',['product-scope:faq-pointer','admin-roles:pool-manager']),
('allocation','unit_applicability_gap','The same unresolved product/version relationship prevents accepting the Institutional allocation behavior as the exact Solana V2 unit behavior. The source-scoped positive predicate remains recorded independently.',['product-scope:faq-pointer','admin-roles:borrower-drawdown']),
('attester','source_statement','An EA evaluates receivable quality for drawdown and can declare defaults; this describes underwriting and administrative decisions.',['evaluation-agent:receivable-review','evaluation-agent:default-trigger']),
('attester','bounded_evidence_gap','No retained source specifies an attestation assertion or schema and its acceptance as evidence for a financial transition, separately from the EA authorizing credit. Both the attestation predicate and unit applicability remain unestablished.',['evaluation-agent:receivable-review','admin-roles:evaluation-role'])],
'limits':['Three bodies were retained, but the Huma 2.0 FAQ body contains only a dApp pointer, not the detailed FAQ text seen in search rendering. It counts toward the body cap and receives no credit for that stale text.','The two substantive operational pages are visibly under Huma Institutional. The corpus combines a V2 name, Solana and institutional-style EA/tranche claims; none alone resolves product identity.','The source-scoped asset_management and allocation predicates are supported for the documented Institutional behavior; unit-level proposed dispositions remain not_evidenced until the relationship is independently established.','No extra Huma Prime, permissionless PST mode, credit legal recourse or oracle roles are imported. The EA is not automatically an attester because it evaluates receivables or sends an authorized transaction.','No signed claim format, credit acceptance implementation, deployed program, actual borrower allocation or legal agreement was inspected.'],
'next':'First bind the corpus unit to the appropriate Huma protocol version and deployment family. Then independently review the two scoped positive predicates. For attester, require a named assertion and consuming transition beyond ordinary credit authorization.'},
{'folder':'wbtc-cross-domain-obligor','unit':'unit:lane2:c2:p0','name':'WBTC — custodial cross-domain workflow and holder obligation','ids':['dispute-19','dispute-20'],'dispositions':{'async_cross_domain':'supported','legal_obligor':'not_evidenced'},
'spans':[('whitepaper','mint-confirmation','Custodian waits for 6 confirmations','ul'),('whitepaper','burn-confirmation','Custodian waits for 25 block confirmations','ul'),('whitepaper','merchant-only-burn','Only merchant addresses can burn','p'),('whitepaper','institutional-contract','The process of minting and burning tokens does not involve','p'),('terms','website-agreement','govern the use of','p'),('terms','information-only','The Website is intended','p'),('faq','mint-summary','Once the BTC deposit is confirmed','p'),('faq','burn-summary','Once the WBTC is received and burned','p')],
'claims':[
('async_cross_domain','source_statement','The whitepaper minting sequence waits for six BTC confirmations before a custodian mints on Ethereum; its burning sequence waits for 25 Ethereum confirmations before BTC release and completion marking.',['whitepaper:mint-confirmation','whitepaper:burn-confirmation']),
('async_cross_domain','inference_under_proposed_rule','That merchant/custodian workflow supplies linked transitions in Bitcoin and Ethereum with an explicit confirmation boundary. It satisfies the proposed predicate within this documented workflow; the rule does not require a trustless relay.',['whitepaper:mint-confirmation','whitepaper:burn-confirmation']),
('async_cross_domain','scope_qualification','The current FAQ summarizes merchant/custodian deposit and release but does not provide those numeric finality requirements. The historical-style whitepaper workflow is not asserted to be every current deployment or chain.',['faq:mint-summary','faq:burn-summary']),
('legal_obligor','source_statement','The whitepaper restricts burning to merchants and describes duties between custodians and merchants. The retained terms govern website use and information.',['whitepaper:merchant-only-burn','whitepaper:institutional-contract','terms:website-agreement','terms:information-only']),
('legal_obligor','bounded_evidence_gap','Those sources do not supply an applicable agreement naming the entity and legally grounded performance owed to an ordinary token holder. Merchant operational duties and informational website terms do not fill that gap.',['whitepaper:institutional-contract','terms:website-agreement'])],
'limits':['The supported proposal is limited to the whitepaper BTC/Ethereum merchant workflow; exact historical deployment and current confirmation policies remain unverified.','The current FAQ compresses release to the user, whereas the whitepaper separates merchant burning/release from the user exchange. This packet does not erase that scope difference or grant users merchant permissions.','The website terms identify their operator by a pronoun and govern website access. They are not a merchant custody agreement or ordinary-holder redemption contract.','No present custodian ownership structure, reserve sufficiency, licensing, legal enforceability or unconditional holder redemption right is verified. A legal-obligor gap is not a claim that no party has any legal obligation.','All three sources are one WBTC publisher family, not independent corroboration. No block explorer, reserve audit or on-chain execution was performed.'],
'next':'Independently review the scoped cross-domain predicate. For legal_obligor, obtain the applicable named custodian/merchant or holder agreement and establish which holder has which obligation, with jurisdiction and version identified.'}
]
(p/'fixture-config.json').write_text(json.dumps(configs,indent=2)+'\n')
