from pathlib import Path
import json,hashlib,subprocess,datetime,re
r=Path('/home/charl/defiformal');b=r/'review/semantic-kernel/program-execution-20260908';o=b/'p24-public-call-diagnostic';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat();write=lambda p,d:p.write_text(json.dumps(d,indent=2)+'\n')
solc=Path('/home/charl/.cache/defiformal-program/program-execution-20260908/p24-compiler/solc-linux-amd64-v0.8.19+commit.7dd6d404');evm=Path('/home/charl/.cache/defiformal-program/program-execution-20260908/p16-tools/evm');assert sha(solc)=='7a5c1d3dc9a8eba62bb2ec37192c9178ae5fe8a54a56e5573fd3c9c17cd9eb48';assert sha(evm)=='d298ce2c811de089d650ed4f9535c0c58efc72e7adee9b61a40b6c10cc26fb5c'
base=b/'p24-source-closure/standard-input.json';assert sha(base)=='6cc2ca50f8ba57480c6b61e945b45111000a8d1b0d8924f417b916b49c3f71b8';d=json.loads(base.read_text());original_sources=list(d['sources'])
for n in ['src/mocks/ERC20Mock.sol','src/mocks/interfaces/IERC20.sol','src/mocks/OracleMock.sol']:d['sources'][n]={'content':(b/'p24-liquidation-test-entry-preparation/upstream'/n).read_text()}
d['sources']['PublicCallProbe.sol']={'content':(o/'PublicCallProbe.sol').read_text()};d['settings']['outputSelection']['*']['*'].append('evm.methodIdentifiers');write(o/'standard-input.json',d)
commands=[]
def run(label,argv,stdin=None):
 st=now();res=subprocess.run(argv,cwd=o,input=stdin,capture_output=True,timeout=180);(o/(label+'.stdout')).write_bytes(res.stdout);(o/(label+'.stderr')).write_bytes(res.stderr);rec={'label':label,'argv':argv,'cwd':str(o),'started_utc':st,'finished_utc':now(),'exit':res.returncode,'stdout_sha256':sha(o/(label+'.stdout')),'stderr_sha256':sha(o/(label+'.stderr'))};commands.append(rec);write(o/'commands.json',commands);return res
res=run('compile',[str(solc),'--standard-json'],(o/'standard-input.json').read_bytes());assert res.returncode==0
out=json.loads(res.stdout);errs=[e for e in out.get('errors',[]) if e.get('severity')=='error'];assert not errs,errs
old=json.loads((b/'p24-compile-readiness/standard-output.json').read_text());prod=out['contracts']['src/Morpho.sol']['Morpho']['evm'];prev=old['contracts']['src/Morpho.sol']['Morpho']['evm'];assert prod['bytecode']['object']==prev['bytecode']['object'];assert prod['deployedBytecode']['object']==prev['deployedBytecode']['object']
harness=out['contracts']['PublicCallProbe.sol']['PublicCallProbe']['evm'];(o/'probe-runtime.hex').write_text(harness['deployedBytecode']['object']);selector=harness['methodIdentifiers']['probe(uint256)']
genesis=json.loads((b/'p16-source-r3-review/fresh/intact/genesis/istanbul-genesis.json').read_text());genesis['config'].update({'berlinBlock':0,'londonBlock':0,'terminalTotalDifficulty':0,'terminalTotalDifficultyPassed':True,'mergeNetsplitBlock':0});genesis.update({'timestamp':'0x1','number':'0x1','difficulty':'0x0','baseFeePerGas':'0x0'});write(o/'paris-genesis.json',genesis)
results=[]
for i in range(4):
 inp=selector+format(i,'064x');res=run('scenario-'+str(i),[str(evm),'run','--prestate',str(o/'paris-genesis.json'),'--codefile',str(o/'probe-runtime.hex'),'--input',inp,'--sender','0x0000000000000000000000000000000000000100','--receiver','0x0000000000000000000000000000000000000200']);output=res.stdout.decode().strip();assert res.returncode==0,(i,res.returncode,res.stdout,res.stderr);assert re.fullmatch(r'0x[0-9a-fA-F]{1024}',output),(i,output,res.stderr.decode());vals=[int(output[2+j*64:2+(j+1)*64],16) for j in range(16)];results.append({'scenario':i,'values':vals});print('scenario',i,vals,flush=True)
a,c,n,z=[x['values'] for x in results];assert a[13]==1 and a[3]==a[4] and a[5]==a[6] and a[7]==a[8] and a[9]==a[10];assert c[1]==0 and c[2]==1 and c[3]==c[4] and c[9]==c[10];assert n[1]>0 and n[2]>0 and n[10]>0 and n[3]==n[4];assert z[11]>z[12] and z[6]==0 and z[8]==0 and z[10]==0 and z[3]-z[4]==z[12]>0;assert all(x['values'][14]==x['values'][15] for x in results)
write(o/'results.json',{'schema':'defiformal-p24-public-call-diagnostic/v1','utc':now(),'source_pin':'8e26ca6a8dbc5089edcd67fb576248810fd2870a','original_production_sources':original_sources,'production_creation_and_runtime_match_prior_compile':True,'solc_sha256':sha(solc),'evm_sha256':sha(evm),'input_sha256':sha(o/'standard-input.json'),'harness_runtime_sha256':sha(o/'probe-runtime.hex'),'genesis_sha256':sha(o/'paris-genesis.json'),'compiler_errors':len(errs),'compiler_warnings':[e.get('formattedMessage') for e in out.get('errors',[]) if e.get('severity')=='warning'],'results':results,'assertions_passed':True,'public_source_calls_executed':True,'P24_accepted':False,'independent_review_pending':True,'scope':'Root diagnostic: single actor with upstream ERC20/Oracle mocks, zero IRM, no elapsed time, empty callback data, fresh local state each scenario. Runtime harness installed directly, production contracts created through real constructors. No deployed-mainnet state claim, multi-supplier allocation proof, full rollback proof or P24 implementation acceptance.'})
print('All four source diagnostics verified; independent review pending',flush=True)
