import DefiKernel.Parallel.Dependency.Fixtures

#print axioms DefiKernel.Parallel.expression_congr_of_region
#print axioms DefiKernel.Parallel.mapM_congr_on
#print axioms DefiKernel.Parallel.mapM_ok_mem
#print axioms DefiKernel.Parallel.evaluate_congr
#print axioms DefiKernel.Parallel.evaluated_targets
#print axioms DefiKernel.Parallel.evaluated_effect_zero_outside
#print axioms DefiKernel.Parallel.funds_iff
#print axioms DefiKernel.Parallel.applyEvaluated_congr
#print axioms DefiKernel.Parallel.execute_congr
#print axioms DefiKernel.Parallel.execute_refusal_iff
#print axioms DefiKernel.Parallel.execute_success_congr
#print axioms DefiKernel.Parallel.execute_target_frame
#print axioms DefiKernel.Parallel.prepareInvocation_shape
#print axioms DefiKernel.Parallel.analyzed_dependencies
#print axioms DefiKernel.Parallel.analyzed_outputs
#print axioms DefiKernel.Parallel.snapshots_congr
#print axioms DefiKernel.Parallel.extractReceipt_congr
#print axioms DefiKernel.Parallel.executeStep_congr
#print axioms DefiKernel.Parallel.executeStep_target_frame
#print axioms DefiKernel.Parallel.executeStep_refusal_iff
#print axioms DefiKernel.Parallel.DependencyFixtures.foreign_agrees
#print axioms DefiKernel.Parallel.DependencyFixtures.foreign_differs
#print axioms DefiKernel.Parallel.DependencyFixtures.malformed_evaluates
#print axioms DefiKernel.Parallel.DependencyFixtures.malformed_targets
#print axioms DefiKernel.Parallel.DependencyFixtures.malformed_effect_outside
#print axioms DefiKernel.Parallel.DependencyFixtures.malformed_writes_fail
#print axioms DefiKernel.Parallel.DependencyFixtures.foreign_funds_iff
#print axioms DefiKernel.Parallel.DependencyFixtures.target_balance_is_needed
#print axioms DefiKernel.Parallel.DependencyFixtures.refused_iff
#print axioms DefiKernel.Parallel.DependencyFixtures.funded_malformed_refusal
#print axioms DefiKernel.Parallel.DependencyFixtures.foreign_malformed_refusal
#print axioms DefiKernel.Parallel.DependencyFixtures.poor_malformed_refusal
#print axioms DefiKernel.Parallel.DependencyFixtures.accounting_refusal
#print axioms DefiKernel.Parallel.DependencyFixtures.division_evaluation
#print axioms DefiKernel.Parallel.DependencyFixtures.division_execution
#print axioms DefiKernel.Parallel.DependencyFixtures.observation_error
#print axioms DefiKernel.Parallel.DependencyFixtures.inactive_evaluation_congr
#print axioms DefiKernel.Parallel.DependencyFixtures.foreign_success
