import DefiKernel.Arithmetic.Fees
import DefiKernel.Arithmetic.Quantity
#print axioms DefiKernel.Arithmetic.Fees.validatedRate_ok_iff
#print axioms DefiKernel.Arithmetic.Fees.validatedRate_error_iff
#print axioms DefiKernel.Arithmetic.Fees.fee_bound
#print axioms DefiKernel.Arithmetic.Fees.feeFromGross_of_round
#print axioms DefiKernel.Arithmetic.Fees.feeFromGross_ok_iff
#print axioms DefiKernel.Arithmetic.Fees.feeFromGross_error_iff
#print axioms DefiKernel.Arithmetic.Fees.feeFromGross_conservation
#print axioms DefiKernel.Arithmetic.Fees.feeOnTop_of_round
#print axioms DefiKernel.Arithmetic.Fees.feeOnTop_overflow_of_round
#print axioms DefiKernel.Arithmetic.Fees.feeOnTop_ok_iff
#print axioms DefiKernel.Arithmetic.Fees.feeOnTop_error_iff
#print axioms DefiKernel.Arithmetic.Fees.feeOnTop_conservation
#print axioms DefiKernel.Arithmetic.Fees.feeFromGross_down_ok_iff
#print axioms DefiKernel.Arithmetic.Fees.feeFromGross_up_ok_iff
#print axioms DefiKernel.Arithmetic.Fees.feeOnTop_down_ok_iff
#print axioms DefiKernel.Arithmetic.Fees.feeOnTop_up_ok_iff
#print axioms DefiKernel.Arithmetic.Fees.feeFromGross_zero_rate
#print axioms DefiKernel.Arithmetic.Fees.feeOnTop_zero_rate
#print axioms DefiKernel.Arithmetic.Fees.feeFromGross_zero_amount
#print axioms DefiKernel.Arithmetic.Fees.feeOnTop_zero_amount
#print axioms DefiKernel.Arithmetic.Fees.feeFromGross_unit_rate
#print axioms DefiKernel.Arithmetic.Fees.feeOnTop_unit_rate
#print axioms DefiKernel.Arithmetic.Fees.feeFromGross_exact_fraction
#print axioms DefiKernel.Arithmetic.Fees.feeOnTop_exact_fraction
#print axioms DefiKernel.Arithmetic.Fees.feeFromGross_exists_iff
#print axioms DefiKernel.Arithmetic.Fees.feeFromGross_fee_le
#print axioms DefiKernel.Arithmetic.Fees.feeOnTop_fee_le
#print axioms DefiKernel.Arithmetic.Fees.feeFromGross_one_down
#print axioms DefiKernel.Arithmetic.Fees.feeFromGross_one_up
#print axioms DefiKernel.Arithmetic.Quantity.toQuantity_amount
#print axioms DefiKernel.Arithmetic.Quantity.fromRat_ok_iff_div
#print axioms DefiKernel.Arithmetic.Quantity.fromRat_ok_iff
#print axioms DefiKernel.Arithmetic.Quantity.fromRat_exists_iff
#print axioms DefiKernel.Arithmetic.Quantity.fromRat_toQuantity
#print axioms DefiKernel.Arithmetic.Quantity.toQuantity_fromRat
#print axioms DefiKernel.Arithmetic.Quantity.fromRat_error_iff
#print axioms DefiKernel.Arithmetic.Quantity.toQuantity_fromRat_eq
