"""Every markdown file in a lane must be represented in that lane's graph.

Two firings ago 09-rwa and 11-fiat-stablecoins each carried an
01-research-round2.md that was tracked in git and absent from the graph -- the
round-two research, missing from exactly the graphs meant to hold it. It was
found by hand. Nothing would catch it today, so this does.

A file counts as represented if at least one node names it as its source_file.
The check is deliberately shallow: it asks whether the ingest saw the document at
all, not whether it extracted it well.
"""
import glob, io, json, os, re, sys
import os as _os, pathlib as _pl, sys as _sys
# Resolved from this file's own location; DEFIFORMAL_ROOT overrides and says so.
_SELF = _pl.Path(__file__).resolve().parents[2]
_REPO = _pl.Path(_os.environ.get("DEFIFORMAL_ROOT", _SELF))
if str(_REPO) != str(_SELF):
    print("%s: NOTE - reading %s (DEFIFORMAL_ROOT), not %s"
          % (_pl.Path(__file__).name, _REPO, _SELF), file=_sys.stderr)


ROOT = str(_REPO / "expansion")
LANES = sorted(d for d in os.listdir(ROOT) if re.match(r"^\d\d-", d))

fail = []
print("%-22s %-5s %-6s %s" % ("lane", "md", "ingest", "missing from the graph"))
for slug in LANES:
    g = json.load(io.open("%s/%s/graphify-out/graph.json" % (ROOT, slug), encoding="utf-8"))
    seen = set()
    for n in g["nodes"]:
        sf = n.get("source_file") or ""
        if sf:
            seen.add(os.path.basename(sf))
    on_disk = sorted(os.path.basename(f) for f in glob.glob("%s/%s/*.md" % (ROOT, slug)))
    missing = [f for f in on_disk if f not in seen]
    # GRAPH_REPORT.md is generated by graphify itself into graphify-out, not a source
    missing = [f for f in missing if f != "GRAPH_REPORT.md"]
    print("%-22s %-5d %-6d %s" % (slug, len(on_disk), len(on_disk) - len(missing),
                                  ",".join(missing) if missing else "-"))
    for f in missing:
        fail.append("%s: %s is on disk and not in the graph" % (slug, f))

# The other half: specs are indexed by the domain graph, not the lane graphs.
# No lane graph holds a spec node -- that is the division of labour, and saying
# so here stops the next reader treating sixty files as missing.
import glob as _glob
dom = json.load(io.open(str(_REPO / "expansion/graphify-out/domain-graph.json"),
                        encoding="utf-8"))
prot_src = {n.get("source_file") for n in dom["nodes"] if n.get("kind") == "protocol"}
specs = sorted(_glob.glob("expansion/*/specs/*.json"))
import subprocess
root = subprocess.run(["git", "rev-parse", "--show-toplevel"],
                      capture_output=True, text=True, cwd=str(_REPO)).stdout.strip()
specs = sorted(os.path.relpath(f, root) for f in
               _glob.glob(root + "/expansion/*/specs/*.json"))
orphan = [f for f in specs if f not in prot_src]
print()
print("specs on disk: %d   with a protocol node in the domain graph: %d"
      % (len(specs), len(specs) - len(orphan)))
for f in orphan[:5]:
    fail.append("%s has no protocol node in the domain graph" % f)

print()
for f in fail:
    print("   ", f)
# verdict last: the gate matches on tail -1
if fail:
    print("COVERAGE INCOMPLETE")
else:
    print("LANE COVERAGE COMPLETE: every markdown file is in its lane graph "
          "and every spec is in the domain graph")
sys.exit(1 if fail else 0)
