"""Every markdown file in a lane must be represented in that lane's graph.

Two firings ago 09-rwa and 11-fiat-stablecoins each carried an
01-research-round2.md that was tracked in git and absent from the graph -- the
round-two research, missing from exactly the graphs meant to hold it. It was
found by hand. Nothing would catch it today, so this does.

A file counts as represented if at least one node names it as its source_file.
The check is deliberately shallow: it asks whether the ingest saw the document at
all, not whether it extracted it well.
"""
import glob, io, json, os, re, sys

ROOT = "/root/defiformal/expansion"
LANES = sorted(d for d in os.listdir(ROOT) if re.match(r"^\d\d-", d))

fail = []
print("%-22s %-5s %-6s %s" % ("lane", "md", "ingest", "missing from the graph"))
for slug in LANES:
    g = json.load(io.open("%s/%s/graphify-out/graph.json" % (ROOT, slug), encoding="utf-8"))
    seen = set()
    for n in g["nodes"]:
        sf = n.get("source_file") or ""
        if sf:
            seen.add(os.path.basename(sf))
    on_disk = sorted(os.path.basename(f) for f in glob.glob("%s/%s/*.md" % (ROOT, slug)))
    missing = [f for f in on_disk if f not in seen]
    # GRAPH_REPORT.md is generated by graphify itself into graphify-out, not a source
    missing = [f for f in missing if f != "GRAPH_REPORT.md"]
    print("%-22s %-5d %-6d %s" % (slug, len(on_disk), len(on_disk) - len(missing),
                                  ",".join(missing) if missing else "-"))
    for f in missing:
        fail.append("%s: %s is on disk and not in the graph" % (slug, f))

print()
if fail:
    print("LANE COVERAGE INCOMPLETE")
    for f in fail:
        print("   ", f)
else:
    print("LANE COVERAGE COMPLETE: every markdown file in every lane is in its graph")
sys.exit(1 if fail else 0)
