// cor:ourconvex -- "D has 15 arcs and 58 strongly connected components, none non-trivial,
// so it is acyclic; and Cn coincides with reachability in D (checked on 21,712 seeds)."
import * as L from "./lib.mjs";
import * as T from "/root/DefiElements/formal/v2/tables.mjs";

console.log("=== cor:ourconvex / thm:convex (definite fragment) ===\n");

function definiteArcs(laws, label) {
  const arcs = [];
  for (const [id, subs, terms] of laws)
    for (const t of terms) if (t.length === 1)
      for (const s of subs) if (s !== t[0]) arcs.push([s, t[0], id]);
  const uniq = [...new Set(arcs.map(a => a[0] + "->" + a[1]))];
  console.log(`${label}: definite (singleton-term) arcs = ${arcs.length}, distinct = ${uniq.length}`);
  console.log(`   ${uniq.join("  ")}`);
  // distinct arcs: a pair may be required by more than one row (Pf->Ct is in
  // both L1 and L4), and a digraph has one arc per pair, not one per row.
  return uniq.map(k => k.split("->"));
}

const arcsL = definiteArcs(T.LSTAR, "LSTAR (paper's L*)");
const parsed = T.PARSED_NEW.map(l => [l.id, l.subjects, l.terms.filter(t => !t.external).map(t => t.alts)]);
const arcsP = definiteArcs(parsed, "PARSED_NEW (raw data.ts law strings)");

function analyse(arcs, label) {
  console.log(`\n--- ${label} ---`);
  const adj = new Map();
  for (const [a, b] of arcs) { if (!adj.has(a)) adj.set(a, new Set()); adj.get(a).add(b); }
  // Tarjan SCC over ALL 58 vertices
  let idx = 0; const index = new Map(), low = new Map(), onstk = new Set(), stk = [], sccs = [];
  function strong(v) {
    index.set(v, idx); low.set(v, idx); idx++; stk.push(v); onstk.add(v);
    for (const w of (adj.get(v) || [])) {
      if (!index.has(w)) { strong(w); low.set(v, Math.min(low.get(v), low.get(w))); }
      else if (onstk.has(w)) low.set(v, Math.min(low.get(v), index.get(w)));
    }
    if (low.get(v) === index.get(v)) {
      const c = []; let w;
      do { w = stk.pop(); onstk.delete(w); c.push(w); } while (w !== v);
      sccs.push(c);
    }
  }
  for (const v of L.E) if (!index.has(v)) strong(v);
  const nontrivial = sccs.filter(c => c.length > 1);
  const selfloop = arcs.filter(([a, b]) => a === b);
  console.log(`vertices ${L.E.length}; arcs ${arcs.length}; SCCs ${sccs.length}; non-trivial SCCs ${nontrivial.length}; self-loops ${selfloop.length}`);
  console.log(`ACYCLIC: ${nontrivial.length === 0 && selfloop.length === 0}`);

  // reachability closure Cn
  const reach = s => { const seen = new Set([s]), q = [s];
    while (q.length) { const v = q.pop(); for (const w of (adj.get(v) || [])) if (!seen.has(w)) { seen.add(w); q.push(w); } }
    return seen; };
  const Cn = X => { const out = new Set(X); let ch = true;
    while (ch) { ch = false; for (const v of [...out]) for (const w of (adj.get(v) || [])) if (!out.has(w)) { out.add(w); ch = true; } }
    return out; };
  // Cn == reachability: test exhaustively on all singletons + all pairs + all triples of E
  let n = 0, bad = 0;
  const check = X => { n++;
    const a = Cn(X); const b = new Set(); for (const s of X) for (const t of reach(s)) b.add(t);
    if (L.key(a) !== L.key(b)) bad++; };
  for (let i = 0; i < L.E.length; i++) { check(new Set([L.E[i]]));
    for (let j = i + 1; j < L.E.length; j++) { check(new Set([L.E[i], L.E[j]]));
      for (let k = j + 1; k < L.E.length; k++) check(new Set([L.E[i], L.E[j], L.E[k]])); } }
  console.log(`Cn == reachability on all ${n} seeds of size <= 3: mismatches ${bad}`);

  // union-stability of Cn (thm:convex hypothesis) exhaustive on the same seeds
  let un = 0, ubad = 0;
  for (let i = 0; i < L.E.length; i++) for (let j = i + 1; j < L.E.length; j++)
    for (let k = j + 1; k < L.E.length; k++) {
      const A = new Set([L.E[i]]), B = new Set([L.E[j], L.E[k]]);
      un++;
      if (L.key(Cn(L.uni(A, B))) !== L.key(L.uni(Cn(A), Cn(B)))) ubad++;
    }
  console.log(`Cn(A u B) == Cn(A) u Cn(B) on ${un} split seeds: failures ${ubad}`);

  // anti-exchange, exhaustive over closed sets generated by <=2 elements
  const closed = new Set();
  for (let i = 0; i < L.E.length; i++) { closed.add(L.key(Cn(new Set([L.E[i]]))));
    for (let j = i + 1; j < L.E.length; j++) closed.add(L.key(Cn(new Set([L.E[i], L.E[j]])))); }
  closed.add("");
  let ae = 0, aeBad = 0;
  for (const ck of closed) {
    const A = new Set(ck ? ck.split(",") : []);
    for (const x of L.E) { if (A.has(x)) continue;
      for (const y of L.E) { if (A.has(y) || x === y) continue;
        const Cx = Cn(new Set([...A, x])), Cy = Cn(new Set([...A, y]));
        if (Cy.has(x) && Cx.has(y)) aeBad++;
        ae++; } }
  }
  console.log(`anti-exchange over ${closed.size} closed sets x ${L.E.length}^2 pairs (${ae} tests): violations ${aeBad}`);

  // ex() and thm:excomp: ex(A) = maximal elements; check ex(A u B) = max(ex A u ex B)
  const below = (a, b) => reach(a).has(b);            // a >= b  iff  b in Cn({a})
  const maxOf = S => new Set([...S].filter(a => ![...S].some(b => b !== a && below(b, a))));
  const ex = A => maxOf(A);
  let cn = 0, cbad = 0, cwit = null;
  const gens = [];
  for (let i = 0; i < L.E.length; i++) for (let j = i; j < L.E.length; j++) gens.push(Cn(new Set([L.E[i], L.E[j]])));
  for (let i = 0; i < gens.length; i++) for (let j = i; j < gens.length; j++) {
    const A = gens[i], B = gens[j];
    const lhs = ex(L.uni(A, B));
    const rhs = maxOf(L.uni(ex(A), ex(B)));
    cn++;
    if (L.key(lhs) !== L.key(rhs)) { cbad++; if (!cwit) cwit = [A, B, lhs, rhs]; }
  }
  console.log(`thm:excomp  ex(A u B) == max(ex A u ex B) over ${cn} closed pairs: failures ${cbad}`);
  if (cwit) console.log(`   witness A={${L.key(cwit[0])}} B={${L.key(cwit[1])}} lhs={${L.key(cwit[2])}} rhs={${L.key(cwit[3])}}`);

  // honest scale: how many elements are their own canonical form?
  const own = L.E.filter(e => Cn(new Set([e])).size === 1).length;
  console.log(`elements whose principal closure is themselves (Cn({e}) = {e}): ${own} / ${L.E.length}`);
}

analyse(arcsL, "LSTAR definite digraph");
analyse(arcsP, "PARSED_NEW definite digraph");
