/* Emit one persistent SECTION-BRIEF.md per category: everything stage 6 needs to
 * write that section of the paper, in one file, with every figure computed.
 *
 *   node section-brief.mjs <expansion-root>
 *
 * Mechanical part is generated from the corpus, the specs and the verdicts, so
 * it cannot drift. Narrative part is whatever SECTION-NOTES.md the lane left -
 * the findings that are judgement rather than arithmetic - appended verbatim.
 */
import fs from "node:fs";
import { PARSED_NEW, MECH, ELEMS } from "../v2/tables.mjs";
import { asSet, ex, admissibility, loadCorpus } from "./construct.mjs";
import path from "node:path";
import { fileURLToPath } from "node:url";
// Resolved from this file's own location; DEFIFORMAL_ROOT overrides and says so.
const SELF_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const REPO_ROOT = process.env.DEFIFORMAL_ROOT || SELF_ROOT;
if (REPO_ROOT !== SELF_ROOT) console.error(`${path.basename(fileURLToPath(import.meta.url))}: NOTE - reading ${REPO_ROOT} (DEFIFORMAL_ROOT), not ${SELF_ROOT}`);


const root = process.argv[2] || `${REPO_ROOT}/expansion`;
// The lane corpus is not committed to this repository. DEFIFORMAL_CORPUS
// points at it; the default is the working tree it was authored against.
const CORPUS_DIR = process.env.DEFIFORMAL_CORPUS || "/mnt/c/defiformal-work/corpus";
const P = loadCorpus();

const pct = (a, b) => b ? (100 * a / b).toFixed(1) + "%" : "n/a";

const lanes = fs.readdirSync(root).filter(d => /^\d\d-/.test(d));
let written = 0;
for (const slug of lanes) {
  const dir = path.join(root, slug);
  const cpath = path.join(CORPUS_DIR, `${slug}.json`);
  if (!fs.existsSync(cpath)) continue;
  const c = JSON.parse(fs.readFileSync(cpath, "utf8"));
  const vpath = path.join(dir, "verdicts.json");
  const V = fs.existsSync(vpath) ? JSON.parse(fs.readFileSync(vpath, "utf8")) : null;

  const mem = P.filter(p => p.cat === c.category);
  const foot = [...new Set(mem.flatMap(p => p.syms))].sort();
  const elsewhere = new Set(P.filter(p => p.cat !== c.category).flatMap(p => p.syms));
  const excl = foot.filter(e => !elsewhere.has(e));
  const core = foot.filter(e => mem.every(p => p.syms.includes(e)));
  const sizes = mem.map(p => p.syms.length).sort((a, b) => a - b);

  const L = [];
  L.push(`# Section brief — ${c.category}`);
  L.push("");
  L.push(`*Generated by \`formal/v3/section-brief.mjs\`. Every figure below is computed;`);
  L.push(`the narrative at the end is the lane's own, appended verbatim. This file is`);
  L.push(`the input for writing \`\\section{...}\\label{${c.texLabel}}\` and its five subsections.*`);
  L.push("");
  L.push(`## The question this category answers`);
  L.push("");
  L.push(`> ${(c.whyACategory || "").trim()}`);
  L.push("");
  L.push(`## The corpus decomposition, as of 2026-08-04`);
  L.push("");
  L.push(`Footprint ${foot.length} of the 58 elements: \`${foot.join(", ")}\`.`);
  L.push(`Exclusive to this category: ${excl.length ? "`" + excl.join(", ") + "`" : "**none**"}.`);
  L.push(`Present in every member: ${core.length ? "`" + core.join(", ") + "`" : "**no common core**"}.`);
  L.push(`Element-set sizes ${sizes.join(", ")}.`);
  L.push("");
  L.push(`| protocol | corpus set | canonical form | derives | req+warrants |`);
  L.push(`|---|---|---|---|---|`);
  for (const p of mem) {
    const g = ex(asSet(p.syms));
    const a = admissibility(asSet(p.syms));
    L.push(`| ${p.name} | \`${p.syms.join(",")}\` | \`${g.join(",")}\` | ${p.syms.filter(e => !g.includes(e)).join(",") || "—"} | ${a.req.length || a.war.length ? "**rejected**: " + a.req.map(r => r.law + ":" + r.term.join("|")).join(" ") + (a.war.length ? " unwarranted " + a.war.join(",") : "") : "satisfied"} |`);
  }
  L.push("");
  L.push(`## The category residue the original lane recorded`);
  L.push("");
  L.push((c.categoryResidue || "*(none recorded)*").trim());
  L.push("");

  if (V) {
    const tot = V.reduce((a, v) => a + v.obligationsTotal, 0);
    const cov = V.reduce((a, v) => a + v.obligationsCovered, 0);
    L.push(`## Stage 3: the constructions, machine-checked`);
    L.push("");
    L.push(`${V.length} applications, ${tot} obligations, ${cov} discharged, ${tot - cov} residue, coverage ${pct(cov, tot)}.`);
    L.push("");
    L.push(`| application | construction | canonical form | verdict | obligations | residue |`);
    L.push(`|---|---|---|---|---|---|`);
    for (const v of V)
      L.push(`| ${v.app} | \`${v.construction.join(",")}\` | \`${v.canonicalForm.join(",")}\` | **${v.verdict}**${v.openRequirementTerms.length ? " (" + v.openRequirementTerms.join(" ") + ")" : ""}${v.armedProhibitions.length ? " arms " + v.armedProhibitions.join(",") : ""} | ${v.obligationsCovered}/${v.obligationsTotal} | ${v.obligationsUncovered.length} |`);
    L.push("");
    L.push(`### Where the corpus and the construction disagree`);
    L.push("");
    for (const v of V) {
      const cp = mem.find(m => m.name === v.app || v.app.startsWith(m.name.split(" (")[0]));
      if (!cp) { L.push(`- **${v.app}** — no corpus row matched by name; compare by hand.`); continue; }
      const added = v.construction.filter(e => !cp.syms.includes(e));
      const dropped = cp.syms.filter(e => !v.construction.includes(e));
      if (!added.length && !dropped.length) { L.push(`- **${v.app}** — construction equals the corpus set.`); continue; }
      L.push(`- **${v.app}** — added \`${added.join(",") || "—"}\`, dropped \`${dropped.join(",") || "—"}\`.`);
    }
    L.push("");
    L.push(`### Residue, verbatim`);
    L.push("");
    for (const v of V) {
      if (!v.obligationsUncovered.length) continue;
      L.push(`**${v.app}** (${v.obligationsUncovered.length}):`);
      L.push("");
      for (const o of v.obligationsUncovered) L.push(`- ${o.text}`);
      L.push("");
    }
  } else {
    L.push(`## Stage 3`);
    L.push("");
    L.push(`*Not yet run for this category — no \`verdicts.json\`.*`);
    L.push("");
  }

  L.push(`## Sources`);
  L.push("");
  L.push(`- Round-one research: \`expansion/${slug}/01-research.md\``);
  const r2 = path.join(dir, "01-research-round2.md");
  if (fs.existsSync(r2)) L.push(`- Round-two research: \`expansion/${slug}/01-research-round2.md\``);
  L.push(`- Obligation specs: \`expansion/${slug}/specs/\``);
  if (V) L.push(`- Verdicts: \`expansion/${slug}/verdicts.json\``);
  if (fs.existsSync(path.join(dir, "graphify-out/graph.json"))) {
    const g = JSON.parse(fs.readFileSync(path.join(dir, "graphify-out/graph.json"), "utf8"));
    L.push(`- Knowledge graph: \`expansion/${slug}/graphify-out/graph.json\` — ${g.nodes.length} nodes, ${g.links.length} links`);
  }
  L.push("");

  const notes = path.join(dir, "SECTION-NOTES.md");
  if (fs.existsSync(notes)) {
    L.push(`---`);
    L.push("");
    L.push(fs.readFileSync(notes, "utf8").trim());
    L.push("");
  } else {
    L.push(`---`);
    L.push("");
    L.push(`## Lane narrative`);
    L.push("");
    L.push(`*No \`SECTION-NOTES.md\` yet. The lane's own judgement findings — the ones that`);
    L.push(`are not arithmetic — belong there and will be appended here on regeneration.*`);
    L.push("");
  }

  fs.writeFileSync(path.join(dir, "SECTION-BRIEF.md"), L.join("\n"));
  written++;
  console.log(`${slug}: brief written (${L.length} lines)${V ? "" : " [no verdicts yet]"}`);
}

// Zero lanes written means the corpus was not found, not that the briefs are
// current. Exiting 0 here is what made brief-fresh.sh vacuous: it diffed the
// committed briefs against themselves and reported 12 of 12 identical.
if (written === 0) {
  console.error(`section-brief.mjs: CORPUS ABSENT - no lane corpus at ${CORPUS_DIR}`);
  console.error(`  set DEFIFORMAL_CORPUS to the directory holding <NN-slug>.json`);
  console.error(`  wrote 0 of ${lanes.length} briefs; nothing was checked`);
  process.exit(3);
}
