from pathlib import Path
import datetime,hashlib,json,subprocess
R=Path('/home/charl/defiformal');B=R/'review/semantic-kernel/program-execution-20260908';C=B.parent/'strategy-audit-20260908/CURRENT.json';h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();read=lambda p:json.loads(p.read_text());now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def put(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
s=read(B/'STATE.json');c=read(C);o=B/'p19-module-tree-grok-r1';v=read(o/'root-adjudication.json');g=read(B/'p26-source-grok-r1/dispatch.json');assert Path('/proc/2314645').exists() and Path('/proc',str(g['pid'])).exists()
s['updated_utc']=now();s['phase']='AGY_R24_codec_proofs_running_Grok_P26_IBC_source_audit_running_R23_review_complete';s['p19']['module_tree_review']={**v,'root_seal':'p19-module-tree-grok-r1/root-seal.json','root_seal_sha256':h(o/'root-seal.json'),'sealed_files':59,'status':'completed_root_verified_adjudicated','acceptance':False};s['p19']['next_author_completed_r23_review_guidance']={'review':'p19-module-tree-grok-r1/REVIEW.md','root_adjudication':'p19-module-tree-grok-r1/root-adjudication.json','scoped_usable':['admitted module TreeJson string encoding','direct declaration-order Request decoder proof'],'actual_fresh_review_named_inventory':550,'full_P19_accepted':False,'note':'R24 already implements missing semantic decoder/validity/depth/scanner obligations. Deliver completed source review on next terminal handoff. No need to interrupt live author or redispatch unchanged proof audit.'};s['independent_reviewer']={**g,'root_supervisor_handle':9674};s['p26']['source_review']={'status':'running_observed_now','dispatch':s['independent_reviewer'],'output':'p26-source-grok-r1','inputs':'p26-source-grok-r1/inputs.json','acceptance':False};s['p26']['prepared_review_status']='launched_after_R23_review_sealed';s['p26']['active_review_launcher']='p26-source-grok-r1-launcher-after-r23.py'
s['next_actions']=['Poll AGY R24 supervisor41629 (45m native run, started21:26:29UTC) and fresh Grok P26 source audit9674 (20turn cap). R23 proof reviewer12212 completedexit0 and is root-sealed.','When P26 reviewer terminal and children gone, verify source/report/probe identities, adjudicate source suitability and replay-NOOP observation mapping without claiming P26/P29 proof or execution.','When R24 author terminal and children gone, freeze using prepared helper, inspect actual source/domain/statements and complete every added module inventory; use completed R23 review for next handoff.','P27 GMX and P28 depeg source/compiler preparation remain unaccepted; P28 ABI mismatch needs runtime/contract observation and eSusFarm mock rejection stays preserved. Full core roadmap and P19/P20 obligations unchanged; Atlas parked.'];s['continuation_loop']['native_reviewer_status']='P26_fresh_Grok_source_review_running';s['continuation_loop']['observed_utc']=now()
c['updated_utc']=now();c['current_task']=s['phase'];c['execution_state']='active';c['p26_source_preparation']=s['p26'];c['process_liveness']={'observed_utc':now(),'author_pid':2314645,'author_live':True,'author_supervisor':41629,'reviewer_pid':g['pid'],'reviewer_live':True,'reviewer_supervisor':9674,'reviewer_scope':'P26 IBC source preparation','note':'Observations only, recheck processes on resume; R23 proof review terminal/sealed.'};put(B/'STATE.json',s);put(C,c)
paths={B/'STATE.json',C,B/'p26-source-grok-r1-launcher-after-r23.py',B/'p26-source-grok-r1/brief.txt',B/'p26-source-grok-r1/dispatch.json',B/'p26-source-grok-r1/inputs.json',o/'root-seal.json'}
for p,d in read(o/'root-seal.json')['files'].items():assert h(o/p)==d;paths.add(o/p)
receipt=B/'r23-review-p26-dispatch.json';put(receipt,{'utc':now(),'prior_head':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip(),'R23_review_sealed_files':59,'R23_manifest_bindings':46,'R23_fresh_proof_inventory':550,'R23_scoped_encoding_and_Request_result':'USABLE','full_P19_accepted':False,'P26_source_review_dispatch':g,'author_supervisor':41629,'reviewer_supervisor':9674,'goal':'active_full_core_scope_unchanged'});paths.add(receipt)
subprocess.run(['git','add','-f','--',*[str(p.relative_to(R)) for p in sorted(paths)]],cwd=R,check=True);subprocess.run(['git','-c','core.whitespace=-blank-at-eol,-blank-at-eof','diff','--cached','--check'],cwd=R,check=True);print(json.dumps({'staged_paths':len(paths),'R23_review_sealed_files':59,'P26_review_supervisor':9674}))
