from pathlib import Path
import datetime,hashlib,json,re,shutil
B=Path('/home/charl/defiformal/review/semantic-kernel/program-execution-20260908');O=B/'p19-r22-root-scope';O.mkdir(exist_ok=False);h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();read=lambda p:json.loads(p.read_text());now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def put(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
m=read(B/'p19-roundtrip-proof-agy-r22-terminal-manifest.json');previous=read(B/'p19-roundtrip-proof-agy-r21-terminal-manifest.json');before={r['path']:r['sha256'] for r in previous['files']};after={r['path']:r['sha256'] for r in m['files']};changed=[p for p in after if before.get(p)!=after[p]];assert len(changed)==63 and all(p.startswith('review/semantic-kernel/certificates/p19/implementation/agy-r22-proof/') for p in changed);assert not set(before)-set(after)
e=Path(m['worktree'])/'review/semantic-kernel/certificates/p19/implementation/agy-r22-proof';assert read(e/'commands.json')==[] and read(e/'MANIFEST.json')['files']==[] and read(e/'verdict.json')['status']=='IN_PROGRESS'
probes=list((e/'probes').glob('*.lean'));assert len(probes)==59
recovery=B/'p19-r22-root-probe-recovery';corrected=[]
for p in sorted(recovery.glob('*/command.json')):
 d=read(p);text=(p.parent/'stdout').read_text();headers=[line for line in text.splitlines() if re.search(r':\d+:\d+: error(?:\(|:)',line)]
 corrected.append({'probe':p.parent.name,'exit':d['exit'],'timed_out':d['timed_out'],'all_error_headers':headers,'all_error_header_count':len(headers),'raw_stdout_sha256':h(p.parent/'stdout')})
record={'utc':now(),'candidate_archive_sha256':m['sha256'],'frozen_files':3664,'production_source_changed':False,'all_prior_frozen_files_unchanged':len(before),'new_files':63,'new_scratch_proofs':59,'author_command_receipts':0,'author_manifest_bindings':0,'author_reports':'All report files remain IN_PROGRESS; native SUCCESS/exit0 is not proof completion.','root_recovery':corrected,'root_error_counter_correction':'Original root probe summary searched error: and missed two error(lean.unknownIdentifier) headers in test_template_fix. All three exit1 verdicts were correct; complete header counts are12,4,4 by named probe. Raw streams unchanged.','diagnostic_obligations':['Explicit Nat-to-Int map lambda/length correspondence for capabilityIds in Request and Invocation representations.','JsonNumber.fromNat normalization and semantic mkObj equality across declaration and sorted field orders.','Missing cellDeltaToJson_encode/supplyDeltaToJson_encode identifiers and malformed TypesEnum proof syntax.','stepToTreeJson_encode quantifies over unsupported tags while production unsupported encoding concatenates raw tags. Match the existing supported canonical domain; do not claim arbitrary unsupported strings encode through escaped TreeJson.','Proof normalization heartbeat limit in template encoding; search existing structural lemmas before expanding huge definitions.'],'production_inventory':'Exact production source unchanged from independently checked R21 (448 named theorem/lemma,415standard33none). No new axiom run is claimed for R22.','next':'AGY repairs and moves compiling module maps into production, then closes whole-module/scanner theorem and full P19 obligations; fresh Grok provides independent stuck review of frozen R22 evidence.','P19_accepted':False,'whole_program_complete':False}
put(O/'scope.json',record);shutil.copy2(__file__,O/'verify.py');files={p.name:h(p) for p in O.iterdir() if p.is_file()};put(O/'root-seal.json',{'utc':now(),'files':files,'file_count':len(files),'P19_accepted':False});put(B/'p19-roundtrip-proof-agy-r22-root-precheck.json',record);print(json.dumps({'production_changes':0,'scratch_proofs':59,'recorded_author_commands':0,'root_selected_failures':[(r['probe'],r['all_error_header_count']) for r in corrected]}))
