import DefiKernel.Parallel.Commutation
#print axioms DefiKernel.Parallel.observeBranch_failure
#print axioms DefiKernel.Parallel.observeBranch_outputs
#print axioms DefiKernel.Parallel.mergeWorld_store
#print axioms DefiKernel.Parallel.mergeWorld_nonnegative
#print axioms DefiKernel.Parallel.mergeWorld_outside
#print axioms DefiKernel.Parallel.worldEq_iff
#print axioms DefiKernel.Parallel.observationsEqual_iff
#print axioms DefiKernel.Parallel.runParallel_refuses
#print axioms DefiKernel.Parallel.WorldEquivalent.refl
#print axioms DefiKernel.Parallel.WorldEquivalent.symm
#print axioms DefiKernel.Parallel.WorldEquivalent.trans
#print axioms DefiKernel.Parallel.ObservationallyEquivalent.refl
#print axioms DefiKernel.Parallel.ObservationallyEquivalent.symm
#print axioms DefiKernel.Parallel.ObservationallyEquivalent.trans
#print axioms DefiKernel.Parallel.CursorAgrees.observation
#print axioms DefiKernel.Parallel.continueRun_congr
#print axioms DefiKernel.Parallel.runBranch_congr
#print axioms DefiKernel.Parallel.continueRun_frame
#print axioms DefiKernel.Parallel.runBranch_frame
#print axioms DefiKernel.Parallel.analyzeBranchFrom_writes_read
#print axioms DefiKernel.Parallel.rerun_after_peer
#print axioms DefiKernel.Parallel.merge_serialLR
#print axioms DefiKernel.Parallel.runParallel_serialLR
#print axioms DefiKernel.Parallel.mergeWorld_swap
#print axioms DefiKernel.Parallel.runParallel_serialRL
#print axioms DefiKernel.Parallel.singleton_commutation
#print axioms DefiKernel.Parallel.runBranch_empty
#print axioms DefiKernel.Parallel.runParallel_empty_right
#print axioms DefiKernel.Parallel.runParallel_empty_left
#print axioms DefiKernel.Parallel.serial_orders_equivalent
