from pathlib import Path
P=Path('openspec/changes/corpus-provenance-adjudication')
p=P/'design.md';s=p.read_text()
s=s.replace('at `9908d9b56be2d5ed2b58a16fa8d28b23f33733ff`. Sprint 10 awaits a substantive\nnative Fable planning verdict and has no implementation authorization. This\ncorpus draft still requires its own frozen nonauthor GPT-6/native Fable planning\ngate.','at `9908d9b56be2d5ed2b58a16fa8d28b23f33733ff`. Sprint 10 has its own accepted\nplanning gate and concurrent implementation; that does not approve this corpus\npackage. Corpus official-r1 received native Fable REQUEST CHANGES; this r2 author\nrevision requires a newly frozen nonauthor GPT-6/native Fable planning gate.')
s=s.replace('adjudications,exposure,freeze}.json','adjudications,interpretations,exposure,freeze}.json')
s=s.replace('and `generated/{corpus,coverage,development-manifest,evaluation-manifest}.json`.','and `generated/{corpus,source-claims,coverage,development-manifest,evaluation-manifest}.json`.\n`corpus.json` is the historical-primary projection defined in decision 5;\n`source-claims.json` is a separately scoped source-reading table, not a current\nreplacement for the historical corpus or a new deployment assertion.')
s=s.replace('Each item has a stable ID, source pointer, exposure role,\nallowed acquisition scope, attempt references and current disposition.','Each item has a stable ID, source pointer, exposure role,\nallowed acquisition scope, attempt references and current disposition. Work\ndisposition is a closed enum: `not_attempted`, `attempted_unavailable`,\n`budget_exhausted`, `review_pending`, `reviewed_unresolved`, `reviewed_resolved`.\nThe terminal states for complete bookkeeping are `attempted_unavailable`,\n`budget_exhausted`, `reviewed_unresolved`, `reviewed_resolved`; each requires its\nreason and attempt/review references (or an explicit no-request eligibility\nreason). `not_attempted` and `review_pending` remain open and block a claimed\ncomplete-work exit 0. Closed bookkeeping is not factual resolution: only the\nlast state can count toward a separately checked, scope-specific factual claim.\nCoverage counts every state, including zero counts, by item kind.')
s=s.replace('URLs per original candidate, prioritizing version-specific official docs, pinned\ncode/release manifests, then deployment records. Each request has 30-second\nconnect/read bounds, at most two retries and five redirects; each body is limited','URL targets per original candidate per pass, prioritizing version-specific official\ndocs, pinned code/release manifests, then deployment records. A target is the\nexact absolute HTTP(S) request URL after fragment removal; path/query spelling\nis retained (no guessed slug or query equivalence). Each first attempted target\nconsumes one slot, including failed guesses and corrected/fallback URLs. Retries\nof the identical target use its existing slot; at most two attempts total\n(initial plus one retry) are allowed. Server-issued redirect hops are recorded\nunder that target and consume the independent five-hop bound, not extra target\nslots; manually following a different URL starts a new target. Reusing a redirect\nendpoint later as a requested target consumes a slot. Every attempt records the\nfull redirect chain. Each attempt has a 30-second total wall deadline covering\nconnection, redirects and body reading; each body is limited')
s=s.replace('`retained`, `fingerprint_only`, `unavailable`, or `restricted`. Evidence locators\nbind exact retained bytes; a digest without bytes cannot pass a replay check.','`retained`, `empty_or_non_substantive`, `fingerprint_only`, `unavailable`, or\n`restricted`. `retained` requires positive body length, matching retained body\nbytes and a documented substantive source classification; HTTP status alone\ndoes not qualify. Empty responses, access/challenge pages and redirect-only\nwrappers use `empty_or_non_substantive` with a reason and receive zero support\ncredit even if their transport bytes and digest replay. Evidence locators must\nselect a nonempty span `0 ≤ start < end ≤ byte_length` in an eligible retained\ncoordinate space; reject zero-length/out-of-range spans and any span in an\nempty/non-substantive or redirect-wrapper record. No digest alone supplies support.')
s=s.replace('Derived-text offsets must identify that coordinate\nspace and bind both extraction output and original response bytes.','Derived-text offsets must identify that coordinate\nspace and bind both extraction output and original response bytes. Retain the\nactual derived output bytes with positive length and digest, extractor/version\nand input-body binding; a method name, pin or an ability to rerun extraction\ndoes not substitute for those bytes. Missing output bytes block dependent replay\nwith `missing_extraction_output`. Span checking is mechanical; the factual\nadequacy of a nonempty excerpt still requires source review. Import writes only\nnew normalized overlay records with original-record pointers and normalization\nreasons: legacy transport records marked retained but empty/wrappers become\n`empty_or_non_substantive`, with no support credit. Preserve their original\nlabels, capture bytes and manifests unchanged. Unknown substantiveness remains\nnon-substantive pending review, not implicitly retained.')
s=s.replace('transcript mapping the citation token to its URL. Matching a claim to a new web','transcript mapping the citation token to its URL. Such recovery additionally\nrecords `origin_trust_assumption`, transcript provider/custody history where\nknown, transcript digest, exact mapping span and reviewer assessment. A matching\ndigest and internally consistent mapping verify byte integrity only, not the\nauthenticity/completeness of the supplied browsing transcript. Unknown origin\ntrust leaves the mapping unresolved; accepted recovered mappings explicitly\nremain conditional on the recorded origin assumption. Matching a claim to a new web')
s=s.replace('17 currently disputed labels and the separate liquidation challenge; they do not\nassert that any named protocol satisfies them.','17 currently disputed labels and the separate liquidation challenge; they do not\nassert that any named protocol satisfies them. The versioned `rules.json` is the\nauthoritative predicate payload (the planning copy is supplied with this change).\nEach rule stores its literal Markdown row in addition to parsed fields; the table\nbelow is a literal-equality checked presentation copy. The implemented overlay\ncopies the frozen payload without silently changing it. Common scope clauses\nand any interpretation selection are separately version/hash bound.')
s=s.replace('Each of the 29 inventory records expands its symmetric difference into label\nclaims.','Derive the disagreement set directly from bound normalized `adjudications`\nfiltered by `rule == INTERSECTION_UNRESOLVED`; derive each symmetric difference\nfrom its raw `a` and `b` arrays, cross-check `unresolved_labels`, and compare\nexact unit/facet/label tuples to the queue inventory. The actual baseline yields\n29 facets, 32 label instances and 24 distinct units; these numbers are outputs\nof that comparison, never authority taken from inventory counters.\n\nEach of the 29 inventory records expands its symmetric difference into label\nclaims.')
s=s.replace('is semantically resolved only when every disputed label has an accepted\n`supported`, `refuted`, or justified `not_applicable` disposition.','is historically semantically resolved only when every disputed label has a\nunique accepted effective decision with `unit_applicability: established` and\n`supported`, `refuted`, or justified `not_applicable` disposition under the\napplicable rule/interpretation. Source-only support cannot close this count.')
a=s.index('An adjudication record binds raw A/B hash and pointer')
b=s.index('\nThe retained `source-research/liquity-v1/`',a)
s=s[:a]+'''An adjudication record binds raw A/B hash and pointer, label/rule version and
hash, evidence spans, scoped proposition, rationale, disposition, interpretation
references, reviewer findings and process status `draft`, `review_pending`,
`accepted`, or `superseded`. Every record has a mandatory `unit_applicability`:

| Value | Required meaning | Historical-primary effect |
| --- | --- | --- |
| `established` | Reviewed evidence binds this source proposition to this exact historical unit's product, version or explicitly version-unspecified scope, operation and snapshot time; unresolved deployment does not become verified | Eligible for an accepted unique effective decision |
| `current_documentation_only` | Positive evidence supports only the explicitly named retrieval-time product/documentation scope, not the historical unit | Source-claims table only; historical claim remains not evidenced/unresolved |
| `unresolved` | Even the source-to-unit applicability cannot be established; source reading may still be recorded at its exact scope | No historical label promotion/removal and no semantic closure |

The historical-primary view targets the preserved 2026-08-04 research snapshot
and its exact row/unit identities, retaining unresolved version/deployment fields.
It begins with the original retained intersection as `provisional_observation`,
not supported evidence. Only a unique accepted effective `established` decision
can add a supported label, or remove a refuted/justifiably-not-applicable label.
Accepted not_evidenced/conflicting leaves provisional labels visibly provisional
and the claim unresolved. Other applicability values never alter the historical
facet. The source-claims table shows exact product/document/version/operation/time
and disposition for each current or narrower source scope; it is not a broad
unit-wide current facet projection. Coverage cross-tabulates every disposition
by applicability, review status and scope; historical semantic closure and
source-scoped supported counts are separate. No existing research packet,
including one with a proposed supported unit label, is automatically accepted or
assigned established applicability. Import creates draft/review-pending records.

`inputs/interpretations.json` contains append-only interpretation records with
ID, rule ID/version/payload hash, precise ambiguity, ruling text, rationale,
evidence/review bindings, status and supersession references. Interpretations do
not silently change predicate text: a changed inclusion predicate requires a new
rule version. For each (rule ID, rule version), a frozen selection names exactly
one accepted interpretation head when any ruling applies. Every accepted decision
under that rule version must reference that same selected interpretation, even
if the reviewer considers the case straightforward. The affected-unit inventory
covers all decisions and pending proposals for the rule, including Lighter,
ApeX and edgeX when R-appchain is reviewed; these names are review coverage, not
new taxonomy rulings. Unresolved ambiguity or missing/unaccepted ruling keeps
interpretation-dependent decisions review_pending. Import must flag conditional
packet wording; it cannot infer a ruling from an author's proposed support.

Decision keys are (unit_id, facet, label, rule_version, scope_id), where scope_id
binds the full explicit historical or source scope. Supersession is an append-only
acyclic graph within one key. A new record can supersede one or more existing
records of that key; references must exist, cycles/self-links/cross-key links
are violations. Only accepted successors retire an accepted predecessor in the
effective projection; draft successors do not. A single non-superseded accepted
head supplies the effective decision. Multiple heads produce `conflicting` with
all IDs retained, even when their dispositions happen to agree, until a reviewed
successor explicitly reconciles every head. No filesystem order, timestamp or
reviewer vote chooses a winner. Interpretation selections obey the same
acyclic/unique-head rule per rule/version; conflicting heads block acceptance
of dependent decisions. Historical and current scopes do not supersede each
other. All previous bytes and review observations remain available.
''' +s[b:]
s=s.replace('source hashes, and exposure reasons/times. Every design-inspected source or case','source hashes, and exposure reasons/times. Each retained source additionally\nrecords the publisher identity as stated (or unresolved), and all substantively\ndescribed organizations/products with exact source locators, their identity status\nand relation to the queued unit. These include described third-party providers,\nnot only the requesting unit or URL host; source attribution is not automatic\nlegal-entity resolution. The overlap inventory indexes these descriptions and\nretains aliases/unresolved identities. Every design-inspected source or case')
s=s.replace('queue entries. It emits source/attempt records and captures for review;','queue entries. Eligibility is checked against the bound development manifest\nusing exact unit/ancestry membership and source exposure, not a caller-supplied\nrole field; missing membership or a spoofed development role is rejected before\na request. Task 6.1 must therefore precede task 2.4. It emits source/attempt records and captures for review;')
s=s.replace('at completion; drift blocks the run. Fresh output paths','at completion; relevant input/tool byte drift blocks the run. HEAD movement is\nrecorded with both revisions and Git-object bindings; unrelated commits do not\nrelabel captures or invalidate byte-identical relevant inputs. A changed relevant\nGit object or absent binding blocks the run. Fresh output paths')
s=s.replace('integrity/record contract holds. It does not mean every factual item resolved.','integrity/record contract holds, with every item in the closed terminal work\ndispositions of decision 2. It does not mean every factual item resolved. Open\nnot_attempted/review_pending items give exit 3 `incomplete_work_queue`; unknown\nenum values are readable contract violations (exit 1).')
s=s.replace('Structured diagnostics identify item and reason, not just a\nsummary substring.','A retained zero-length/non-substantive body or invalid nonempty locator is a\nreadable false record (exit 1); a missing body/output claimed retained is exit 3.\nStructured diagnostics identify item and reason, not just a\nsummary substring.')
s=s.replace('Controls call these actual entry points','Offline execution uses an enforceable Linux network-denial wrapper for both\n`build` and `check`: a dedicated network namespace with no external interfaces\nand a pinned seccomp launcher denying socket/socketpair/connect plus equivalent\nnetwork syscalls to the entire child process tree (including subprocesses). The\nlauncher and policy bytes, version and self-test results are run inputs. A fresh\nsubprocess socket-creation/connect probe must actually fail under that policy\nwhile a local-file positive succeeds. Unavailable namespace/seccomp support,\nlauncher or a failed denial self-test is exit 3 `offline_isolation_unavailable`;\nnever fall back to an assertion or an unenforced Python monkey-patch. DNS and\nchild processes are covered; the trusted OS/launcher enforcement is explicit.\nCollector HTTP fixtures run outside that offline wrapper and are labelled separately.\nImplementation may select an existing system launcher, but must bind its exact\nexecutable/policy and demonstrate these behaviors before an offline claim.\n\nControls call these actual entry points')
s=s.replace('This refresh is provisional; no planning gate\nor native review has been performed for this corpus package.','This r2 revision addresses the preserved official-r1 native REQUEST CHANGES\nreport; historical GPT-6/Fable review records exist but do not approve these new\nbytes. Revised-candidate reviews and implementation remain pending.')
s=s.replace('immutable; refresh-03 supplies current author bindings and is not a review verdict.','immutable; official-r2-preparation supplies refreshed author bindings and is\nnot a review verdict. At each official freeze regenerate all in-change normative\ninventories/maps/context manifests, and preserve prior versions as historical\nsnapshots; a stale manifest cannot serve as the current implementation map.')
p.write_text(s)
# Freeze exact existing literal rows as the planning authoritative payload; no predicate edits.
import json
rows=[l for l in s.splitlines() if l.startswith('| `R-')]
rules=[]
for row in rows:
 fields=[x.strip() for x in row.strip('|').split('|')];ident,facet=fields[0].split(' / ')
 rules.append({'id':ident.strip('`'),'facet':facet,'positive_evidence':fields[1],'insufficient_alone':fields[2],'literal_markdown_row':row})
(P/'rules.json').write_text(json.dumps({'rule_set':'evidence-adjudication/1','status':'planning_predicates_not_accepted_adjudications','authority':'This literal payload; design table must match each literal_markdown_row exactly.','common_constraints':['direct_service','exact_identity_operation_time_scope','no_dependency_or_parent_inheritance','historical_unit_applicability_required','uniform_selected_interpretation'],'rules':rules},indent=2)+'\n')
p=P/'proposal.md';s=p.read_text().replace('- Add reusable, versioned evidence rules and an append-only adjudication overlay','- Add authoritative literal evidence rules, uniformly reviewed interpretation\n  records, historical-primary and separate scoped source-claim projections, and\n  mandatory historical unit applicability in an append-only adjudication overlay')
s=s.replace('`9908d9b56be2d5ed2b58a16fa8d28b23f33733ff`. Sprint 10 planning remains pending\nits substantive native Fable review; its implementation gate is closed. No\ncorpus planning acceptance or implementation is implied.','`9908d9b56be2d5ed2b58a16fa8d28b23f33733ff`. Sprint 10 independently passed its\nplanning gate and is being implemented; corpus implementation remains ungated.\nThe preserved corpus official-r1 Fable review requested changes; this author r2\nrevision addresses those findings but awaits new independent acceptance.')
s=s.replace('none is an untouched holdout. Refresh-03 author evidence preserves these boundaries\nand the earlier author artifacts before the official candidate is frozen.','none is an untouched holdout. Official-r2-preparation preserves every modified\nplan before-image and regenerates the current inventories. It defines empty-body\nnormalization, retained extraction bytes, bounded target accounting, terminal\nqueue states, deterministic supersession and enforceable offline checks. No\nexisting packet is accepted by import, and source-only support cannot close a\nhistorical disagreement. All factual adjudications remain pending.')
p.write_text(s)
