from pathlib import Path
import json
R=Path('/home/charl/defiformal');O=Path(__file__).resolve().parent;C=R/'openspec/changes/claims-liability-lifecycle'
def save(n,x): (O/n).write_text(json.dumps(x,indent=2)+'\n')
caps=[
('fixed-claim-state',[
('CS01','Represent fixed dimensioned obligations','Claims SHALL retain debtor, current creditor, domain, asset, fixed positive face, remaining/paid/waived quantities, due, unconditional condition, status, default history and revision with executable finite validation.',[
('S01','a valid fixed loan is created','the fresh row has positive face=remaining, paid=waived=0, an explicit unconditional condition and active status'),
('S02','an imported row violates decomposition or status/clock consistency','initial admission identifies the first invalid row and ordered reason without running a command')]),
('CS02','Retain permanent identities and tombstones','Claims SHALL use append-only positional ClaimIds and preserve every existing row identity, including terminal entries.',[
('S03','a paid or forgiven row is followed by a new loan','the new ID is the previous list length and the old tombstone remains exact'),
('S04','a command targets a terminal or nonexistent row','it refuses without deleting, reusing or reactivating an ID')]),
('CS03','Bound the instrument and initial assumptions','Claims SHALL distinguish validated imported obligations from funded-origin traces and SHALL exclude unsupported conditional, indexed, interest and asynchronous behavior.',[
('S05','a valid imported nonempty store is admitted','validity is not described as proof of historical funding'),
('S06','conditional payoff, legal default or external truth is discussed','it remains an explicit separate obligation; an arbitrary Boolean does not certify it')])]),
('authorized-claim-lifecycle',[
('CL01','Bind ownership and authenticated actors','Lifecycle authorization SHALL use the trusted boundary principal/domain and current row ownership, with separate unchanged kernel capabilities for cash movement.',[
('L01','a debtor invokes funded creation or repayment with valid cash authority','the debtor role and actual invoke/debit permissions are both checked'),
('L02','a nondebtor pays or a noncreditor transfers, extends, defaults or forgives','the exact role refusal preserves public state even if the actor has broad ledger/admin permissions')]),
('CL02','Transfer and extend without inventing liability','Transfer SHALL change only creditor/revision and extension SHALL change only an active claim due/revision under the declared forbearance rules.',[
('L03','the current creditor transfers an active or defaulted claim','the debtor, face, amounts, due, condition and default history remain unchanged'),
('L04','the creditor extends an active due date','newDue is strictly later and at least now; principal and cash remain exact'),
('L05','a defaulted claim is extended or a transfer names the debtor','the action refuses; no cure, self-payment claim or debtor novation occurs')]),
('CL03','Distinguish forgiveness from paid discharge','Discharge by a creditor SHALL explicitly forgive the entire remaining amount, recording waived rather than paid and publishing no cash movement.',[
('L06','the creditor forgives an active or defaulted remainder','remaining becomes0, waived increases by the old remainder, paid is unchanged and status is terminal forgiven'),
('L07','forgiveness is reported as repayment','the full status/paid/waived/receipt oracle rejects that report')]),
('CL04','Record default without debt disappearance','Default SHALL require the current creditor, active status and now strictly greater than due; it SHALL preserve every monetary amount and retain immutable default history.',[
('L08','default is requested exactly at due and one tick later','the first refuses and the second records default without erasing debt'),
('L09','a defaulted claim receives partial or complete late repayment','payment remains allowed and defaultAt survives partial/defaulted or terminal/paid status')]),
('CL05','Enforce revisions time and ordered refusal','Existing-row commands SHALL check expectedRevision and explicit ordered admission; lifecycle time SHALL be nondecreasing without strengthening legacy time semantics.',[
('L10','a stale row revision and unauthorized actor occur together','revision refusal wins under the declared precedence'),
('L11','a lifecycle boundary time decreases','clock refusal precedes lookup; legacy execution retains its old timestamp behavior')])]),
('ledger-backed-claim-payments',[
('CP01','Fund creation with actual registered execution','Loan creation SHALL append a liability only after actual Composition execution transfers the exact principal from creditor to debtor with zero supply and no other effects.',[
('P01','a debtor borrows10 from a funded creditor','one command publishes cash movement and exactly one face10 claim'),
('P02','funding is missing or has the wrong amount or source','the candidate receipt fails exact shape and neither funds nor a claim are published')]),
('CP02','Repay the current creditor with actual cash','Repayment SHALL require 0<amount≤remaining and actual debtor-to-current-creditor movement before atomically updating paid and remaining.',[
('P03','10 outstanding is repaid4 then6','the first leaves remaining6/paid4 and the second yields terminal paid with paid10 and actual cash restored'),
('P04','the creditor changed before repayment','cash reaches the current creditor; historical payments retain their own event creditor'),
('P05','repayment is zero, negative or exceeds remaining','the ordered amount refusal preserves ledger and liability')]),
('CP03','Reject substituted effects and supply','Payment validation SHALL compare the actual invoked receipt at every cell and every domain/asset supply entry, preserving kernel failure distinctions.',[
('P06','a successful inner invocation pays from another party, to another creditor, or in another asset','paymentMismatch retains the tentative diagnostic and publishes no state change'),
('P07','a successful inner invocation adds supply or an extra balanced transfer','exact all-cell/supply checks reject it despite a plausible headline payment'),
('P08','the registered invocation refuses for authority or insufficient funds','the exact underlying Composition failure is retained without a claim mutation')]),
('CP04','Publish cash and claims together','An accepted lifecycle money command SHALL publish its actual result and claim mutation once; every refusal SHALL retain entry public state and successful history.',[
('P09','execution succeeds but subsequent payment validation fails','public world, claims, outputs and events remain at entry while the failure records the actual tentative result'),
('P10','cash or claim publication is individually omitted','the independently expected full-state oracle rejects the incomplete result')])]),
('claim-trace-preservation',[
('CT01','Preserve actual ordered cursor observations','The cursor SHALL retain full world/capability/claim state, actual events/receipts/outputs, absolute index and exact failure; every successful command increments index and a failed suffix is inert.',[
('T01','metadata and payment commands share a sequence','metadata consumes an absolute index without inventing outputs; payment uses the actual prior output history'),
('T02','a command refuses after a successful prefix','only located failure is added and every subsequent command is skipped'),
('T03','continueRun is split at an arbitrary entry cursor','append equality preserves the whole cursor without reinitialization')]),
('CT02','Prove authorized no-disappearance','Reachability SHALL be generated by actual command equations and SHALL prove row presence, immutable fields, status transitions, other-row framing and authorized accounting changes.',[
('T04','a reachable existing liability decreases','an actual debtor payment or creditor forgiveness accounts for exactly that decrease'),
('T05','default, transfer, extension or legacy execution occurs','remaining/paid/waived stay unchanged and every other row remains exact'),
('T06','a trace starts with empty claims and creates loans','every appended row has an actual funding-event witness, not merely an assumed well-formed row')]),
('CT03','Prove conservative projection at the right scope','Legacy-only programs embedded with empty claims SHALL project exactly to existing Composition continuation; mixed lifecycle traces SHALL retain their distinct indexing and failure semantics.',[
('T07','an arbitrary legacy cursor including prior failure is embedded','legacy continuation preserves its exact old events, history, world, index and failure'),
('T08','a mixed lifecycle trace is projected','only proved local world/payment/stutter facts are claimed; metadata indices and paymentMismatch are not silently erased')])]),
('claim-lifecycle-evidence',[
('CE01','Use independent full-state financial fixtures','The evidence SHALL provide24 named literal fixtures with complete finite state/claim/receipt expectations and distinct authority, default, amount, payment and observation negatives.',[
('E01','the fixture suite executes','every ID is nonempty, unique and backed by a literal expected result outside the mutated runtime path'),
('E02','a wrong debtor, default erasure, overpayment or missing ledger payment candidate executes','the relevant false financial oracle detects it; another guard or compiler failure is not mislabelled detection')]),
('CE02','Run actual mutations and honest CLI controls','The gate SHALL execute20 named source mutations plus separately enumerated actual CLI controls with exact source/tool/output identity and exit0/1/3 semantics.',[
('E03','an actual compiled mutant produces a false named result','the gate records semantic detection separately from successful process exit'),
('E04','source drift, timeout, malformed/empty/duplicate evidence or output-path conflict occurs','the attempt is blocked and preserved without overwriting prior evidence or awarding mutant credit')]),
('CE03','Require proof inventories and independent accepted gates','Implementation SHALL require the frozen nonauthor GPT-6/native Fable planning gate and final native Grok/Fable source/evidence review, with actual proof statements and explicit dependencies.',[
('E05','only this author draft or an unavailable reviewer exists','implementation and acceptance remain false'),
('E06','all scoped checks and required reviews pass','the parent records exact delivery while conditional claims, async lifecycle, integer/deployment/provenance work remain open')])])]
scenarios=[]
for cap,reqs in caps:
 lines=['## Purpose','','Defines the bounded fixed-claim lifecycle contract described in design.md.','','## ADDED Requirements','']
 for rid,title,body,ss in reqs:
  lines+=['### Requirement: '+rid+' '+title,'',body,'']
  for sid,when,then in ss:
   lines+=['#### Scenario: '+sid+' '+when[0].upper()+when[1:],'','- **WHEN** '+when,'- **THEN** '+then+'.','']
   scenarios.append({'id':sid,'capability':cap,'requirement':rid,'when':when,'then':then,'evidence_status':'pending_implementation','acceptance_evidence':[]})
 p=C/'specs'/cap/'spec.md';p.parent.mkdir(parents=True,exist_ok=True);p.write_text('\n'.join(lines))
save('scenario-map.json',{'status':'author_draft_not_accepted','capabilities':len(caps),'requirements':sum(len(x[1]) for x in caps),'scenarios':scenarios})
fixtures=[
('F01','funded creation','empty claims; home USD alice0,bob20,carol10','alice creates loan10 from bob at time1 due10','alice10,bob10,carol10; id0 active face10/rem10/paid0/waived0 rev0 created1 due10','S01 P01'),
('F02','partial repayment','F01 success','alice repays4 at time2 revision0','alice6,bob14; id0 rem6/paid4/waived0 active rev1','P03'),
('F03','full repayment','F02 success','alice repays6 at time3 revision1','alice0,bob20; id0 rem0/paid10/waived0 discharged paid rev2','P03'),
('F04','transfer and current creditor','F01 success','bob transfers id0 to carol at2; alice repays4 at3 with rev1','after transfer all balances unchanged rev1 creditor carol; then alice6,bob10,carol14 rem6 paid4 rev2','L03 P04'),
('F05','due-only amendment','F01 success','bob extends due10 to20 at time2 revision0','all balances/amounts unchanged; due20 rev1 active; extension10 refuses invalidDue','L04'),
('F06','explicit waiver','F02 success','bob discharges at time3 revision1','alice6,bob14; rem0 paid4 waived6 terminal forgiven rev2','L06 L07'),
('F07','default due boundary','F01 success in two independent cursors','bob defaults at10 versus11','time10 refuses notDue; time11 defaulted rem10 paid0 waived0 rev1 defaultAt11; identical cash','L08'),
('F08','late default repayment','F07 defaulted success','alice repays4 at12 rev1 then6 at13 rev2','first alice6,bob14 rem6 paid4 defaulted rev2; then alice0,bob20 paid10 terminal paid rev3; defaultAt11 both','L09'),
('F09','wrong debtor actor','F01 success; carol has valid inner invoke and debit(home,alice,usd) grants; inner template pays alice→bob independent of caller','carol attempts id0 repayment4 revision0 at2','unauthorizedActor before inner call; all public fields retained','L02 E02'),
('F10','unauthorized creditor actions','F01 success; admin broad cash grants','admin independently transfer/extend/default/discharge at11 revision0','unauthorizedActor for each command; no cash/row change','L02'),
('F11','amount boundaries and fractions','F01 success in independent cursors; the overpayment11 cursor has a validated imported world with aliceUSD12 so the kernel can pay11','repay0, -1, 11; companion repay1/2','nonPositive,nonPositive,overpayment refusals; fraction success alice19/2,bob21/2 rem19/2 paid1/2 rev1','P05'),
('F12','missing payment','F01 success; actual authorized zero-effect invocation','repay4 using that invocation','inner success then paymentMismatch; rem10 paid0 and alice10,bob10 public; actual zero receipt only diagnostic','P02 P09'),
('F13','wrong cash source','F01 success; alice is actually authorized to debit carol USD','repay4 using carol→bob transfer4','inner cash candidate alice10,bob14,carol6; paymentMismatch public F01 unchanged','P06'),
('F14','wrong destination','F01 success; valid alice→carol USD invocation','repay4 to carol while creditor bob','candidate alice6,bob10,carol14; paymentMismatch retains F01 public','P06'),
('F15','wrong asset','F01 success; home EUR alice8,bob9 with valid debit grant','repay4 via EUR alice→bob','candidate EUR4/13; paymentMismatch; USD debt and public EUR8/9 unchanged','P06'),
('F16','supply and extra effects','F01 success; inner authority includes exact changeSupply and donor debit','repay4 with extra mint1 to carol; independent sibling adds balanced EUR alice→bob1','both inner success, then paymentMismatch; distinguish nonzero supply from zero-supply extra-cell movement','P07'),
('F17','underlying failures','F01 success with alice cash independently set2 in valid imported world','repay4 with correct transfer; companion omit debit grant on funded world','payment(kernel insufficientFunds) versus payment(kernel unauthorizedDebit); no liability reduction','P08'),
('F18','tombstone permanence','F03 paid success; independent F06 forgiven success','repay/default/transfer/discharge terminal id0; then fresh loan5 in a fresh nonfailed cursor from each state','terminal refusals; new loan appends id1, keeps id0 exact; never reuses0','S03 S04'),
('F19','legacy conservative embedding','arbitrary nonempty Composition prefix; empty claims; lifecycle clock0','issue/revoke/invoke legacy commands, including decreasing boundary times and an already-failed cursor','exact old Composition cursor projection; empty claims and clock0; no new time refusal','T07 L11'),
('F20','absolute history and failure suffix','F01 variant with home adminUSD4, a declared output port snapshotting that unchanged cell at loan index0; configure payment input using its actual output','metadata transfer at index1 then repay at index2 from output index0; wrong-shape repayment followed by another valid debtor repayment4','actual index2/history resolves; failed variant retains successful prefix/index and skips the valid repayment; no outputs published from diagnostic','T01 T02 T03'),
('F21','stale version and clock precedence','F04 transferred state rev1, time2','repay expectedRevision0 with wrong actor at3; authorized alice stale-revision sibling; independent unknownid command at1','revision mismatch first; time regression before lookup; public state unchanged','L10 L11'),
('F22','default retention through transfer and forgiveness','F07 defaulted success','bob transfer to carol at12; carol discharge at13; independent extendDue at12','defaultAt11 retained terminal forgiven with waived10 paid0 and cash unchanged; extension refuses wrongStatus','L03 L05 L06'),
('F23','two IDs and imported invalidity','F01 id0 plus funded id1 of5 from carol to alice; initial two valid rows','repay id0 amount4; independent malformed imported row1 with both negative remaining and bad decomposition','id1 exact; initial first-invalid row1/nonnegative reason; failed start runs no command','S02 S05 T04 T05 T06'),
('F24','atomic publication and actor binding','empty claims and F01 success as separate initial states','createLoan10 using zero-effect funding; repay4 actual transfer with forged claimedActor','fundingMismatch leaves no cash/claim; payment(kernel actorMismatch) leaves F01 exact; success sibling publishes both pieces','P02 P09 P10')]
save('fixtures.json',{'status':'planned_not_executed','count':len(fixtures),'universe':{'parties':['alice','bob','carol','admin'],'assets':['usd','eur'],'domains':['home','away']},'full_state_convention':'Every oracle enumerates all16 cells. Base homeUSD alice0 bob20 carol10 admin0; homeEUR alice8 bob9 carol0 admin0; awayEUR carol11; every other cell0. Fields not explicitly changed remain byte/value exact. Each fixture records the full capability list, claim list, lifecycle clock, actual command/event/index/pre/post/receipt/output sequence and exact failure including tentative diagnostics. Required malformed-source siblings are separate independent runs, not continuations after sticky failure. Fixtures must construct valid registry/catalog/footprints and actual capability permission for wrong-shape inner successes. Broad permission is a test precondition, never lifecycle ownership. F20 compares an independently expected value4 against the actual OutputPort balance snapshot; outputs are not arbitrary literal-return functions.','fixtures':[{'id':i,'name':n,'initial':a,'commands':b,'expected':c,'scenarios':s.split(),'status':'planned_not_executed'} for i,n,a,b,c,s in fixtures]})
mutants=[
('M01','loan append omitted','Execution.createLoan success drops claim append','F01','cash moves but row missing'),('M02','funding world omitted','Execution.createLoan returns old world with new claim','F01','liability exists without funded10'),('M03','repayment world omitted','Execution.repay returns old world after amount update','F02','remaining6 with unchanged cash'),('M04','payment shape always accepts','Payment exact effect validator returns true','F12','zero cash credited as repayment'),('M05','debtor role omitted','Lifecycle.repay omits actor=debtor','F09','authorized carol inner movement from alice incorrectly accepted; fixture supplies permission'),('M06','creditor role omitted','Lifecycle.discharge omits actor=current creditor','F10','admin forgives someone else liability'),('M07','default erases debt','Lifecycle.default sets remaining0 and waived=face-paid','F07','default monetary amounts change'),('M08','due comparison inclusive','Lifecycle.default now>due becomes now≥due','F07','default accepted exactly at10'),('M09','repayment amount upper bound omitted','Lifecycle.repay removes amount≤remaining guard','F11','overpayment11 executes and produces wrong result/invalid negative remaining'),('M10','wrong creditor source','Payment repayment destination mistakenly uses claim.debtor instead of claim.creditor','F04','legitimate payment to current carol incorrectly refused'),('M11','ignore source cell','Payment validator accepts creditor credit q with arbitrary balancing source','F13','carol payment reduces alice debt'),('M12','ignore asset','Payment validator tests matching amount and owners on an arbitrary asset','F15','EUR cash reduces USD debt'),('M13','ignore supply','Payment validator restricts comparison to debtor/creditor cells and omits all supply/other-cell checks','F16','extra mint accepted; coupled weakening explicitly one mutation'),('M14','forgiveness mislabeled paid','Lifecycle.discharge increments paid rather than waived and sets terminal paid','F06','waiver reported as repayment'),('M15','tombstone removed','Lifecycle final repayment removes row instead of retaining closed row','F18','id0 disappears or later ID reused'),('M16','default history cleared','Lifecycle final repayment sets defaultAt=none','F08','late-paid terminal forgets prior default'),('M17','stale revision ignored','Lifecycle lookup omits expectedRevision comparison','F21','use authorized actor sibling to isolate stale revision acceptance'),('M18','diagnostic world published','Execution paymentMismatch copies tentative world into public state','F13','cash leaks despite failed claim transaction'),('M19','metadata does not consume index','Execution success increments index only for monetary commands','F20','payment uses wrong absolute index/history'),('M20','failure cleared by next command','Execution.advance retries after located failure','F20','failed suffix valid debtor repayment executes')]
save('planned-mutations.json',{'status':'planned_not_executed','count':len(mutants),'limits':'Exact source snippets/anchors and all successful/negative fixture instances must be frozen at implementation. These are changes to actual new runtime code, not source grep or compile-only credit. M10 substitutes two existing same-typed fields and needs no invented original-creditor field. M13 deliberately weakens the combined exact-effect/supply predicate: supply omission alone is redundant under full-cell equality plus accepted kernel accounting, so no independent detection is claimed for that omission.','mutants':[{'id':i,'name':n,'actual_source_change':x,'oracle_fixture':f,'expected_detection':d,'status':'planned_not_executed'} for i,n,x,f,d in mutants]})
print(len(caps),sum(len(x[1]) for x in caps),len(scenarios),len(fixtures),len(mutants))
