from pathlib import Path
import json,hashlib,datetime
H=Path('/home/charl');R=H/'defiformal';A=R/'review/semantic-kernel/strategy-audit-20260908';P=Path('review/semantic-kernel/program-loop-20260908');now=datetime.datetime.now(datetime.timezone.utc).isoformat();old=json.loads((R/P/'WORKSTATE.json').read_text());snap=A/'evidence/workstate-history';snap.mkdir(parents=True,exist_ok=True)
def sha(b):return hashlib.sha256(b).hexdigest()
def save(p,x):p.write_text(json.dumps(x,indent=2,ensure_ascii=False)+'\n')
roots=[R]+sorted(p for p in H.glob('defiformal-wt-*-grok-gpt6-2026090*') if (p/P/'WORKSTATE.json').exists());history=[]
for r in roots:
 b=(r/P/'WORKSTATE.json').read_bytes();digest=sha(b);sp=snap/(digest+'.json')
 if not sp.exists():sp.write_bytes(b)
 history.append({'worktree':str(r),'original_sha256':digest,'snapshot':str(sp)})
save(A/'evidence/workstate-history-index.json',history)
def location(lane):return str(H/f'defiformal-wt-{lane}-grok-gpt6-20260908')
lanes=[]
def lane(id,where,phase,accepted,candidate,next,depends=[],findings=[]):lanes.append({'id':id,'worktree':where,'phase':phase,'accepted_scope':accepted,'candidate':candidate,'next_gate':next,'depends_on':depends,'open_findings':findings,'whole_scope_delivered':False})
lane('M3',str(R),'delivered','35 tasks accepted and delivered',{'source_commit':'94f70e502c75132656bd0902a17be60ca45ab1c2','delivery_commit':'a12b7cac05a818cc8d35c2ca440b7170a2807e92'},'Reuse exact accepted dependencies');lanes[-1]['whole_scope_delivered']=True
freezes={r['scope'][0]:r for r in json.loads((A/'evidence/terminal-freezes.json').read_text())}
def frozen(match):
 r=next(v for k,v in freezes.items() if match in k);return {'archive':r['artifacts'][0]['path'],'sha256':r['artifacts'][0]['sha256'],'native_session_id':r['native_session_id'],'process_exit':r['exit_code'],'native_stop_reason':r['stop_reason'],'acceptance':'not established by freeze'}
lane('M4',location('sprint12'),'review_open','Official plan and six-module runtime foundation only',frozen('compatible-recovery-r2'),'Independent generic recovery review; then contracts/monitors/fullfixtures/mutations and coherent delivery',['M3'])
lane('M5',str(H/'defiformal-wt-sprint11-grok-gpt6-20260907'),'provisional_only','Provisional planning with limits',old.get('m5_m6_recovery',{}),'Official refresh after delivered M4; do not start speculative implementation',['M4'])
lane('M6',str(R),'planned_not_started','No new implementation accepted',{},'Refresh actual M4/M5 dependencies before official plan/implementation',['M4','M5'])
lane('capability',location('lifecycle'),'review_open','Official r2 planning; no whole foundation acceptance',{'archive':location('lifecycle')+'/'+str(P/'native-worker/capability-foundation-r2-stage.tar.gz'),'sha256':'7fc31431a2b5d6f0198f8a182fcd31a35b90d323c076c1c0bc000c9a3b30c52a'},'Review initialized query/tombstone proofs and actual check inventory, then Isolation/full gates',[],['CF2 reported22old vs actual23; verify newcount','Verify CF1 actual revoked-ID discrimination'])
lane('claims',location('claims'),'partial_cancelled','Official r2 and runtime foundation accepted; generic proof gate open',frozen('generic-proofs-r1'),'Inspect partial PaymentSoundness/Conservative/Preservation exact bytes; finish only chosen bounded obligation',[],['max_turns_reached; cancelled native result is not completion'])
lane('corpus',location('corpus'),'repair_required','Tooling r7, exposure ledger,169-work/75-identity skeleton only',{'archive':location('corpus')+'/'+str(P/'native-worker/corpus-production-inputs-r2-stage.tar.gz'),'sha256':'a119b4ae63c81bc59f1b8e0c509a3ff6ec53e1a112f838612c5a2c522407614c'},'Repair source substance and exact capture/derived/span binding then focused independent review',[],['Audit04 challenge403 substantive misclassification','Audit04 CoW derived locator applied to raw404 sibling','Original whole r2 review interrupted; strategic finding is not full acceptance'])
lane('historical',location('historical'),'repair_required','Scoped Lean/data/export/tooling/integration only',{'archive':location('historical')+'/'+str(P/'native-worker/historical-claim-closure-r2-stage.tar.gz'),'sha256':'26ade3b9544924e782264e9fbcf37c93c88fb078cacbd7ab1098478e3ed4c0a6'},'Repair exact H02/H12 authority links and like-for-like measurement table; finish occurrence review',[],['Convex review does not accept Independence/Interface','R-only and R-intersect-W measurements conflated/omitted','Original whole r2 review interrupted'])
lane('certificates',location('certificates'),'review_open','No official r2 planning acceptance or implementation',frozen('certificates/planning'),'Review repaired first-order Typed/sequential grammar/results/fixtures/projection/correspondence; implement only accepted supported subset')
lane('liquidity',location('liquidity'),'repair_required','Pinned source readiness only',{'archive':location('liquidity')+'/'+str(P/'native-worker/liquidity-official-planning-r1-stage.tar.gz'),'sha256':'e1cd08f9f8a843355f1b249a013c9de0d29e7e1ebf1d5a3e8716d6d7621baf77'},'Resolve source sum-overflow oracle and mutant positive controls before library plan acceptance',[],['Audit04 independently reproduced next-price mismatch','M09 changes protectedF28 amountIn2to1','Original full planning review interrupted'])
lane('atlas',location('atlas'),'review_open','Historical layout prioracceptances only',frozen('atlas/implementation'),'Review existing238-check candidate; park newfeatures until API/schema stable',[],['Author238checks not independentacceptance','Search-list/badges/zoom/print/find andscientificrefresh remain'])
lane('reporting_gate',location('honest-gate'),'review_open','Historical gate contract; new repair acceptance open',frozen('honest-gate/implementation'),'Review single-source patch + clean210/0 record; deliver coherent fix if accepted')
for id,next in [('async','Select concrete workflow; freeze lifecycle/finality/replay/compensation contracts'),('remaining_libraries','Select next family after substantive two-case reuse gate'),('fidelity_adapters','Implement selected source/model boundary and explicitly scoped comparisons/refinements'),('untouched_evaluation','Freeze platform and audited exposure policy before independent case selection'),('publication','Publish claims reflecting exact accepted/model/bounded/source-refined levels')]:lane(id,str(R),'future_open','No whole scope completion claimed',{},next)
state={'schema_version':2,'updated_utc':now,'user_priority':'A broadly reusable verification platform and libraries','current_task':'Five-angle strategy audit, graph refresh, safe cleanup and iterated plan','execution_state':'implementation_dispatch_held_for_strategy_review','whole_program_status':'open','whole_program_objective':old['objective'],'worker':'native Grok4.6','checker':'independent GPT6','no_foreman':True,'scope_acceptance_and_delivery_are_separate':True,'process_liveness':'No process liveness inferred from saved handles. Five last worker terminals preserved in evidence/terminal-freezes.json.','review_capacity':'Five current strategy reviewers succeeded; earlier three interrupted package reviews retain no final verdict. Strategy reviews do not replace full package gates.','plan':str(A/'PLAN.md'),'graph':str(R/'graphify-out/strategy-audit-20260908/graph.json'),'historical_state_index':str(A/'evidence/workstate-history-index.json'),'lanes':lanes}
save(A/'CURRENT.json',state)
router={'schema_version':2,'status':'strategy_review_hold','canonical_current_state':str(A/'CURRENT.json'),'refined_plan':str(A/'PLAN.md'),'whole_program_status':'open','worker':'native Grok4.6','checker':'GPT6','no_foreman':True,'instruction':'Read canonical_current_state. Old multi-lane fields are historical snapshots, not current dispatch instructions. Do not resume feature implementation during the strategy decision.','historical_state_index':str(A/'evidence/workstate-history-index.json'),'updated_utc':now}
for r in roots:save(r/P/'WORKSTATE.json',{**router,'local_worktree':str(r)})
print('One canonical current state;',len(roots),'thin routers;',len(lanes),'lane rows;',len(list(snap.glob('*.json'))),'unique preserved old states')
