import DefiKernel.Nary.FundedEnabledness
#print axioms DefiKernel.Nary.FundedEnabledness.f10_catalog_valid
#print axioms DefiKernel.Nary.FundedEnabledness.f10_bounds_producer
#print axioms DefiKernel.Nary.FundedEnabledness.f10_bounds_deposit1
#print axioms DefiKernel.Nary.FundedEnabledness.f10_bounds_deposit2
#print axioms DefiKernel.Nary.FundedEnabledness.prepare_producer
#print axioms DefiKernel.Nary.FundedEnabledness.prepare_consumer
#print axioms DefiKernel.Nary.FundedEnabledness.prepare_deposit1
#print axioms DefiKernel.Nary.FundedEnabledness.prepare_deposit2
#print axioms DefiKernel.Nary.FundedEnabledness.executeStep_invoke_ok
#print axioms DefiKernel.Nary.FundedEnabledness.producer_effect
#print axioms DefiKernel.Nary.FundedEnabledness.producer_extract
#print axioms DefiKernel.Nary.FundedEnabledness.producer_invoke_auth
#print axioms DefiKernel.Nary.FundedEnabledness.producer_valid
#print axioms DefiKernel.Nary.FundedEnabledness.producer_execute
#print axioms DefiKernel.Nary.FundedEnabledness.budget_asset
#print axioms DefiKernel.Nary.FundedEnabledness.producer_snapshots
#print axioms DefiKernel.Nary.FundedEnabledness.f10_producer_enabled
#print axioms DefiKernel.Nary.FundedEnabledness.consumer_args
#print axioms DefiKernel.Nary.FundedEnabledness.consumer_invoke_auth
#print axioms DefiKernel.Nary.FundedEnabledness.consumer_debit_auth
#print axioms DefiKernel.Nary.FundedEnabledness.amount_le_decide
#print axioms DefiKernel.Nary.FundedEnabledness.amount_zero_le_six
#print axioms DefiKernel.Nary.FundedEnabledness.consumer_guard
#print axioms DefiKernel.Nary.FundedEnabledness.vaultC_tuple
#print axioms DefiKernel.Nary.FundedEnabledness.recipientC_tuple
#print axioms DefiKernel.Nary.FundedEnabledness.donor1C_tuple
#print axioms DefiKernel.Nary.FundedEnabledness.donor2C_tuple
#print axioms DefiKernel.Nary.FundedEnabledness.consumer_caller
#print axioms DefiKernel.Nary.FundedEnabledness.consumer_parties_ctx
#print axioms DefiKernel.Nary.FundedEnabledness.consumer_resolve_required
#print axioms DefiKernel.Nary.FundedEnabledness.consumer_resolve_declared
#print axioms DefiKernel.Nary.FundedEnabledness.consumer_resolve_writes
#print axioms DefiKernel.Nary.FundedEnabledness.consumer_delta_eval
#print axioms DefiKernel.Nary.FundedEnabledness.consumer_evaluate
#print axioms DefiKernel.Nary.FundedEnabledness.consumer_extract
#print axioms DefiKernel.Nary.FundedEnabledness.vaultC_ne_recipientC
#print axioms DefiKernel.Nary.FundedEnabledness.consumer_effect
#print axioms DefiKernel.Nary.FundedEnabledness.consumer_stateReadsOK
#print axioms DefiKernel.Nary.FundedEnabledness.consumer_envReadsOK
#print axioms DefiKernel.Nary.FundedEnabledness.consumer_domainOK
#print axioms DefiKernel.Nary.FundedEnabledness.consumer_debitsOK
#print axioms DefiKernel.Nary.FundedEnabledness.consumer_suppliesOK
#print axioms DefiKernel.Nary.FundedEnabledness.consumer_accountingOK
#print axioms DefiKernel.Nary.FundedEnabledness.consumer_writesOK
#print axioms DefiKernel.Nary.FundedEnabledness.consumer_nonneg
#print axioms DefiKernel.Nary.FundedEnabledness.consumer_valid
#print axioms DefiKernel.Nary.FundedEnabledness.consumer_execute
#print axioms DefiKernel.Nary.FundedEnabledness.consumer_snapshots
#print axioms DefiKernel.Nary.FundedEnabledness.f10_consumer_enabled
#print axioms DefiKernel.Nary.FundedEnabledness.deposit1_args
#print axioms DefiKernel.Nary.FundedEnabledness.deposit2_args
#print axioms DefiKernel.Nary.FundedEnabledness.deposit1_invoke_auth
#print axioms DefiKernel.Nary.FundedEnabledness.deposit1_debit_auth
#print axioms DefiKernel.Nary.FundedEnabledness.deposit2_invoke_auth
#print axioms DefiKernel.Nary.FundedEnabledness.deposit2_debit_auth
#print axioms DefiKernel.Nary.FundedEnabledness.deposit1_caller
#print axioms DefiKernel.Nary.FundedEnabledness.deposit1_parties_ctx
#print axioms DefiKernel.Nary.FundedEnabledness.deposit2_caller
#print axioms DefiKernel.Nary.FundedEnabledness.deposit2_parties_ctx
#print axioms DefiKernel.Nary.FundedEnabledness.deposit1_guard
#print axioms DefiKernel.Nary.FundedEnabledness.deposit2_guard
#print axioms DefiKernel.Nary.FundedEnabledness.deposit1_resolve_required
#print axioms DefiKernel.Nary.FundedEnabledness.deposit1_resolve_declared
#print axioms DefiKernel.Nary.FundedEnabledness.deposit1_resolve_writes
#print axioms DefiKernel.Nary.FundedEnabledness.deposit2_resolve_required
#print axioms DefiKernel.Nary.FundedEnabledness.deposit2_resolve_declared
#print axioms DefiKernel.Nary.FundedEnabledness.deposit2_resolve_writes
#print axioms DefiKernel.Nary.FundedEnabledness.deposit1_evaluate
#print axioms DefiKernel.Nary.FundedEnabledness.deposit2_evaluate
#print axioms DefiKernel.Nary.FundedEnabledness.deposit1_extract
#print axioms DefiKernel.Nary.FundedEnabledness.deposit2_extract
#print axioms DefiKernel.Nary.FundedEnabledness.donor1C_ne_vaultC
#print axioms DefiKernel.Nary.FundedEnabledness.donor2C_ne_vaultC
#print axioms DefiKernel.Nary.FundedEnabledness.deposit1_effect
#print axioms DefiKernel.Nary.FundedEnabledness.deposit2_effect
#print axioms DefiKernel.Nary.FundedEnabledness.deposit1_stateReadsOK
#print axioms DefiKernel.Nary.FundedEnabledness.deposit1_envReadsOK
#print axioms DefiKernel.Nary.FundedEnabledness.deposit1_domainOK
#print axioms DefiKernel.Nary.FundedEnabledness.deposit1_debitsOK
#print axioms DefiKernel.Nary.FundedEnabledness.deposit1_suppliesOK
#print axioms DefiKernel.Nary.FundedEnabledness.deposit1_accountingOK
#print axioms DefiKernel.Nary.FundedEnabledness.deposit1_writesOK
#print axioms DefiKernel.Nary.FundedEnabledness.deposit2_stateReadsOK
#print axioms DefiKernel.Nary.FundedEnabledness.deposit2_envReadsOK
#print axioms DefiKernel.Nary.FundedEnabledness.deposit2_domainOK
#print axioms DefiKernel.Nary.FundedEnabledness.deposit2_debitsOK
#print axioms DefiKernel.Nary.FundedEnabledness.deposit2_suppliesOK
#print axioms DefiKernel.Nary.FundedEnabledness.deposit2_accountingOK
#print axioms DefiKernel.Nary.FundedEnabledness.deposit2_writesOK
#print axioms DefiKernel.Nary.FundedEnabledness.deposit1_nonneg
#print axioms DefiKernel.Nary.FundedEnabledness.deposit2_nonneg
#print axioms DefiKernel.Nary.FundedEnabledness.deposit1_valid
#print axioms DefiKernel.Nary.FundedEnabledness.deposit2_valid
#print axioms DefiKernel.Nary.FundedEnabledness.deposit1_execute
#print axioms DefiKernel.Nary.FundedEnabledness.deposit2_execute
#print axioms DefiKernel.Nary.FundedEnabledness.deposit1_snapshots
#print axioms DefiKernel.Nary.FundedEnabledness.deposit2_snapshots
#print axioms DefiKernel.Nary.FundedEnabledness.f10_deposit1_enabled
#print axioms DefiKernel.Nary.FundedEnabledness.f10_deposit2_enabled
