import json,hashlib,re,subprocess
from pathlib import Path
from datetime import datetime,timezone
R=Path('/home/charl/defiformal');base=R/'review/semantic-kernel/corpus-provenance-adjudication/source-research';batch=base/'batch-04-edgex-jupiter-pendle';now=lambda:datetime.now(timezone.utc).isoformat();h=lambda b:hashlib.sha256(b).hexdigest()
def js(p):return json.loads(p.read_text())
def bind(p,pointer=None):
 b=p.read_bytes();d={'path':str(p.relative_to(R)),'sha256':h(b),'bytes':len(b)}
 if pointer is not None:d['pointer']=pointer
 return d
def write(p,d):
 if p.exists():
  old=js(p); new=dict(d)
  if 'created_utc' in old and 'created_utc' in new:new['created_utc']=old['created_utc']
  assert old==new,('existing record differs',p)
  return
 with p.open('x') as f:json.dump(d,f,indent=2,ensure_ascii=False);f.write('\n')
triage=js(base/'disagreement-triage.json');before=js(batch/'input-protection-before.json');designpath=R/'openspec/changes/corpus-provenance-adjudication/design.md';rules={}
for i,s in enumerate(designpath.read_text().splitlines(),1):
 m=re.match(r'\| `(R-[^`]+)` / ([^|]+) \| ([^|]+) \| ([^|]+) \|',s)
 if m:rules[m[1]]={'id':m[1],'facet':m[2].strip(),'predicate':m[3].strip(),'insufficient_alone':m[4].strip(),'literal_row':s,'source':{**bind(designpath),'line':i},'status':'proposed reusable rule; not accepted in this research'}
configs=[
 {'folder':'edgex-attester','unit':'unit:lane2:c0:p4','name':'edgeX','ids':['dispute-11'],'dispositions':{'attester':'not_evidenced'},
 'spans':[('starkex-da','mode-selection','Data Availability Committee','p'),('starkex-management','committee-attestation','A Committee contract is a contract','p'),('starkex-management','validium-scope','The committee mechanism is required','p'),('starkex-management','acceptance','The state update is only accepted','p')],
 'claims':[('attester','primary_dependency_statement','StarkEx documentation describes a committee signing possession of state data, with sufficient signatures checked for a proposed state transition.',['starkex-management:committee-attestation','starkex-management:acceptance']),('attester','scope_qualification','That documented committee path applies to Validium; ZK-Rollup mode does not require it. Generic infrastructure therefore does not determine a consuming product’s configuration.',['starkex-management:validium-scope','starkex-da:mode-selection']),('attester','bounded_evidence_gap','The packet has no usable edgeX-specific primary body selecting the committee path or binding its role and acceptance configuration. The disputed unit label remains not_evidenced.',['starkex-management:validium-scope'])],
 'limits':['The edgeX L2-signature page failed retrieval with404 then403. Search-rendered text was not substituted for a retained primary body.','The two retained sources are StarkWare infrastructure documentation, not evidence of an edgeX deployment. In particular one source is explicitly in the StarkEx Spot documentation path, while the corpus unit is a perpetual venue.','The generic committee mechanism fits the attestation predicate if independently bound to the product, but that conditional fact cannot accept the edgeX label.','No deployed contract address, availability verifier, signer threshold, exact product version or chain-state configuration was inspected. Ordinary user signatures would not by themselves establish an attester.'],
 'next':'Retrieve a usable official edgeX architecture/deployment source and bind the actual availability verifier and committee role. Keep generic StarkEx attestation separate from this unestablished product binding.'},
 {'folder':'jupiter-jlp','unit':'unit:lane2:c0:p5','name':'Jupiter Perpetual Exchange / JLP','ids':['dispute-12','dispute-13'],'dispositions':{'asset_management':'supported','allocation':'not_evidenced','redemption':'not_evidenced'},
 'spans':[('pool-account','managed-custodies','An array containing the public keys','tr'),('pool-account','pool-aum','The current AUM value','tr'),('pool-account','weight-limits','tokenWeightageBufferBps','tr'),('pool-account','rebalance-fee','encouraging liquidity providers to rebalance','tr'),('pool-account','liquidity-fee','Fee charged when adding or removing liquidity','tr'),('custody-account','target-weight','targetRatioBps','tr'),('custody-account','owned-assets','The number of tokens owned by the pool','tr'),('custody-account','locked-assets','The number of tokens locked by the pool','tr')],
 'claims':[('asset_management','source_statement','Official developer documents describe tokens managed by the JLP pool, pool-level AUM accounting and custody balances reserved for trader liabilities.',['pool-account:managed-custodies','pool-account:pool-aum','custody-account:owned-assets','custody-account:locked-assets']),('asset_management','inference_under_proposed_rule','Together with explicit liquidity-provider rebalancing and deposit/withdraw controls, this describes management of the pooled LP capital in the JLP path, beyond incidental treasury holdings.',['pool-account:rebalance-fee','pool-account:weight-limits','pool-account:managed-custodies']),('allocation','source_statement','The sources describe target weights, admission limits and fees encouraging liquidity providers to rebalance.',['pool-account:weight-limits','pool-account:rebalance-fee','custody-account:target-weight']),('allocation','bounded_evidence_gap','An incentive and a permitted-weight constraint are not alone a demonstrated operation distributing capital among destinations. This packet does not establish the particular allocation action or actor-selection path.',['pool-account:rebalance-fee','custody-account:target-weight']),('redemption','source_statement','Liquidity removal is described as reducing custody assets and carrying a fee.',['custody-account:owned-assets','pool-account:liquidity-fee']),('redemption','bounded_evidence_gap','The retained account documentation does not establish holder submission of JLP claims for backing settlement, the token consumption/authorization path and its conditions. A withdrawal accounting field is insufficient alone.',['custody-account:owned-assets','pool-account:liquidity-fee'])],
 'limits':['This is two disputed facets and three separate label claims. A proposed asset_management finding does not resolve the allocation/redemption facet.','The supported finding concerns management of the JLP liquidity-provider pool already bundled with this corpus unit, not every Jupiter venue or unrelated Lend/managed-vault product.','The current Custody documentation lists JupUSD along with other assets. No current list, numeric weights, caps or leverage values are asserted to match the historical corpus state.','Two official JLP user-guide routes returned404. The old route and one explicit fallback attempt are preserved separately; neither was counted as a body or replaced with search text.','No named live pool configuration, deployed program revision, LP transaction or actual mint/burn/settlement execution was verified. Targets and fee incentives do not prove autonomous rebalancing or an AMM invariant.'],
 'next':'Independently review the scoped pooled-capital management finding. A later bounded packet should retrieve the actual add/remove-liquidity instruction and JLP claim settlement interface, and the operation distributing exposure; this may settle allocation and redemption separately.'},
 {'folder':'pendle-spot-asset','unit':'unit:lane2:c1:p0','name':'Pendle','ids':['dispute-14'],'dispositions':{'spot_asset':'not_evidenced'},
 'spans':[('architecture','sy-wrapper','SY is a wrapped version','p'),('architecture','pt-claim','PT is a token that represents','p'),('architecture','yt-claim','YT is a token that represents','p'),('standardized-yield','sy-adapter','for heterogeneous yield-bearing tokens','p'),('standardized-yield','sy-redemption','Burns SY shares','p'),('amm','traded-instruments','Liquidity on Pendle V2 comprises','p'),('amm','routing','Auto-routing is built in','p')],
 'claims':[('spot_asset','source_statement','The documented Pendle V2 market trades PT against SY; PT is a maturity principal claim, YT carries pre-maturity yield rights, and SY wraps heterogeneous yield-bearing tokens.',['architecture:pt-claim','architecture:yt-claim','architecture:sy-wrapper','amm:traded-instruments']),('spot_asset','source_statement','SY redemption burns wrapper shares for an eligible output token. Routing may accept or return major assets around the PT/SY workflow.',['standardized-yield:sy-redemption','amm:routing']),('spot_asset','rule_application_limit','Trading a token immediately does not make its economic rights a spot asset: PT/YT’s claim rights defeat the annotation’s tradable-token shortcut. However these generic pages do not classify every concrete SY wrapper or routed output as the unit’s exposed instrument.',['architecture:pt-claim','architecture:yt-claim','standardized-yield:sy-adapter']),('spot_asset','bounded_evidence_gap','Without a specific market/instrument boundary and current ownership/control rights, the broad unit’s spot_asset label remains not_evidenced. This does not assert that no spot asset is ever handled by Pendle.',['architecture:sy-wrapper','standardized-yield:sy-adapter','amm:routing'])],
 'limits':['The source version is current Pendle V2 documentation, whereas the corpus product version, market and deployment are unresolved. No historical source match is claimed.','PT/YT claim semantics and SY wrapper rights must remain distinct. A spot underlying or an input/output routed through another venue is not automatically the direct instrument being classified.','No specific SY implementation, accepted output token or settlement restriction was inspected. The documented generic redemption interface does not determine every wrapper’s rights.','Do not reclassify PT as debt or YT as an option in this task. Other instrument taxonomy gaps remain outside this single-label review.'],
 'next':'Choose and source-bind the precise Pendle market/instrument exposure before applying R-spot_asset. Preserve the distinction between a current asset, a wrapper share, a principal/yield claim and an incidental router input/output.'}
]
checks=[];outcomes=[]
def check(n,v):checks.append({'name':n,'pass':bool(v)});assert v,n
def resolve(ref):
 d=js(R/ref['path'])
 for x in ref['pointer'].strip('/').split('/'):d=d[int(x)] if isinstance(d,list) else d[x]
 return d
for cfg in configs:
 p=base/cfg['folder'];manifests=[p/'retrievals.json']
 if cfg['folder']=='jupiter-jlp':manifests += [p/'retrievals-pass2.json',p/'retrievals-pass3.json']
 records=[r for f in manifests for r in js(f)['records']];retained={r['source_id']:r for r in records if r['status']=='retained'};bodies={sid:(R/r['attempts'][-1]['capture_path']).read_bytes() for sid,r in retained.items()};locators=[]
 for sid,lid,needle,tag in cfg['spans']:
  b=bodies[sid];start=max(0,b.find(b'<main'));i=b.index(needle.encode(),start);ms=list(re.finditer(rb'<'+tag.encode()+rb'(?:\s[^>]*|)>',b[:i+1]));assert ms,(sid,lid)
  a=ms[-1].start();z=b.index(b'</'+tag.encode()+b'>',i)+len(tag)+3
  locators.append({'id':sid+':'+lid,'source_id':sid,'capture':bind(R/retained[sid]['attempts'][-1]['capture_path']),'byte_start':a,'byte_end_exclusive':z,'line_start':b[:a].count(b'\n')+1,'line_end':b[:z].count(b'\n')+1,'span_sha256':h(b[a:z]),'needle':needle,'method':'Exact visible HTML '+tag+' span from retained bytes; manually inspected, no normalization'})
 write(p/'evidence-locators.json',{'locators':locators});rows=[x for x in triage['disagreements'] if x['id'] in cfg['ids']];obs=[];decisions=[]
 for row in rows:
  a=resolve(row['raw_a']['record']);b=resolve(row['raw_b']['record']);g=resolve(row['generated']['pointer']);obs.append({'triage_record':row,'raw_a':a,'raw_b':b,'actual_generated_facet':g});check(row['id']+'-unresolved',g['rule']=='INTERSECTION_UNRESOLVED');delta=set(a['facets'][row['facet']])^set(b['facets'][row['facet']]);check(row['id']+'-labels',delta==set(row['label_claims'][i]['label'] for i in range(len(row['label_claims']))))
  for label in sorted(delta):decisions.append({'dispute_id':row['id'],'facet':row['facet'],'label':label,'proposed_disposition':cfg['dispositions'][label],'accepted_disposition':None,'rule':rules['R-'+label]})
 write(p/'selection-and-observations.json',{'unit_id':cfg['unit'],'selection':'Parent-authorized next3distinct units: edgeX, Jupiter Perpetual/JLP, Pendle; Lighter is a separate agent’s packet','triage':bind(base/'disagreement-triage.json'),'dispute_ids':cfg['ids'],'observations':obs})
 ids={x['id'] for x in locators};claims=[{'id':'C'+str(i+1),'label':label,'kind':kind,'claim':claim,'evidence':ev} for i,(label,kind,claim,ev) in enumerate(cfg['claims'])]
 for c in claims:check(cfg['folder']+'-'+c['id'],set(c['evidence'])<=ids)
 for sid,r in retained.items():last=r['attempts'][-1];check(cfg['folder']+'-body-'+sid,h(bodies[sid])==last['body_sha256'] and len(bodies[sid])==last['body_bytes'])
 for l in locators:check(cfg['folder']+'-span-'+l['id'],h(bodies[l['source_id']][l['byte_start']:l['byte_end_exclusive']])==l['span_sha256'])
 check(cfg['folder']+'-body-cap',0<len(bodies)<=3)
 authors=sorted({r['independence_key'] for r in retained.values()});proposal={'kind':'bounded-single-unit-source-research','created_utc':now(),'author':'GPT-6 stock Codex harness; no independent review performed','unit_id':cfg['unit'],'dispute_ids':cfg['ids'],'process_status':'draft_review_pending','dispositions':decisions,'observations':bind(p/'selection-and-observations.json'),'claims':claims,'qualifications':cfg['limits'],'next_step':cfg['next'],'source_provenance':{'retrieval_manifests':[bind(f) for f in manifests],'locators':bind(p/'evidence-locators.json'),'retained_primary_bodies':len(bodies),'retained_primary_bytes':sum(map(len,bodies.values())),'failed_targets':[r for r in records if r['status']!='retained'],'retained_source_publisher_groups':authors,'independence_limit':'Sources from one publisher are not independent corroboration; a dependency publisher does not bind the consuming product.','original_reference_status':'Reconstructed supporting sources; original missing citations not recovered'},'overlay_applied':False,'semantic_closure':False,'limits':['No accepted corpus labels, deployment identity, historical equivalence, contract execution, Lean refinement, fidelity or holdout claim.','Existing raw annotations, generated decisions, prior research packages and frozen Sprint10 inputs remain unchanged.','not_evidenced is a bounded missing-predicate/scope result, not refuted or not_applicable.','All findings use retained bodies; failed requests and search snippets receive no primary-evidence credit.']}
 write(p/'proposed-adjudication.json',proposal)
 lines=[f"# {cfg['name']} — draft source research",'', '; '.join(f"{d['dispute_id']}/{d['label']}: proposed **{d['proposed_disposition']}**" for d in decisions)+'. All remain unaccepted.','',f"Unit `{cfg['unit']}`; disputed facets {', '.join(cfg['ids'])}. [Exact raw A/B/generated observations](selection-and-observations.json) preserve each facet separately; all actual generated rules remain `INTERSECTION_UNRESOLVED`.",'']
 for c in claims:
  links=', '.join(f"[{sid}]({retained[sid]['url']})" for sid in sorted({x.split(':')[0] for x in c['evidence']}));lines += [c['kind'].replace('_',' ')+': '+c['claim']+' '+links,'']
 lines+=['Qualifications:', '']+['- '+x for x in cfg['limits']]+['',f"Retained {len(bodies)} primary bodies ({sum(map(len,bodies.values()))} bytes) from {len(records)} target URLs. Failed attempts and exact source URLs/times/hashes remain in the retrieval manifests. No more than three bodies were retained for this unit. {len(locators)} source locators bind exact original bytes.",'','The [proposed disposition record](proposed-adjudication.json) binds the current proposed rule, per-label reasoning and full source provenance. No deployment/fidelity or canonical corpus acceptance is claimed.','',cfg['next'],'','Author: GPT-6 stock Codex harness. Independent review remains pending.']
 report='\n'.join(lines)+'\n'
 if (p/'REPORT.md').exists():assert (p/'REPORT.md').read_text()==report
 else:
  with (p/'REPORT.md').open('x') as f:f.write(report)
 outcomes.append({'folder':cfg['folder'],'unit_id':cfg['unit'],'dispute_ids':cfg['ids'],'dispositions':cfg['dispositions'],'bodies':len(bodies),'bytes':sum(map(len,bodies.values())),'locators':len(locators),'targets':len(records),'attempts':sum(len(r['attempts']) for r in records)})
for path,digest in before['files'].items():check('protected:'+path,h((R/path).read_bytes())==digest)
verify={'created_utc':now(),'git_head_before':before['git_head'],'git_head_after':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip(),'s10_frozen_candidate':before['s10_frozen_candidate'],'s10_protected_inputs':88,'protected_files':len(before['files']),'all_protected_unchanged':True,'checks':checks,'check_count':len(checks),'all_passed':all(x['pass'] for x in checks),'units':outcomes,'unit_count':3,'facet_count':4,'label_claim_count':5,'proposed_supported':1,'proposed_not_evidenced':4,'accepted':0,'retained_bodies':sum(x['bodies'] for x in outcomes),'retained_bytes':sum(x['bytes'] for x in outcomes),'scope':'Offline input/body/span/record checks only, not semantic acceptance'}
write(batch/'verification.json',verify)
for cfg in configs:
 p=base/cfg['folder'];write(p/'verification.json',{'batch_verification':bind(batch/'verification.json'),'protected_inputs':bind(batch/'input-protection-before.json'),'unit':next(x for x in outcomes if x['folder']==cfg['folder']),'all_checks_passed':True});write(p/'artifact-manifest.json',{'status':'immutable draft research packet','files':[bind(x) for x in sorted(p.rglob('*')) if x.is_file()]})
write(batch/'artifact-manifest.json',{'files':[bind(x) for x in sorted(batch.iterdir()) if x.is_file()],'unit_manifests':[bind(base/cfg['folder']/'artifact-manifest.json') for cfg in configs]})
print(json.dumps({'checks':len(checks),'protected':len(before['files']),'outcomes':outcomes,'manifest':bind(batch/'artifact-manifest.json')},indent=2))
