from pathlib import Path
import gzip,json,hashlib,datetime,subprocess,re,shutil
B=Path('/home/charl/defiformal/review/semantic-kernel/program-execution-20260908');O=B/'p28-payout-abi-diagnostic-attempt2';h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();read=lambda p:json.loads(p.read_text());now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def put(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
solc=Path(read(B/'p28-depeg-compiler-preparation/compiler.json')['binary_path'])
evm=Path('/home/charl/.cache/defiformal-program/program-execution-20260908/p16-tools/evm');assert h(solc)=='b6b9429d71d4395901795936a0aaee0b23082fcaee10d563d87b42e69c0e68c2';assert h(evm)=='d298ce2c811de089d650ed4f9535c0c58efc72e7adee9b61a40b6c10cc26fb5c'
commands=[]
def run(name,argv,stdin=None):
 start=now();p=subprocess.run(argv,cwd=O,input=stdin,capture_output=True,timeout=180);(O/(name+'.stdout')).write_bytes(p.stdout);(O/(name+'.stderr')).write_bytes(p.stderr);commands.append({'id':name,'argv':argv,'cwd':str(O),'started_utc':start,'finished_utc':now(),'exit':p.returncode,'tool_sha256':h(Path(argv[0])),'stdin_sha256':hashlib.sha256(stdin).hexdigest() if stdin else None,'stdout_sha256':h(O/(name+'.stdout')),'stderr_sha256':h(O/(name+'.stderr'))});put(O/'commands.json',commands);return p
run('solc-version',[str(solc),'--version']);run('evm-version',[str(evm),'--version'])
d=json.loads(gzip.decompress((B/'p28-depeg-compiler-baseline/input.json.gz').read_bytes()));source_hashes={n:hashlib.sha256(v['content'].encode()).hexdigest() for n,v in d['sources'].items()};d['sources']['PayoutAbiProbe.sol']={'content':(O/'PayoutAbiProbe.sol').read_text()};d['settings']['outputSelection']['*']['*'].append('evm.methodIdentifiers');put(O/'input.json',d)
p=run('compile',[str(solc),'--standard-json'],(O/'input.json').read_bytes());assert p.returncode==0;out=json.loads(p.stdout);errors=[e for e in out.get('errors',[]) if e['severity']=='error'];put(O/'diagnostics.json',out.get('errors',[]));assert not errors,errors
old=json.loads(gzip.decompress((B/'p28-depeg-compiler-baseline/stdout.json.gz').read_bytes()));unchanged=[]
for source,contracts in old['contracts'].items():
 for name,c in contracts.items():
  for kind in ['bytecode','deployedBytecode']:assert out['contracts'][source][name]['evm'][kind]['object']==c['evm'][kind]['object'],(source,name,kind)
  unchanged.append({'source':source,'contract':name})
probe=out['contracts']['PayoutAbiProbe.sol']['PayoutAbiProbe']['evm'];(O/'runtime.hex').write_text(probe['deployedBytecode']['object']);selector=probe['methodIdentifiers']['probe(uint256)'];gen=B/'p24-public-call-diagnostic/paris-genesis.json';assert h(gen)==read(B/'p24-public-call-diagnostic/manifest.json')['files']['paris-genesis.json'];shutil.copy2(gen,O/'paris-genesis.json')
values=[];expected=[[0,7,93,96,1,1,1,100],[0,7,0,64,1,1,1,100],[42,0,0,0,1,1,1,100],[1,0,0,0,0,0,0,0],[1,0,0,0,0,0,0,0]]
for i in range(5):
 p=run('scenario-'+str(i),[str(evm),'run','--prestate',str(O/'paris-genesis.json'),'--codefile',str(O/'runtime.hex'),'--input',selector+format(i,'064x'),'--sender','0x0000000000000000000000000000000000000100','--receiver','0x0000000000000000000000000000000000000200']);raw=p.stdout.decode().strip();assert p.returncode==0 and re.fullmatch('0x[0-9a-fA-F]{512}',raw),(i,p.returncode,raw,p.stderr.decode());v=[int(raw[2+64*j:2+64*(j+1)],16) for j in range(8)];assert v==expected[i],(i,v,expected[i]);values.append({'scenario':i,'observed':v,'expected':expected[i]});print(i,v,flush=True)
result={'utc':now(),'scope':'Root bounded ABI diagnostic through actual pinned Product inherited _processPayout, ProductService fallback and PolicyDefaultFlow.processPayout; surrounding registry/license/component/policy/treasury/pool are explicit mocks.','upstream_compiler_source_text_bindings':source_hashes,'all_71_prior_contract_creation_and_runtime_objects_unchanged':len(unchanged)==71,'unchanged_contracts':unchanged,'source_count':len(d['sources']),'compiler_sha256':h(solc),'evm_sha256':h(evm),'compiler_settings':d['settings'],'input_sha256':h(O/'input.json'),'runtime_sha256':h(O/'runtime.hex'),'genesis_sha256':h(O/'paris-genesis.json'),'scenario_results':values,'runtime_observations':'Raw actual service/flow returns (false,7,93). Actual Product wrapper sees (0,7), not (7,93). Ignoring returns proceeds to marker42. Mock treasury/policy/pool effects occur on each successful path. Actual source authorization and responsible-product refusals fire with zero mock effects.','fork':'Paris genesis, block0 timestamp1, compiled Istanbul target inherited solc0.8.2 default','wrapper_runtime_injected':True,'production_contracts_deployed_with_actual_constructors':True,'real_token_transfers':False,'full_DepegProduct_processPolicy_executed':False,'real_policy_or_treasury_accounting':False,'P28_accepted':False,'independent_review_pending':True};put(O/'result.json',result);shutil.copy2(__file__,O/'run.py');files={p.name:h(p) for p in O.iterdir() if p.is_file()};put(O/'root-seal.json',{'utc':now(),'files':files,'file_count':len(files),'acceptance':False});print(json.dumps({'scenarios':5,'prior_contract_objects_unchanged':len(unchanged),'P28_accepted':False}))
