from pathlib import Path
import hashlib,json,subprocess,datetime
R=Path(__file__).resolve().parents[5]; E=Path(__file__).resolve().parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
before=json.loads((E/'before-manifest.json').read_text());cp=R/'review/semantic-kernel/sprint9/native-review-r2/candidate.json';c=json.loads(cp.read_text());bound={x['path']:x for x in c['inputs']};checks=[]
def ck(n,v):checks.append({'label':n,'passed':bool(v)});assert v,n
for x in before['prior_refresh_and_wiki']:ck('preserved/'+x['path'],sha(R/x['path'])==x['sha256'])
ck('all own plan/evidence writes outside native inputs',all(p not in bound for p in before['intended_edits'])and not any(p.startswith(str(E.relative_to(R))+'/')for p in bound))
ck('native manifest unchanged',sha(cp)==before['native_candidate_manifest_sha256'])
source=json.loads((E/'source-context.json').read_text());ck('selected API sources/tools equal captured bytes',all(sha(R/x['path'])==x['sha256']for x in source['bindings']))
mismatches=[{'path':p,'state':'absent_after_root_archive'if not(R/p).exists()else'changed_after_native_reviews'}for p,x in bound.items()if not(R/p).exists()or sha(R/p)!=x['sha256']]
ck('all bound current Lean sources match',not any(x['path'].startswith('lean/')for x in mismatches))
coverage=json.loads((E/'author-coverage.json').read_text());gb=next(x for x in coverage['scenarios']if x['scenario'].startswith('GB11 '));ck('GB11 maps group task and fixture','4.3'in gb['tasks']and'F07'in gb['planned_evidence'])
ck('initialized group arithmetic',5-1==4 and 4-1==3 and 0+2==2 and 2+2==4)
ck('F16 explicitly excluded as initialized equality witness','**not an initialized A=B witness**'in(R/'openspec/changes/operational-interface-binding-preservation/design.md').read_text())
d={'status':'provisional_author_companion_ready','captured_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'observed_head':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip(),'source_context':'eec499d613688137a341f3556cd80ca461dd2ee9','source_acceptance_note':'Parent reports both S9 final native reviews accepted with limitations; exact delivery binding is separately required. This task did not invoke reviewers.','counts':coverage['counts']|{'fixtures':20},'planned_companion':{'fixture_id':'F07','entry_balances':[5,5,0],'prefix_balances':[[4,4,2],[3,3,4]],'all_other_ledger_cells':0,'store':'exact fixed17-entry store unchanged','events':[{'index':0,'before':[5,5,0],'after':[4,4,2],'operation':102},{'index':1,'before':[4,4,2],'after':[3,3,4],'operation':102}],'each_receipt_effects':[-1,-1,2],'each_receipt_supply':[],'output_histories':[[],[]],'failures':[None,None],'next_indices':[1,2],'query':'[(A,B)]','query_success_at':['entry','first-leaf cursor','whole two-leaf group cursor'],'actual_runtime_evidence':False},'checks':checks,'all_passed':all(x['passed']for x in checks),'native_bound_mismatches_before':before['current_native_binding_mismatches_before'],'native_bound_mismatches_after':mismatches,'native_binding_note':'Root explicitly authorized administrative task/evidence changes and archiving after accepted reviews. Current changed/archived inputs are disclosed; none was edited by this S10 task. All bound current Lean inputs match.','remaining_gates':['exact accepted S9 source/evidence/archive/remote delivery binding','official S10 candidate/shared bundle freeze','nonauthor GPT-6 and native Fable5.1 medium planning acceptance','all M2 implementation and verification evidence'],'development_failures':[{'operation':'first ad hoc companion metadata preparation assumed all original native paths still exist','exit':1,'cause':'root concurrently archived S9 plan; old design path absent','resolution':'treat archived paths as disclosed administrative differences; preserve actual current source checks','source_or_plan_writes_by_failed_operation':False}]}
(E/'companion-readiness.json').write_text(json.dumps(d,indent=2)+'\n');print('PASS',len(checks),'checks;',len(mismatches),'post-review administrative changes/archived paths disclosed.')
