from pathlib import Path
import datetime,hashlib,json,shutil
B=Path('/home/charl/defiformal/review/semantic-kernel/program-execution-20260908');D=B/'p28-depeg-dependency-preparation';O=B/'p28-depeg-lifecycle-scope';O.mkdir(exist_ok=False);h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def put(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
anchors=[]
def add(id,p,needle,claim):
 lines=p.read_text().splitlines();found=[i+1 for i,line in enumerate(lines) if needle in line];assert found,(id,needle);anchors.append({'id':id,'source_path_from_program_root':str(p.relative_to(B)),'sha256':h(p),'needle':needle,'matching_lines':found,'static_observation':claim,'proof_or_execution':False})
g=D/'source/gif-contracts/contracts';f=g/'flows/PolicyDefaultFlow.sol';t=g/'modules/TreasuryModule.sol';p=g/'modules/PolicyController.sol';c=g/'modules/ComponentController.sol'
add('service-authorization',g/'services/ProductService.sol','require(isAuthorized,','Fallback obtains license status and nonzero configured policy flow, then delegatecalls. Runtime registry, license, component and policy flow identities must be bound.')
add('active-component-license',B/'p28-depeg-license-source/LicenseController.sol','_component.getComponentState(productId) == IComponent.ComponentState.Active','License requires an active registered component. Its getPolicyFlow call separately invokes ComponentController product-type guard; do not infer product type solely from _isValidCall.')
add('product-flow-type',c,'ERROR:CCR-011:UNKNOWN_PRODUCT_ID','getPolicyFlow requires isProduct(productId), completing the source authorization/type chain together with registered-component and active-state checks.')
add('responsible-product',f,'ERROR:PFD-004:PROCESSID_PRODUCT_MISMATCH','Policy flow checks the process metadata productId against the registered calling product. This is state/identity authorization, not oracle truth.')
add('controller-service-authority',g/'shared/CoreController.sol','ERROR:CRC-003:NOT_PRODUCT_SERVICE','Controller mutation requires registered storage address and registered ProductService caller. Source-bound proof must model delegated context and trusted registry state.')
add('expected-payout',t,'ERROR:TRS-040:PAYOUT_ALREADY_PROCESSED','Treasury requires Expected payout state before token movement.')
add('cash-custody-balance',t,'ERROR:TRS-042:RISKPOOL_WALLET_BALANCE_TOO_SMALL','Treasury checks actual selected token balance of riskpool wallet. Authorized claim alone does not guarantee funded payout.')
add('cash-custody-allowance',t,'ERROR:TRS-043:PAYOUT_ALLOWANCE_TOO_SMALL','Treasury also checks wallet allowance, distinct from accounting solvency and legal enforceability.')
add('payout-recipient',t,'TransferHelper.unifiedTransferFrom(token, riskpoolWalletAddress, metadata.owner, payout.amount)','Token transfer targets policy metadata.owner. Depeg protectedWallet and claim caller can differ from payout recipient.')
add('token-call-contract',g/'shared/TransferHelper.sol','data.length == 0','Transfer helper accepts successful low-level transferFrom with no return data, or exactly32bytes decoding true. It does not independently measure recipient balance delta; token behavior assumptions remain.')
add('positive-confirmed-payout',p,'ERROR:POC-083:PAYOUT_AMOUNT_ZERO_INVALID','createPayout requires a confirmed existing claim, strictly positive amount and paidAmount+payoutAmount<=claimAmount. Zero calculated payout is a downstream refusal, not automatic successful closure.')
add('paid-state-transition',p,'payout.state = IPolicy.PayoutState.PaidOut;','Controller moves Expected payout to PaidOut, increments claim.paidAmount, and closes claim only on exact full payment. Payout states and openClaimsCount must be preserved.')
add('exact-discharge',p,'if (claim.claimAmount == claim.paidAmount) {','Claim closes only when paid amount equals confirmed claim amount. Creating/confirming claim or producing an event alone is not discharge.')
add('flow-cash-before-accounting',f,'(feeAmount, netPayoutAmount) = treasury.processPayout(processId, payoutId);','Flow processes treasury transfer before policy and pool accounting. Atomic transaction behavior and failure rollback remain runtime obligations.')
put(O/'source-navigation.json',{'utc':now(),'anchors':anchors,'count':len(anchors),'scope':'Static source observations plus separately captured compiler ABI evidence. No EVM or Lean execution.','P28_accepted':False})
(O/'README.md').write_text('''# P28 lifecycle source follow-up

The Brownie-selected GIF refs expose the actual ProductService fallback, PolicyDefaultFlow, PolicyController, TreasuryModule, TransferHelper and LicenseController authorization/accounting paths. Static navigation binds exact source hashes and lines. These source observations are candidates for an AGY observation contract; no source-entry or formal acceptance is granted.

The authorization chain includes registered active product, resolved policy flow, responsible product for the process, and registered controller/service storage context. It does not prove oracle or owner-supplied historical balance truth. The protected wallet creates the claim; any caller can process a queued claim with required owner-supplied balance data. Payout goes from riskpool custody to policy metadata.owner. Positive confirmed payout, token balance, allowance and successful token transfer are required. The helper accepts empty return data or true; exact recipient balance movement still depends on token semantics. Claim paidAmount/openClaimsCount transitions and equality-triggered closure distinguish cash-backed discharge from disappearance of an unpaid obligation.

The selected flow ABI returns(bool success,uint feeAmount,uint netPayoutAmount), while selected IProductService ABI returns(uint feeAmount,uint netPayoutAmount). The flow never assigns its success variable; solc emits an unused-parameter warning. Product._processPayout reads two outputs, and the selected DepegProduct ignores those returned values. This is a real source/compiled-ABI mismatch requiring an explicit call/return observation and runtime diagnostic. Do not relabel the default boolean as transaction failure, infer return-tuple correctness from compilation, or claim proven lost payout. Flow itself uses treasury return values for policy/pool bookkeeping.

Configuration route remains Brownie0.8.2 optimizer200 and its exact Git refs, separate from differing npm declarations. The standalone compile normalizes CRLF to LF in six text inputs via Python read_text; raw acquired source hashes and exact JSON input hashes are both retained. This transformation is recorded in root verification. No npm/Brownie install, full test/deployment execution or live oracle/custody observation ran.
''');shutil.copy2(__file__,O/'scope.py');put(O/'root-seal.json',{'utc':now(),'files':{p.name:h(p) for p in O.iterdir() if p.is_file()},'acceptance':False});print(json.dumps({'static_lifecycle_anchors':len(anchors),'acceptance':False}))
