import DefiKernel.Certificates.Delivered
import DefiKernel.Certificates.Tests
open DefiKernel.Certificates
open DefiKernel.Certificates.Tests
-- Independent fixed six-class inventory, 64 literal expected rows generated outside candidate.
def cases : List (Nat × List String × List (String × String) × Option String) := [
(0, [], [("registry-trust", "missing"), ("administrator-trust", "missing"), ("context-authenticity", "missing"), ("observation-truth", "missing"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "missing")], (some "registry-trust")),
(1, ["registry-trust"], [("registry-trust", "present"), ("administrator-trust", "missing"), ("context-authenticity", "missing"), ("observation-truth", "missing"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "missing")], (some "administrator-trust")),
(2, ["administrator-trust"], [("registry-trust", "missing"), ("administrator-trust", "present"), ("context-authenticity", "missing"), ("observation-truth", "missing"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "missing")], (some "registry-trust")),
(3, ["registry-trust", "administrator-trust"], [("registry-trust", "present"), ("administrator-trust", "present"), ("context-authenticity", "missing"), ("observation-truth", "missing"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "missing")], (some "context-authenticity")),
(4, ["context-authenticity"], [("registry-trust", "missing"), ("administrator-trust", "missing"), ("context-authenticity", "present"), ("observation-truth", "missing"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "missing")], (some "registry-trust")),
(5, ["registry-trust", "context-authenticity"], [("registry-trust", "present"), ("administrator-trust", "missing"), ("context-authenticity", "present"), ("observation-truth", "missing"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "missing")], (some "administrator-trust")),
(6, ["administrator-trust", "context-authenticity"], [("registry-trust", "missing"), ("administrator-trust", "present"), ("context-authenticity", "present"), ("observation-truth", "missing"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "missing")], (some "registry-trust")),
(7, ["registry-trust", "administrator-trust", "context-authenticity"], [("registry-trust", "present"), ("administrator-trust", "present"), ("context-authenticity", "present"), ("observation-truth", "missing"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "missing")], (some "observation-truth")),
(8, ["observation-truth"], [("registry-trust", "missing"), ("administrator-trust", "missing"), ("context-authenticity", "missing"), ("observation-truth", "present"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "missing")], (some "registry-trust")),
(9, ["registry-trust", "observation-truth"], [("registry-trust", "present"), ("administrator-trust", "missing"), ("context-authenticity", "missing"), ("observation-truth", "present"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "missing")], (some "administrator-trust")),
(10, ["administrator-trust", "observation-truth"], [("registry-trust", "missing"), ("administrator-trust", "present"), ("context-authenticity", "missing"), ("observation-truth", "present"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "missing")], (some "registry-trust")),
(11, ["registry-trust", "administrator-trust", "observation-truth"], [("registry-trust", "present"), ("administrator-trust", "present"), ("context-authenticity", "missing"), ("observation-truth", "present"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "missing")], (some "context-authenticity")),
(12, ["context-authenticity", "observation-truth"], [("registry-trust", "missing"), ("administrator-trust", "missing"), ("context-authenticity", "present"), ("observation-truth", "present"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "missing")], (some "registry-trust")),
(13, ["registry-trust", "context-authenticity", "observation-truth"], [("registry-trust", "present"), ("administrator-trust", "missing"), ("context-authenticity", "present"), ("observation-truth", "present"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "missing")], (some "administrator-trust")),
(14, ["administrator-trust", "context-authenticity", "observation-truth"], [("registry-trust", "missing"), ("administrator-trust", "present"), ("context-authenticity", "present"), ("observation-truth", "present"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "missing")], (some "registry-trust")),
(15, ["registry-trust", "administrator-trust", "context-authenticity", "observation-truth"], [("registry-trust", "present"), ("administrator-trust", "present"), ("context-authenticity", "present"), ("observation-truth", "present"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "missing")], (some "environment-authenticity")),
(16, ["environment-authenticity"], [("registry-trust", "missing"), ("administrator-trust", "missing"), ("context-authenticity", "missing"), ("observation-truth", "missing"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "missing")], (some "registry-trust")),
(17, ["registry-trust", "environment-authenticity"], [("registry-trust", "present"), ("administrator-trust", "missing"), ("context-authenticity", "missing"), ("observation-truth", "missing"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "missing")], (some "administrator-trust")),
(18, ["administrator-trust", "environment-authenticity"], [("registry-trust", "missing"), ("administrator-trust", "present"), ("context-authenticity", "missing"), ("observation-truth", "missing"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "missing")], (some "registry-trust")),
(19, ["registry-trust", "administrator-trust", "environment-authenticity"], [("registry-trust", "present"), ("administrator-trust", "present"), ("context-authenticity", "missing"), ("observation-truth", "missing"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "missing")], (some "context-authenticity")),
(20, ["context-authenticity", "environment-authenticity"], [("registry-trust", "missing"), ("administrator-trust", "missing"), ("context-authenticity", "present"), ("observation-truth", "missing"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "missing")], (some "registry-trust")),
(21, ["registry-trust", "context-authenticity", "environment-authenticity"], [("registry-trust", "present"), ("administrator-trust", "missing"), ("context-authenticity", "present"), ("observation-truth", "missing"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "missing")], (some "administrator-trust")),
(22, ["administrator-trust", "context-authenticity", "environment-authenticity"], [("registry-trust", "missing"), ("administrator-trust", "present"), ("context-authenticity", "present"), ("observation-truth", "missing"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "missing")], (some "registry-trust")),
(23, ["registry-trust", "administrator-trust", "context-authenticity", "environment-authenticity"], [("registry-trust", "present"), ("administrator-trust", "present"), ("context-authenticity", "present"), ("observation-truth", "missing"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "missing")], (some "observation-truth")),
(24, ["observation-truth", "environment-authenticity"], [("registry-trust", "missing"), ("administrator-trust", "missing"), ("context-authenticity", "missing"), ("observation-truth", "present"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "missing")], (some "registry-trust")),
(25, ["registry-trust", "observation-truth", "environment-authenticity"], [("registry-trust", "present"), ("administrator-trust", "missing"), ("context-authenticity", "missing"), ("observation-truth", "present"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "missing")], (some "administrator-trust")),
(26, ["administrator-trust", "observation-truth", "environment-authenticity"], [("registry-trust", "missing"), ("administrator-trust", "present"), ("context-authenticity", "missing"), ("observation-truth", "present"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "missing")], (some "registry-trust")),
(27, ["registry-trust", "administrator-trust", "observation-truth", "environment-authenticity"], [("registry-trust", "present"), ("administrator-trust", "present"), ("context-authenticity", "missing"), ("observation-truth", "present"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "missing")], (some "context-authenticity")),
(28, ["context-authenticity", "observation-truth", "environment-authenticity"], [("registry-trust", "missing"), ("administrator-trust", "missing"), ("context-authenticity", "present"), ("observation-truth", "present"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "missing")], (some "registry-trust")),
(29, ["registry-trust", "context-authenticity", "observation-truth", "environment-authenticity"], [("registry-trust", "present"), ("administrator-trust", "missing"), ("context-authenticity", "present"), ("observation-truth", "present"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "missing")], (some "administrator-trust")),
(30, ["administrator-trust", "context-authenticity", "observation-truth", "environment-authenticity"], [("registry-trust", "missing"), ("administrator-trust", "present"), ("context-authenticity", "present"), ("observation-truth", "present"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "missing")], (some "registry-trust")),
(31, ["registry-trust", "administrator-trust", "context-authenticity", "observation-truth", "environment-authenticity"], [("registry-trust", "present"), ("administrator-trust", "present"), ("context-authenticity", "present"), ("observation-truth", "present"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "missing")], (some "replay-prevention-outside-model")),
(32, ["replay-prevention-outside-model"], [("registry-trust", "missing"), ("administrator-trust", "missing"), ("context-authenticity", "missing"), ("observation-truth", "missing"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "present")], (some "registry-trust")),
(33, ["registry-trust", "replay-prevention-outside-model"], [("registry-trust", "present"), ("administrator-trust", "missing"), ("context-authenticity", "missing"), ("observation-truth", "missing"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "present")], (some "administrator-trust")),
(34, ["administrator-trust", "replay-prevention-outside-model"], [("registry-trust", "missing"), ("administrator-trust", "present"), ("context-authenticity", "missing"), ("observation-truth", "missing"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "present")], (some "registry-trust")),
(35, ["registry-trust", "administrator-trust", "replay-prevention-outside-model"], [("registry-trust", "present"), ("administrator-trust", "present"), ("context-authenticity", "missing"), ("observation-truth", "missing"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "present")], (some "context-authenticity")),
(36, ["context-authenticity", "replay-prevention-outside-model"], [("registry-trust", "missing"), ("administrator-trust", "missing"), ("context-authenticity", "present"), ("observation-truth", "missing"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "present")], (some "registry-trust")),
(37, ["registry-trust", "context-authenticity", "replay-prevention-outside-model"], [("registry-trust", "present"), ("administrator-trust", "missing"), ("context-authenticity", "present"), ("observation-truth", "missing"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "present")], (some "administrator-trust")),
(38, ["administrator-trust", "context-authenticity", "replay-prevention-outside-model"], [("registry-trust", "missing"), ("administrator-trust", "present"), ("context-authenticity", "present"), ("observation-truth", "missing"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "present")], (some "registry-trust")),
(39, ["registry-trust", "administrator-trust", "context-authenticity", "replay-prevention-outside-model"], [("registry-trust", "present"), ("administrator-trust", "present"), ("context-authenticity", "present"), ("observation-truth", "missing"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "present")], (some "observation-truth")),
(40, ["observation-truth", "replay-prevention-outside-model"], [("registry-trust", "missing"), ("administrator-trust", "missing"), ("context-authenticity", "missing"), ("observation-truth", "present"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "present")], (some "registry-trust")),
(41, ["registry-trust", "observation-truth", "replay-prevention-outside-model"], [("registry-trust", "present"), ("administrator-trust", "missing"), ("context-authenticity", "missing"), ("observation-truth", "present"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "present")], (some "administrator-trust")),
(42, ["administrator-trust", "observation-truth", "replay-prevention-outside-model"], [("registry-trust", "missing"), ("administrator-trust", "present"), ("context-authenticity", "missing"), ("observation-truth", "present"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "present")], (some "registry-trust")),
(43, ["registry-trust", "administrator-trust", "observation-truth", "replay-prevention-outside-model"], [("registry-trust", "present"), ("administrator-trust", "present"), ("context-authenticity", "missing"), ("observation-truth", "present"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "present")], (some "context-authenticity")),
(44, ["context-authenticity", "observation-truth", "replay-prevention-outside-model"], [("registry-trust", "missing"), ("administrator-trust", "missing"), ("context-authenticity", "present"), ("observation-truth", "present"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "present")], (some "registry-trust")),
(45, ["registry-trust", "context-authenticity", "observation-truth", "replay-prevention-outside-model"], [("registry-trust", "present"), ("administrator-trust", "missing"), ("context-authenticity", "present"), ("observation-truth", "present"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "present")], (some "administrator-trust")),
(46, ["administrator-trust", "context-authenticity", "observation-truth", "replay-prevention-outside-model"], [("registry-trust", "missing"), ("administrator-trust", "present"), ("context-authenticity", "present"), ("observation-truth", "present"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "present")], (some "registry-trust")),
(47, ["registry-trust", "administrator-trust", "context-authenticity", "observation-truth", "replay-prevention-outside-model"], [("registry-trust", "present"), ("administrator-trust", "present"), ("context-authenticity", "present"), ("observation-truth", "present"), ("environment-authenticity", "missing"), ("replay-prevention-outside-model", "present")], (some "environment-authenticity")),
(48, ["environment-authenticity", "replay-prevention-outside-model"], [("registry-trust", "missing"), ("administrator-trust", "missing"), ("context-authenticity", "missing"), ("observation-truth", "missing"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "present")], (some "registry-trust")),
(49, ["registry-trust", "environment-authenticity", "replay-prevention-outside-model"], [("registry-trust", "present"), ("administrator-trust", "missing"), ("context-authenticity", "missing"), ("observation-truth", "missing"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "present")], (some "administrator-trust")),
(50, ["administrator-trust", "environment-authenticity", "replay-prevention-outside-model"], [("registry-trust", "missing"), ("administrator-trust", "present"), ("context-authenticity", "missing"), ("observation-truth", "missing"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "present")], (some "registry-trust")),
(51, ["registry-trust", "administrator-trust", "environment-authenticity", "replay-prevention-outside-model"], [("registry-trust", "present"), ("administrator-trust", "present"), ("context-authenticity", "missing"), ("observation-truth", "missing"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "present")], (some "context-authenticity")),
(52, ["context-authenticity", "environment-authenticity", "replay-prevention-outside-model"], [("registry-trust", "missing"), ("administrator-trust", "missing"), ("context-authenticity", "present"), ("observation-truth", "missing"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "present")], (some "registry-trust")),
(53, ["registry-trust", "context-authenticity", "environment-authenticity", "replay-prevention-outside-model"], [("registry-trust", "present"), ("administrator-trust", "missing"), ("context-authenticity", "present"), ("observation-truth", "missing"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "present")], (some "administrator-trust")),
(54, ["administrator-trust", "context-authenticity", "environment-authenticity", "replay-prevention-outside-model"], [("registry-trust", "missing"), ("administrator-trust", "present"), ("context-authenticity", "present"), ("observation-truth", "missing"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "present")], (some "registry-trust")),
(55, ["registry-trust", "administrator-trust", "context-authenticity", "environment-authenticity", "replay-prevention-outside-model"], [("registry-trust", "present"), ("administrator-trust", "present"), ("context-authenticity", "present"), ("observation-truth", "missing"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "present")], (some "observation-truth")),
(56, ["observation-truth", "environment-authenticity", "replay-prevention-outside-model"], [("registry-trust", "missing"), ("administrator-trust", "missing"), ("context-authenticity", "missing"), ("observation-truth", "present"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "present")], (some "registry-trust")),
(57, ["registry-trust", "observation-truth", "environment-authenticity", "replay-prevention-outside-model"], [("registry-trust", "present"), ("administrator-trust", "missing"), ("context-authenticity", "missing"), ("observation-truth", "present"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "present")], (some "administrator-trust")),
(58, ["administrator-trust", "observation-truth", "environment-authenticity", "replay-prevention-outside-model"], [("registry-trust", "missing"), ("administrator-trust", "present"), ("context-authenticity", "missing"), ("observation-truth", "present"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "present")], (some "registry-trust")),
(59, ["registry-trust", "administrator-trust", "observation-truth", "environment-authenticity", "replay-prevention-outside-model"], [("registry-trust", "present"), ("administrator-trust", "present"), ("context-authenticity", "missing"), ("observation-truth", "present"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "present")], (some "context-authenticity")),
(60, ["context-authenticity", "observation-truth", "environment-authenticity", "replay-prevention-outside-model"], [("registry-trust", "missing"), ("administrator-trust", "missing"), ("context-authenticity", "present"), ("observation-truth", "present"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "present")], (some "registry-trust")),
(61, ["registry-trust", "context-authenticity", "observation-truth", "environment-authenticity", "replay-prevention-outside-model"], [("registry-trust", "present"), ("administrator-trust", "missing"), ("context-authenticity", "present"), ("observation-truth", "present"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "present")], (some "administrator-trust")),
(62, ["administrator-trust", "context-authenticity", "observation-truth", "environment-authenticity", "replay-prevention-outside-model"], [("registry-trust", "missing"), ("administrator-trust", "present"), ("context-authenticity", "present"), ("observation-truth", "present"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "present")], (some "registry-trust")),
(63, ["registry-trust", "administrator-trust", "context-authenticity", "observation-truth", "environment-authenticity", "replay-prevention-outside-model"], [("registry-trust", "present"), ("administrator-trust", "present"), ("context-authenticity", "present"), ("observation-truth", "present"), ("environment-authenticity", "present"), ("replay-prevention-outside-model", "present")], none)
]

def runPayload : CompositionRunPayloadEnc := ⟨defaultConfig, [defaultStepPayload.boundary], defaultStepPayload.pre, [defaultStep]⟩
def routes : List (String × (EnvelopeEnc → Report) × (EnvelopeEnc → RawObservation)) := [
 ("typed", (fun env => Delivered.checkTyped env defaultPayload), (fun env => rawExecute (.typed env defaultPayload))),
 ("step", (fun env => Delivered.checkStep env defaultStepPayload), (fun env => rawExecute (.step env defaultStepPayload))),
 ("run", (fun env => Delivered.checkRun env runPayload), (fun env => rawExecute (.run env runPayload))) ]
def main : IO UInt32 := do
 let mut failures := 0
 for (name, checker, rawChecker) in routes do
  let mut passed := 0
  for claim in [false, true] do
   for (mask, present, labels, missing) in cases do
    let env := { defaultEnvelope with assumptions := present, claimed_judgments := if claim then ["assumptionsDeclared"] else [] }
    let rep := checker env
    let raw := rawChecker env
    let expectedOutcome := if missing.isSome then JudgmentOutcome.«false» else .«true»
    let expectedJudgment : JudgmentResult := ⟨"assumptionsDeclared", expectedOutcome, claim, claim == missing.isNone⟩
    let statusOK := if let some m := missing then rep.status == .incomplete && rep.failure == some ⟨.incompleteObligation, m, none⟩ else rep.status == .accepted && rep.failure == none
    let ok := rep.assumptions == labels && statusOK &&
      rep.judgments.find? (·.family == "assumptionsDeclared") == some expectedJudgment &&
      rep.world == raw.world && rep.receipt == raw.receipt && rep.outputs == raw.outputs && rep.events == raw.events && rep.nextIndex == raw.nextIndex && rep.cursorFailure == raw.cursorFailure
    if ok then passed := passed + 1 else
     failures := failures + 1
     IO.println s!"FAIL {name} mask={mask} claim={claim}"
  IO.println s!"{name}: actual labels/status/firstMissing/judgment/claimed/match/kernel {passed}/128"
 return if failures == 0 then 0 else 1
