from pathlib import Path
import collections,datetime,gzip,hashlib,json,re,shutil
B=Path('/home/charl/defiformal/review/semantic-kernel/program-execution-20260908');O=B/'p19-module-map-stuck-grok-r1';C=O/'closeout';S=Path('/home/charl/.cache/defiformal-program/program-execution-20260908/p19-module-map-stuck-grok-r1-sandbox');V=O/'root-verification';now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat();h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();read=lambda p:json.loads(p.read_text())
def put(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
assert not Path('/proc/2285155').exists();V.mkdir(exist_ok=False);shutil.copy2(__file__,V/'verify.py');i=read(O/'inputs.json')
for n,d in i['files'].items():assert h(S/n)==d,n
for folder in [O/'original-terminal']:
 for n,d in read(folder/'root-seal.json')['files'].items():assert h(folder/n)==d,n
manifest=read(C/'MANIFEST.json');assert manifest['self_excluding'] and len(manifest['files'])==manifest['file_count']==12
for r in manifest['files']:
 p=C/r['path'];assert p.stat().st_size==r['bytes'] and h(p)==r['sha256'],r['path']
assert read(C/'verdict.json')['status']=='complete';orig=read(O/'process.json');close=read(C/'process.json');assert h(O/'native.jsonl')==orig['log_sha256'] and h(C/'native.jsonl')==close['log_sha256'];assert orig['sessions']==close['sessions'] and close['reported_models']==['grok-4.6-build'] and close['process_exit']==0
native=[json.loads(l) for l in (O/'native.jsonl').read_text().splitlines() if l.strip()];calls={d['toolCallId']:d for d in native if d.get('type')=='tool_call'};cmds=read(C/'commands.json');assert len(calls)==cmds['original_native_tool_call_count']==88
assert dict(collections.Counter(d['toolName'] for d in calls.values()))==cmds['original_native_by_name'];assert len(cmds['original_native_tool_calls'])==88
for row in cmds['original_native_tool_calls']:
 actual=calls[row['toolCallId']];assert row['toolName']==actual['toolName']
 for key,value in row.items():
  if key in ['toolCallId','toolName','kind','source','compiler']:continue
  assert actual['rawInput'].get(key)==value,(key,row['toolCallId'])
assert cmds['this_review_compiler_commands']==[] and cmds['author_compiler_commands']==[]
for row in read(C/'verdict.json')['root_probe_recovery']['probes']:
 p=B/'p19-r22-root-probe-recovery'/row['probe'];assert h(p/'stdout')==row['stdout_sha256'];assert read(p/'command.json')['exit']==row['exit']==1
 errors=[line for line in (p/'stdout').read_text().splitlines() if re.search(r':\d+:\d+: error(?:\([^)]*\))?:',line)];assert len(errors)==row['error_header_count'],row['probe']
diagnostic=B/'p19-r22-root-object-diagnostic';d=read(diagnostic/'command.json');assert d['exit']==0
for n,digest in read(diagnostic/'root-seal.json')['files'].items():assert h(diagnostic/n)==digest
out=(diagnostic/'stdout').read_text();axioms=[l for l in out.splitlines() if 'depends on axioms:' in l];assert len(axioms)==3 and all(l.endswith('[propext, Classical.choice, Quot.sound]') for l in axioms)
res={'utc':now(),'frozen_input_bindings':len(i['files']),'review_manifest_bindings':12,'native_read_search_shell_calls_verified':88,'reviewer_compiler_commands':0,'root_prior_failed_probes':{'test_typed_roundtrip':12,'test_all_structures':4,'test_template_fix':4},'same_session':close['sessions'][0],'actual_models_original_and_closeout':['grok-4.6-build'],'original_exit':1,'original_turn_cap':20,'closeout_exit':0,'root_additional_diagnostic':'../p19-r22-root-object-diagnostic/root-seal.json','root_additional_diagnostic_axioms':{'theorem_count':3,'standard_only':True},'verdict':'CHANGES_REQUIRED','acceptance':False};put(V/'result.json',res)
adjudication={**res,'scope':'Completed independent source-level diagnosis of frozen R22 failures. Root adopts repair guidance with the corrections below. No P19 production acceptance or campaign credit.','corrections':['commands.json original_native_tool_calls source=original-terminal/native.jsonl.gz resolves from parent review output, not its declared closeout base. Actual immutable stream and all88 IDs/recorded inputs are verified; reviewer metadata retained unchanged.','P19-R22-STUCK-02 mixes locations across modules; TreeJson.toJson is CanonicalJson.lean:884, not Correspondence.lean:884. Use narrative/library references and actual source.','encodeCellDelta/encodeSupplyDelta are production encoder definitions, not replacement proof lemmas. Prove/reuse actual child representation equalities; do not blindly replace a missing theorem name with a definition.','Grok intentionally left Json Raw-tree permutation equality unfinished. NEW ROOT Lean diagnostic proves the concrete libraryRef field-order trees unequal, despite semantic BEq evaluating true. This is a false structural-equality helper obligation, not just a missing rfl tactic. Preserve production bytes and public codec/domain; design faithful decoder extensionality or another justified representation bridge instead of trying to prove the false equality.','NEW ROOT Lean diagnostic also proves an unsupported quote-tag encoding mismatch. Existing supported admission excludes unsupported; not a supported-input codec defect. This is root execution after review, not Grok evidence.','Reviewer skipped preflight and context helper and honestly reports no compiler runs. Source diagnosis remains advisory and all prospective tactic suggestions remain untested.'], 'next_author_evidence_delta':['RootObjectDiagnostic.distinct_json refutes direct exact-Json equality for libraryRef declaration-order vs sorted-order objects. RootObjectDiagnostic.unsupported_quote_mismatch proves the out-of-domain unsupported-tag mismatch.','Use existing generic parseCanonicalJson_tree for declaration-order TreeJson, then relate semantic decoder observations to existing mappers without assuming representation equality; preserve same real encode/decode target and full admitted domain.','Explicit Nat→Int map, fromNat unfolding, malformed TypesEnum syntax, helper theorem naming and bounded structural encode proof repairs remain required.'], 'full_P19_accepted':False,'whole_program_complete':False};put(O/'root-adjudication.json',adjudication)
with (C/'native.jsonl.gz').open('xb') as f:
 with gzip.GzipFile(filename='',mode='wb',fileobj=f,mtime=0) as z:z.write((C/'native.jsonl').read_bytes())
files={str(p.relative_to(O)):h(p) for p in O.rglob('*') if p.is_file() and p.name!='native.jsonl'};assert 'root-seal.json' not in files;put(O/'root-seal.json',{'utc':now(),'files':files,'file_count':len(files),'review_manifest_bindings':12,'acceptance':False});print(json.dumps({'sealed_files':len(files),**res}))
