from pathlib import Path
import json,hashlib,subprocess,datetime,re
r=Path('/home/charl/defiformal');b=r/'review/semantic-kernel/program-execution-20260908';w=Path('/home/charl/defiformal-wt-p19-certificates-grok-opus-20260909');o=b/'p19-r16-root-precheck';o.mkdir(exist_ok=False);h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();write=lambda p,d:p.write_text(json.dumps(d,indent=2)+'\n');m=json.loads((b/'p19-roundtrip-proof-agy-r16-terminal-manifest.json').read_text());old=json.loads((b/'p19-roundtrip-proof-agy-r15-terminal-manifest.json').read_text());prev={f['path']:f['sha256'] for f in old['files']}
assert not Path('/proc/1902759').exists()
for f in m['files']:assert h(w/f['path'])==f['sha256'],f['path']
changes=[f['path'] for f in m['files'] if prev.get(f['path'])!=f['sha256']];names=[];counts={}
for n in ['CanonicalJson','Correspondence']:
 ns=re.findall(r'^theorem\s+(\S+)',(w/f'lean/DefiKernel/Certificates/{n}.lean').read_text(),re.M);counts[n]=len(ns);names+=ns
assert len(names)==269 and len(set(names))==269
probe=o/'Axioms269.lean';probe.write_text('import DefiKernel.Certificates.Correspondence\n'+''.join('#print axioms DefiKernel.Certificates.'+n+'\n' for n in names));tool=Path('/home/charl/.elan/toolchains/leanprover--lean4---v4.33.0-rc2/bin');cmd=[str(tool/'lake'),'env',str(tool/'lean'),str(probe)];start=datetime.datetime.now(datetime.timezone.utc).isoformat();p=subprocess.run(cmd,cwd=w/'lean',capture_output=True,timeout=120);end=datetime.datetime.now(datetime.timezone.utc).isoformat();(o/'axioms269.stdout').write_bytes(p.stdout);(o/'axioms269.stderr').write_bytes(p.stderr);out=p.stdout.decode();records=re.findall(r"'([^']+)' depends on axioms: \[([^\]]*)\]",out,re.S);zero=re.findall(r"'([^']+)' does not depend on any axioms",out);got=[n for n,_ in records]+zero;want=['DefiKernel.Certificates.'+n for n in names];bad=[{'name':n,'axioms':a} for n,a in records if set(x.strip() for x in a.split(',') if x.strip())-{'propext','Classical.choice','Quot.sound'}]
receipt={'argv':cmd,'cwd':str(w/'lean'),'started_utc':start,'finished_utc':end,'exit':p.returncode,'probe_sha256':h(probe),'stdout_sha256':h(o/'axioms269.stdout'),'stderr_sha256':h(o/'axioms269.stderr'),'lean_sha256':h(tool/'lean'),'lake_sha256':h(tool/'lake'),'source_counts':counts,'axiom_records':len(records),'zero_axiom_records':len(zero),'exact_names_match':set(got)==set(want),'forbidden':bad,'scope':'Exact269 declarations imported from frozen R16 author build; fresh independent reviewer rebuild remains pending.','acceptance':False};write(o/'axioms269-command.json',receipt);assert p.returncode==0 and len(got)==269 and set(got)==set(want) and not bad
for f in m['files']:assert h(w/f['path'])==f['sha256'],f['path']
record={'schema':'defiformal-p19-root-precheck/v1','utc':end,'candidate_archive_sha256':m['sha256'],'changed_or_new_files':changes,'counts':counts,'axiom_check':'p19-r16-root-precheck/axioms269-command.json','findings':['Universal EncodeDecodeRoundtripStatement remains a Prop; lexical and parser success are still hypotheses of the conditional byte pipeline theorem.','R16 scanner uses lexString and root replay verified32 C0 collision roundtrips, true duplicate refusals, quote and backslash positives. Fresh independent rebuild/review remains required.','escapedKeyCollision_admissible is now a named checked theorem; assess sourceMap sorted fast path and existing contracts on exact frozen Encode bytes.','New parser steps and fixed rational examples do not replace general recursive parser/numeric inverse proofs.','Report Verify287/408 is one prefix scope; bind full actual Verify log separately from exact269 declarations.','Root correction: encodeEnvelope preserves declaration order; encodeSourceMap sorts entries (R16 adds already-sorted fast path). Preserve actual encoder output.'],'acceptance':False,'assessment':'PARTIAL_PROOF_WORK_CHANGES_REQUIRED'};write(b/'p19-roundtrip-proof-agy-r16-root-precheck.json',record);print(json.dumps({'counts':counts,'axiom_records':len(records),'zero_axioms':len(zero),'changes':changes,'acceptance':False}))
