from pathlib import Path
import json,hashlib,datetime,re
r=Path(__file__).resolve().parents[3];b=Path(__file__).parent;final='99e2e2c61a1a3c5249026921efdc6cd41ac8f21d'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def read(p):return json.loads(p.read_text())
reviews=[]
for provider in ['grok','opus']:
 p=b/'final-review'/f'final-{provider}.invocation.json';v=read(p);report=b/'final-review'/f'final-{provider}.md'
 assert v['exit_code']==0 and v['candidate']==final and v['bundle_unchanged'] and v['inputs_unchanged']
 assert not v.get('is_error');assert re.search(r'VERDICT:\s*ACCEPT(?: WITH LIMITATIONS)?\b',report.read_text())
 raw=b/'final-review'/f'final-{provider}.json';assert sha(raw)==v['response_sha256']
 reviews.append({'provider':provider,'requested_model':v['requested_model'],'reported_models':v['reported_models'],'verdict':'ACCEPT WITH LIMITATIONS' if 'VERDICT: ACCEPT WITH LIMITATIONS' in report.read_text() else 'ACCEPT','candidate':final,'bundle_sha256':v['bundle_sha256'],'invocation':str(p.relative_to(r)),'invocation_sha256':sha(p),'report':str(report.relative_to(r)),'report_sha256':sha(report),'raw_response_sha256':sha(raw)})
summary={'source_candidate':final,'kernel_execution_candidate':'a52fb748272fdc08f07d4ad8d2e2a06805b92dd6','accepted_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'substantive_source_and_evidence_accepted':True,'reviews':reviews,'reviewer_change':'User explicitly replaced future Fable reviews with native Opus; historical Fable REVISE remains unchanged. GPT6 implementation through stock Codex, no Foreman.','presentation':'Grok saw full96-input bundle; Opus saw compact JSON and a normalized proof inventory retaining all106 full explicit statements and all generated/supplemental identity/source/axiom/type hashes. All complete source and execution reports retained; same99 source and same underlying complete proof inventory. Two earlier Opus context failures provide no verdict.','closed_findings':['88aa Audit list/count mismatch corrected at a52; all18 production mutants freshly qualified.','Real production #eval/IO.userError and bare output protocol covered;65 controls=52+11+2.','Nested Lean log variable overwritten CLI path; corrected at99, fresh65 r4 controls, all65 exact pointers verified.'],'limits':['Trusted initial stores/authenticated boundaries; fixed store during invocation-only atomic batch.','Rational arithmetic, restricted lane supply policy; no deployed Balancer/fees/hooks/fidelity or machine arithmetic.','No general order independence, dynamic provenance, fairness or transaction-boundary reassociation.','Projection erases abort diagnostics; direct Result access can still inspect them.','Empty-lane inherited live/history/time fixtures are batch evidence; unused Atomic-native templates are not exercised settlement evidence.','Last-lane and last-participant mutations have identical8-false inventories; detection does not identify fault.','Lexical projection guard does not analyze arbitrary earlier-defined command macro expansion.','Supplemental/generated declarations are not additional independent mathematical claims.'],'actual_execution_identities':{'proof_Lean_production':'a52fb748','legacy11':'88aa4906 with exact relevant-dependency equivalence to a52 and99','runner65':'a52fb748 HEAD with edited dc539d harness bytes committed unchanged at99'},'delivery_pending':not (b/'archive-delivery.json').exists()}
(b/'final-review/acceptance.json').write_text(json.dumps(summary,indent=2)+'\n')
v=read(b/'scenario-to-evidence.json');v['kind']='accepted-source-and-evidence overlay; original pre-review map retained';v['candidate']=final;v['captured_utc']=summary['accepted_utc'];v['immutable_pre_review_map']={'path':str((b/'scenario-to-evidence.json').relative_to(r)),'sha256':sha(b/'scenario-to-evidence.json')};v['execution_identity_note']=summary['actual_execution_identities'];v['acceptance']='source/evidence accepted; delivery pending'
for e in v['evidence']:
 if e['id']=='compilercontrol:actual-cli-controls':
  e['artifacts']=[x.replace('runner-controls-r3','runner-controls-r4') for x in e['artifacts']];e['scope']='Fresh65 r4 controls (52+11+2), all CLI paths/output/hashes correct; actualHEADa52 with final99 harness bytes. Synthetic evidence, not production financial mutations.'
v['evidence'] += [{'id':'advisory:final-native-reviews','category':'advisory','status':'accepted-with-limitations','artifacts':[str((b/'final-review/acceptance.json').relative_to(r))]+[x['report'] for x in reviews],'scope':'Native Grok and native Opus reviewed source99 with exact actual execution bindings; no independent native command execution claimed.'},{'id':'sourcebinding:final-harness-delta','category':'sourcebinding','status':'verified','artifacts':[str((b/'implementation/log-pointer-fix-binding.json').relative_to(r)),str((b/'implementation/log-pointer-fix-independent.json').relative_to(r))],'scope':'Only2line harness rename differs from a52; all kernel/driver/spec inputs unchanged; r4 covers final harness.'}]
for row in v['scenarios']:
 row['evidence'].append('sourcebinding:final-harness-delta')
 if row['id']=='A36':row.update(status='evidence-mapped-at-candidate',pending=[]);row['evidence'].append('advisory:final-native-reviews')
 if row['id']=='A37' and (b/'archive-delivery.json').exists():
  delivery=read(b/'archive-delivery.json');assert delivery['remote_matches'] and delivery['archive_complete'];row.update(status='evidence-mapped-at-candidate',pending=[]);row['evidence'].append('delivery:verified-branch-and-archive')
 if (r/'openspec/changes/archive/2026-09-07-atomic-synchronization').exists():row['path']=row['path'].replace('openspec/changes/atomic-synchronization','openspec/changes/archive/2026-09-07-atomic-synchronization')
if (b/'archive-delivery.json').exists():
 v['evidence'].append({'id':'delivery:verified-branch-and-archive','category':'delivery','status':'verified','artifacts':[str((b/'delivery.json').relative_to(r)),str((b/'archive-delivery.json').relative_to(r))],'scope':'Actual authorized branch push and archive, no main merge.'});v['acceptance']='accepted, delivered and archived'
assert len(v['scenarios'])==49 and len({x['id'] for x in v['scenarios']})==49
ids={x['id'] for x in v['evidence']};assert len(ids)==len(v['evidence']);assert all(set(x['evidence'])<=ids for x in v['scenarios'])
(b/'scenario-map-final.json').write_text(json.dumps(v,indent=2)+'\n');pending=[x['id'] for x in v['scenarios'] if x['pending']]
(b/'coverage-final.md').write_text(f'''Source/evidence accepted at `{final}`. All49 scenarios mapped; {49-len(pending)} complete and {len(pending)} pending: {', '.join(pending) or 'none'}. Original scenario-to-evidence.json and r1/r2/r3 snapshots remain unchanged. This overlay binds r4 control evidence and actual Grok/Opus verdicts, preserving all original execution identities.\n\n135 runtime comparisons,18 production mutants,65 actual controls,14 Lean commands and11 legacy suites are separate inventories, counted once. Imported357 theorems include106 explicit and251 generated;496 supplemental declarations are axiom-audit scope, not further theorem claims. See final-review/acceptance.json for exact models, hashes, closed findings and limits.\n''')
print('accepted reviews',len(reviews),'scenarios',49,'pending',pending)
