import Defialgebra.Obstruction
import Defialgebra.ConvexGeometry
import Defialgebra.Polarity
import Defialgebra.Lattice
import Defialgebra.Discharge
import Defialgebra.Permission
import Defialgebra.Interface
import Defialgebra.FlowPolarity
import Defialgebra.Nary
import Defialgebra.Extremal
