from pathlib import Path
import json,hashlib
out=Path(__file__).parent;root=Path('/home/charl/.cache/defiformal-program/program-execution-20260919/astra-grok-r5')
findings=[
 {'id':'R5-01','severity':'high','title':'Live CLI accepts a recomputed compatibility failure','location':'lean/DefiKernel/Certificates/Delivered.lean:201-256','evidence':['cli-overlap.stdout','overlap-run.json','Probes.lean'],'detail':'Two valid components sequentially transfer USD3 each across the same alice/bob cells. The live check CLI returns accepted, failure=null, compositionCompatible=false, alice=4,bob=6. The compatibility detector is working; checkRun never gates accepted on its result. This contradicts the frozen report-policy requirement that required reached families are true.','repair':'Include required family outcomes in report acceptance policy and prove/use that policy across delivered modes. Preserve sequential success as a raw observation; do not label a failed required compatibility check accepted.'},
 {'id':'R5-02','severity':'high','title':'Host validator omits new library inventory and compiled-host binding','location':'scripts/run_certificate_fixtures.py:272-326','evidence':['host-probes.stdout','host_probes.py'],'detail':'Intact passes and empty dependencies refuse, but missing/substituted library_compiler_records, modified Arithmetic/Operations.lean, and changed TrustedHost.lean constants all pass. The validator checks 11 fixed paths and JSON metadata, never the added library record or compiled constants. The existing arithmetic token happens to match the frozen Operations source; this does not establish drift detection.','repair':'Validate the required library path/hash/theorem/token against actual source and compiler/audit records; bind all host constants consumed by the built checker to the validated inventory. Add intact and independently altered controls.'},
 {'id':'R5-03','severity':'medium','title':'Indexed compatibility repair still lacks the required decoded branch contract','location':'lean/DefiKernel/Certificates/Check.lean:403-440','evidence':['adapter-probes-corrected.stdout','AdapterProbes.lean'],'detail':'Original-step boundaries are repaired: differing alice/vault actors yield true, forcing boundary0 yields false. Two-component overlap yields false; repeated component0 invokes yield true against an empty right branch. Revoke-only returns notApplicable. A comment declaring component0 versus all other IDs is not a decoded branch pair or a proved correspondence to the intended composition contract. Author CompatibilityExamples tests a separate example domain and Parallel.admit directly, not the certificate adapter. Its conflictRefusal also treats every error as a conflict, though the independent exact-constructor probe confirms this particular witness is a conflict.','repair':'Encode/validate an actual declared branch decomposition, or obtain an explicit accepted contract for the restricted decomposition; connect recomputed footprints to checkCompatibility_ok_iff. Specify and test issue/revoke behavior and nonempty success/refusal on the actual adapter.'},
 {'id':'R5-04','severity':'medium','title':'Correspondence inventory remains partial','location':'lean/DefiKernel/Certificates/KernelCorrespondence.lean; lean/DefiKernel/Certificates/Soundness.lean','evidence':['audit-r5-corrected.stdout'],'detail':'The new policy-projection theorems are valid at their written scopes. Typed raw success omits receipt. Historical raw step success omits world/receipt/outputs; historical raw run proves only outputs/index/cursorFailure. Delivered run theorem assumes kernelFailure=none and omits receipt/cursorFailure, so failure cursors remain outside it. Delivered step-error and full source-guard coverage are absent; the inventory omits T-checkIR-step-error entirely. Historical raw step-error uses payload.index whereas frozen specification says nextIndex=0, an unresolved contract discrepancy. Canonical-byte inverse is already proved and was independently axiom-checked; it is not an open gap.','repair':'Complete the exact raw and delivered field equations and all failure/guard branches without shrinking the frozen domain; reconcile step-index contract explicitly. Preserve accepted codec theorems.'},
 {'id':'R5-05','severity':'medium','title':'Independent positive codec and scenario evidence remains open','location':'lean/DefiKernel/Certificates/Tests.lean:551; scripts/run_certificate_fixtures.py','evidence':['build.stdout'],'detail':'The canonical positive companion is a Lean encoder/decode roundtrip, not an independently supplied expected structural IR with changed-IR comparator control. S13/S14/S80 are correctly left open. Neither the full54 fixture nor16-mutant campaign was rerun for R5; inherited R4 evidence is not R5 evidence.','repair':'Supply a new named canonical raw input and independent expected IR, discriminate changed expected IR, and execute the required scenarios against the final delivered source before qualified delivery.'},
 {'id':'R5-06','severity':'low','title':'Delivered diagnostics retain contradictory or mislocated fields','location':'lean/DefiKernel/Certificates/Delivered.lean:sourceIdentityFailure/checkTyped; lean/DefiKernel/Certificates/Check.lean:356','evidence':['probes.stdout','cli-library.stdout'],'detail':'A successfully discharged library remains in outstanding. Wrong audit_record produces staleSource.compiler_record with null payload. These are report-field defects, not failures of the addition proof.','repair':'Derive outstanding from actual discharge and report the failing audit field separately.'}
]
(out/'findings.json').write_text(json.dumps(findings,indent=2)+'\n')
accepted={p:hashlib.sha256((root/p).read_bytes()).hexdigest() for p in ['lean/DefiKernel/Certificates/LibraryInstantiation.lean','lean/DefiKernel/Certificates/TrustedHost.lean']}
verdict={'schema':'defiformal-independent-review/v1','reviewer':{'harness_assignment':'gpt-6-astra','reasoning_effort':'medium','provider_telemetry_claimed':False},'candidate':'Grok20260919R5','candidate_archive_sha256':'64092ff16a945cc825cc076eecc0df01a27fc36e19ffa0fc7a65293604f20b2a','verdict':'REJECT_PRODUCTION_CHECKER_ACCEPT_SCOPED_LIBRARY_HELPERS','accepted_exact_sources':accepted,'accepted_scope':'Arithmetic extraction/executable checking helpers, their stated Lean theorems, and static pinned identity constants only. No default root/CLI routing or qualified certificate acceptance.','full_P19_accepted':False,'full_P20_accepted':False,'P20_21_3_closed':False,'P37_accepted':False,'findings':'findings.json','integration_owner':'root','production_fixes_authored':False,'commit_or_push_performed':False}
(out/'verdict.json').write_text(json.dumps(verdict,indent=2)+'\n')
