import DefiKernel.Typed.Types
import DefiKernel.Typed.Expr
import DefiKernel.Typed.Authority
import DefiKernel.Typed.Transition
import DefiKernel.Typed.Examples
import DefiKernel.Typed.Acceptance
import DefiKernel.Typed.ExprTests
import DefiKernel.Typed.AuthorityTests
#check DefiKernel.Typed.numericRat_numericValue
#check DefiKernel.Typed.numericValue_numericRat
#check DefiKernel.Typed.Expr.eval_congr
#check DefiKernel.Typed.readBalance_congr
#check DefiKernel.Typed.Expr.eval_congr_of_resolved
#check DefiKernel.Typed.issueCapability_ok_iff
#check DefiKernel.Typed.issueCapability_admin
#check DefiKernel.Typed.lookup_nextId
#check DefiKernel.Typed.issueCapability_fresh
#check DefiKernel.Typed.issueCapability_preserves_other
#check DefiKernel.Typed.issueCapability_ne_existing
#check DefiKernel.Typed.revokeCapability_ok_iff
#check DefiKernel.Typed.revokeCapability_admin
#check DefiKernel.Typed.revokeCapability_tombstone
#check DefiKernel.Typed.revokeCapability_preserves_other
#check DefiKernel.Typed.authorizesId_iff
#check DefiKernel.Typed.hasAuthority_iff
#check DefiKernel.Typed.hasAuthority_duplicate
#check DefiKernel.Typed.revokeCapability_cannot_use
#check DefiKernel.Typed.issueCapability_keeps_revoked
#check DefiKernel.Typed.applyEvaluated_ok_iff
#check DefiKernel.Typed.execute_ok_iff
#check DefiKernel.Typed.applyEvaluated_accounting
#check DefiKernel.Typed.applyEvaluated_locality
#check DefiKernel.Typed.applyEvaluated_debit_authority
#check DefiKernel.Typed.applyEvaluated_supply_authority
#check DefiKernel.Typed.execute_evaluated
#check DefiKernel.Typed.execute_preserves_capabilities
#check DefiKernel.Typed.execute_nonnegative
#check DefiKernel.Typed.execute_invocation_authority
#check DefiKernel.Typed.execute_debit_authority
#check DefiKernel.Typed.execute_supply_authority
#check DefiKernel.Typed.execute_accounting_and_locality
#check DefiKernel.Typed.execute_reads_and_domain
#check DefiKernel.Typed.Evaluated.effect_cons
#check DefiKernel.Typed.Evaluated.supply_cons
#check DefiKernel.Typed.Examples.allCells_complete
#check DefiKernel.Typed.Examples.allCells_nodup
#check DefiKernel.Typed.Acceptance.transfer_executed
#check DefiKernel.Typed.Acceptance.deposit_executed
#check DefiKernel.Typed.Acceptance.withdraw_executed
#check DefiKernel.Typed.Acceptance.borrow_executed
#check DefiKernel.Typed.Acceptance.revoked_request_refused
#check DefiKernel.Typed.Acceptance.stale_oracle_refused
#check DefiKernel.Typed.Acceptance.issued_used_revoked_refused
#check DefiKernel.Typed.Acceptance.reference_invocation_authority
#check DefiKernel.Typed.Acceptance.reference_capabilities_preserved
#check DefiKernel.Typed.ExprTests.price_conversion_exact
#check DefiKernel.Typed.ExprTests.inverse_price_exact
#check DefiKernel.Typed.ExprTests.zero_division_refused
#check DefiKernel.Typed.ExprTests.unrelated_balance_preserved
#check DefiKernel.Typed.authority_checks_pass
